---
title: "STAC32: Applications of Statistical Methods"
author: "Lecture notes"
header-includes:
   - \usepackage{multicol}
output: 
  beamer_presentation:
    latex_engine: lualatex
    slide_level: 2
    df_print: kable
    theme: "AnnArbor"
    colortheme: "dove"
---



```{r copyable-slides-c32-1, child="preliminaries.Rmd", echo=F}
```

# Course outline 

```{r copyable-slides-c32-2, child="outline_c32.Rmd"}
```


# Running R

```{r copyable-slides-c32-3, child="running_R.Rmd"}
```

# Reading in data

```{r copyable-slides-c32-4, child="readfile_R.Rmd"}
```

# Making graphs

```{r copyable-slides-c32-5, child="graphs_R.Rmd"}
```

# Numerical summaries: more detailed

```{r copyable-slides-c32-6, child="numsum_R.Rmd"}
```

# Statistical Inference

```{r copyable-slides-c32-7, child="inference_R.Rmd"}
```

# Writing reports

```{r copyable-slides-c32-8, child="reports_R.Rmd"}
```


# Tidying and organizing data

```{r copyable-slides-c32-9, child="tidying_R.Rmd"}
```

# Case study 1: the windmill data

```{r copyable-slides-c32-10, child="windmill.Rmd"}
```


# Case study 3: Asphalt

```{r copyable-slides-c32-11, child="asphalt.Rmd"}
```



# Regression with categorical variables

```{r copyable-slides-c32-12, child="with_categ_R.Rmd"}
```

# Functions

```{r copyable-slides-c32-13, child="functions.Rmd"}
```

# Dates and times

```{r copyable-slides-c32-14, child="dates_and_times.Rmd"}
```

# Miscellanea

```{r copyable-slides-c32-15, child="miscellanea.Rmd"}
```



# the end of the notes

