# anova done the bayes way

## packages

```{r anova-bayes-1}
library(tidyverse)
library(rstan)
```

## grab some data

```{r anova-bayes-2}
my_url <- "http://ritsokiguess.site/datafiles/jumping.txt"
rats0 <- read_delim(my_url," ")
rats0
```

plot

```{r anova-bayes-3}
ggplot(rats0, aes(x=group, y=density))+geom_boxplot()
```

turn the group IDs into numbers

```{r anova-bayes-4}
rats0 %>% mutate(group_fct=fct_inorder(group),
              group_no=as.integer(group_fct)) -> rats
rats
```

these groups are now in the right order:

```{r anova-bayes-5}
ggplot(rats, aes(x=group_fct, y=density))+geom_boxplot()
```

## stan model

model code in `anova.stan`:

```{r anova-bayes-6}
anova_compiled=stan_model("anova.stan")
```

## sample from it

```{r anova-bayes-7}
anova_data=list(n_obs=30, n_group=3, density=rats$density, group_no=rats$group_no)
anova_samples=sampling(anova_compiled, data=anova_data)
```

```{r anova-bayes-8}
traceplot(anova_samples)
```

```{r anova-bayes-9}
anova_samples
```


```{r anova-bayes-10}
anova_ext=extract(anova_samples)
glimpse(anova_ext)
```

```{r anova-bayes-11}
anova_ext$sigma %>% as_tibble() %>% 
  ggplot(aes(x=value))+geom_histogram(bins=20)
```

```{r anova-bayes-12}
anova_ext$sigma %>% as_tibble() %>% 
  ggplot(aes(x=value))+geom_density()
```

```{r anova-bayes-13}
anova_ext$mu %>% as_tibble() %>% 
  gather(group, density, everything()) %>% 
  ggplot(aes(x=group, y=density)) + geom_boxplot()
```

posterior distributions of group *means*

```{r anova-bayes-14}
anova_ext$mu %>% as_tibble() %>% 
  gather(group, density, everything()) %>% 
  ggplot(aes(x=density, colour=group)) + geom_density()
```


predictive distributions (compare with observed data)

```{r anova-bayes-15}
cbind(mu=anova_ext$mu, sigma=anova_ext$sigma) %>% 
  as_tibble() %>% 
  gather(group, mean, V1:V3) %>% 
  mutate(sim_data=rnorm(12000, mean, sigma)) -> sims
sims %>% sample_n(10)
sims %>% 
  mutate(group=fct_recode(group, Control="V1", Lowjump="V2", Highjump="V3")) -> sims2
sims2
```

```{r anova-bayes-16}
ggplot(sims2, aes(x=sim_data)) + geom_density() +
  geom_point(data=rats, aes(x=density, y=0)) + 
  facet_wrap(~group)
```

