---
title: "STAC33 2025"
format: html
editor: visual
---

sitting outside on the long curved seat for a change of scene. Not sure
how long I will stay awake.

ideas:

-   R studio connection and quarto docs
-   graphs (including normal quantile): `graphs_c33`
-   numerical summaries
-   choosing stuff (dplyr)
-   inference (faster): `inference_c33`
    -   1-sample
    -   2-sample
    -   matched pairs
-   assumptions: `assumptions_c33`
-   bootstrap with CIs and simulation (same or different sections?) `simboot`
-   power rewritten: `power_c33`
-   sign test, mood median
-   anova as now
-   tidying
-   regression as now
-   functions
-   stan as now

new stuff needed

-   abbreviated version of normal-theory inference
-   coherent bootstrap and simulation

think about how I am making it more challenging (maybe it's mostly more
stuff in less time).

is there room for more computationally-intensive stuff? (find out about
what might be useful). Make a big deal about simulation.

also think about how c32 might change (or use any of the new stuff)