<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.340">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Factor analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="factor_files/libs/clipboard/clipboard.min.js"></script>
<script src="factor_files/libs/quarto-html/quarto.js"></script>
<script src="factor_files/libs/quarto-html/popper.min.js"></script>
<script src="factor_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="factor_files/libs/quarto-html/anchor.min.js"></script>
<link href="factor_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="factor_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="factor_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="factor_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="factor_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="factor.html"><i class="bi bi-file-slides"></i>RevealJS</a></li><li><a href="factor.pdf"><i class="bi bi-file-pdf"></i>Beamer</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Factor analysis</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="vs.-principal-components" class="level2">
<h2 class="anchored" data-anchor-id="vs.-principal-components">Vs. principal components</h2>
<ul>
<li><p>Principal components:</p>
<ul>
<li><p>Purely mathematical.</p></li>
<li><p>Find eigenvalues, eigenvectors of correlation matrix.</p></li>
<li><p>No testing whether observed components reproducible, or even probability model behind it.</p></li>
</ul></li>
<li><p>Factor analysis:</p>
<ul>
<li><p>some way towards fixing this (get test of appropriateness)</p></li>
<li><p>In factor analysis, each variable modelled as: “common factor” (eg. verbal ability) and “specific factor” (left over).</p></li>
<li><p>Choose the common factors to “best” reproduce pattern seen in correlation matrix.</p></li>
<li><p>Iterative procedure, different answer from principal components.</p></li>
</ul></li>
</ul>
</section>
<section id="packages" class="level2">
<h2 class="anchored" data-anchor-id="packages">Packages</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggbiplot)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(conflicted)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">conflict_prefer</span>(<span class="st">"mutate"</span>, <span class="st">"dplyr"</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">conflict_prefer</span>(<span class="st">"select"</span>, <span class="st">"dplyr"</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">conflict_prefer</span>(<span class="st">"filter"</span>, <span class="st">"dplyr"</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">conflict_prefer</span>(<span class="st">"arrange"</span>, <span class="st">"dplyr"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="example" class="level2">
<h2 class="anchored" data-anchor-id="example">Example</h2>
<ul>
<li><p>145 children given 5 tests, called PARA, SENT, WORD, ADD and DOTS. 3 linguistic tasks (paragraph comprehension, sentence completion and word meaning), 2 mathematical ones (addition and counting dots).</p></li>
<li><p>Correlation matrix of scores on the tests:</p></li>
</ul>
<pre><code>
para 1     0.722 0.714 0.203 0.095
sent 0.722 1     0.685 0.246 0.181
word 0.714 0.685 1     0.170 0.113
add  0.203 0.246 0.170 1     0.585
dots 0.095 0.181 0.113 0.585 1
</code></pre>
<ul>
<li>Is there small number of underlying “constructs” (unobservable) that explains this pattern of correlations?</li>
</ul>
</section>
<section id="to-start-principal-components" class="level2">
<h2 class="anchored" data-anchor-id="to-start-principal-components">To start: principal components</h2>
<p>Using correlation matrix. Read that first:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>my_url <span class="ot">&lt;-</span> <span class="st">"http://ritsokiguess.site/datafiles/rex2.txt"</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>kids <span class="ot">&lt;-</span> <span class="fu">read_delim</span>(my_url, <span class="st">" "</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>kids</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 6
  test   para  sent  word   add  dots
  &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 para  1     0.722 0.714 0.203 0.095
2 sent  0.722 1     0.685 0.246 0.181
3 word  0.714 0.685 1     0.17  0.113
4 add   0.203 0.246 0.17  1     0.585
5 dots  0.095 0.181 0.113 0.585 1    </code></pre>
</div>
</div>
</section>
<section id="principal-components-on-correlation-matrix" class="level2">
<h2 class="anchored" data-anchor-id="principal-components-on-correlation-matrix">Principal components on correlation matrix</h2>
<p>Turn into R <code>matrix</code>, using column <code>test</code> as column names:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>kids <span class="sc">%&gt;%</span> </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">column_to_rownames</span>(<span class="st">"test"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">as.matrix</span>() <span class="ot">-&gt;</span> m</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Principal components:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>kids<span class="fl">.0</span> <span class="ot">&lt;-</span> <span class="fu">princomp</span>(<span class="at">covmat =</span> m) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>I used <code>kids.0</code> here since I want <code>kids.1</code> and <code>kids.2</code> later.</p>
</section>
<section id="scree-plot" class="level2">
<h2 class="anchored" data-anchor-id="scree-plot">Scree plot</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggscreeplot</span>(kids<span class="fl">.0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="factor_files/figure-html/bFactor-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="principal-component-results" class="level2">
<h2 class="anchored" data-anchor-id="principal-component-results">Principal component results</h2>
<ul>
<li>Need 2 components. Loadings:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>kids<span class="fl">.0</span><span class="sc">$</span>loadings</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Loadings:
     Comp.1 Comp.2 Comp.3 Comp.4 Comp.5
para  0.534  0.245  0.114         0.795
sent  0.542  0.164         0.660 -0.489
word  0.523  0.247 -0.144 -0.738 -0.316
add   0.297 -0.627  0.707              
dots  0.241 -0.678 -0.680         0.143

               Comp.1 Comp.2 Comp.3 Comp.4 Comp.5
SS loadings       1.0    1.0    1.0    1.0    1.0
Proportion Var    0.2    0.2    0.2    0.2    0.2
Cumulative Var    0.2    0.4    0.6    0.8    1.0</code></pre>
</div>
</div>
</section>
<section id="comments" class="level2">
<h2 class="anchored" data-anchor-id="comments">Comments</h2>
<ul>
<li><p>First component has a bit of everything, though especially the first three tests.</p></li>
<li><p>Second component rather more clearly <code>add</code> and <code>dots</code>.</p></li>
<li><p>No scores, plots since no actual data.</p></li>
<li><p>See how factor analysis compares on these data.</p></li>
</ul>
</section>
<section id="factor-analysis" class="level2">
<h2 class="anchored" data-anchor-id="factor-analysis">Factor analysis</h2>
<ul>
<li><p>Specify number of factors first, get solution with exactly that many factors.</p></li>
<li><p>Includes hypothesis test, need to specify how many children wrote the tests.</p></li>
<li><p>Works from correlation matrix via <code>covmat</code> or actual data, like <code>princomp</code>.</p></li>
<li><p>Introduces extra feature, <em>rotation</em>, to make interpretation of loadings (factor-variable relation) easier.</p></li>
</ul>
</section>
<section id="factor-analysis-for-the-kids-data" class="level2">
<h2 class="anchored" data-anchor-id="factor-analysis-for-the-kids-data">Factor analysis for the kids data</h2>
<ul>
<li><p>Create “covariance list” to include number of children who wrote the tests.</p></li>
<li><p>Feed this into <code>factanal</code>, specifying how many factors (2).</p></li>
<li><p>Start with the matrix we made before.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>m</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      para  sent  word   add  dots
para 1.000 0.722 0.714 0.203 0.095
sent 0.722 1.000 0.685 0.246 0.181
word 0.714 0.685 1.000 0.170 0.113
add  0.203 0.246 0.170 1.000 0.585
dots 0.095 0.181 0.113 0.585 1.000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>ml <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">cov =</span> m, <span class="at">n.obs =</span> <span class="dv">145</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>kids<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">factanal</span>(<span class="at">factors =</span> <span class="dv">2</span>, <span class="at">covmat =</span> ml)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="uniquenesses" class="level2">
<h2 class="anchored" data-anchor-id="uniquenesses">Uniquenesses</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>kids<span class="fl">.2</span><span class="sc">$</span>uniquenesses</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     para      sent      word       add      dots 
0.2424457 0.2997349 0.3272312 0.5743568 0.1554076 </code></pre>
</div>
</div>
<ul>
<li><p>Uniquenesses say how “unique” a variable is (size of specific factor). Small uniqueness means that the variable is summarized by a factor (good).</p></li>
<li><p>Very large uniquenesses are bad; <code>add</code>’s uniqueness is largest but not large enough to be worried about.</p></li>
<li><p>Also see “communality” for this idea, where <em>large</em> is good and <em>small</em> is bad.</p></li>
</ul>
</section>
<section id="loadings" class="level2">
<h2 class="anchored" data-anchor-id="loadings">Loadings</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>kids<span class="fl">.2</span><span class="sc">$</span>loadings</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Loadings:
     Factor1 Factor2
para 0.867          
sent 0.820   0.166  
word 0.816          
add  0.167   0.631  
dots         0.918  

               Factor1 Factor2
SS loadings      2.119   1.282
Proportion Var   0.424   0.256
Cumulative Var   0.424   0.680</code></pre>
</div>
</div>
<ul>
<li>Loadings show how each factor depends on variables. Blanks indicate “small”, less than 0.1.</li>
</ul>
</section>
<section id="comments-1" class="level2">
<h2 class="anchored" data-anchor-id="comments-1">Comments</h2>
<ul>
<li><p>Factor 1 clearly the “linguistic” tasks, factor 2 clearly the “mathematical” ones.</p></li>
<li><p>Two factors together explain 68% of variability (like regression R-squared).</p></li>
<li><p>Which variables belong to which factor is <em>much</em> clearer than with principal components.</p></li>
</ul>
</section>
<section id="are-2-factors-enough" class="level2">
<h2 class="anchored" data-anchor-id="are-2-factors-enough">Are 2 factors enough?</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>kids<span class="fl">.2</span><span class="sc">$</span>STATISTIC</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>objective 
0.5810578 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>kids<span class="fl">.2</span><span class="sc">$</span>dof</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>kids<span class="fl">.2</span><span class="sc">$</span>PVAL</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>objective 
 0.445898 </code></pre>
</div>
</div>
<p>P-value not small, so 2 factors OK.</p>
</section>
<section id="factor" class="level2">
<h2 class="anchored" data-anchor-id="factor">1 factor</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>kids<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">factanal</span>(<span class="at">factors =</span> <span class="dv">1</span>, <span class="at">covmat =</span> ml)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>kids<span class="fl">.1</span><span class="sc">$</span>STATISTIC</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>objective 
 58.16534 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>kids<span class="fl">.1</span><span class="sc">$</span>dof</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>kids<span class="fl">.1</span><span class="sc">$</span>PVAL</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   objective 
2.907856e-11 </code></pre>
</div>
</div>
<p>1 factor rejected (P-value small). Definitely need more than 1.</p>
</section>
<section id="places-rated-again" class="level2">
<h2 class="anchored" data-anchor-id="places-rated-again">Places rated, again</h2>
<ul>
<li>Read data, transform, rerun principal components, get biplot:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>my_url <span class="ot">&lt;-</span> <span class="st">"http://ritsokiguess.site/datafiles/places.txt"</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>places0 <span class="ot">&lt;-</span> <span class="fu">read_table2</span>(my_url)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `read_table2()` was deprecated in readr 2.0.0.
ℹ Please use `read_table()` instead.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>places0 <span class="sc">%&gt;%</span> </span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mutate</span>(<span class="fu">across</span>(<span class="sc">-</span>id, \(x) <span class="fu">log</span>(x))) <span class="ot">-&gt;</span> places</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>places <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>id) <span class="ot">-&gt;</span> places_numeric</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>places<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">princomp</span>(places_numeric, <span class="at">cor =</span> <span class="cn">TRUE</span>)</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>g <span class="ot">&lt;-</span> <span class="fu">ggbiplot</span>(places<span class="fl">.1</span>, <span class="at">labels =</span> places<span class="sc">$</span>id,</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">labels.size =</span> <span class="fl">0.8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>This is all exactly as for principal components (nothing new here).</li>
</ul>
</section>
<section id="the-biplot" class="level2">
<h2 class="anchored" data-anchor-id="the-biplot">The biplot</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>g</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="factor_files/figure-html/bFactor-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="comments-2" class="level2">
<h2 class="anchored" data-anchor-id="comments-2">Comments</h2>
<ul>
<li>Most of the criteria are part of components 1 <em>and</em> 2.</li>
<li>If we can rotate the arrows counterclockwise:
<ul>
<li>economy and crime would point straight up
<ul>
<li>part of component 2 only</li>
</ul></li>
<li>health and education would point to the right
<ul>
<li>part of component 1 only</li>
</ul></li>
</ul></li>
<li>would be easier to see which variables belong to which component.</li>
<li>Factor analysis includes a rotation to help with interpretation.</li>
</ul>
</section>
<section id="factor-analysis-1" class="level2">
<h2 class="anchored" data-anchor-id="factor-analysis-1">Factor analysis</h2>
<ul>
<li>Have to pick a number of factors <em>first</em>.</li>
<li>Do this by running principal components and looking at scree plot.</li>
<li>In this case, 3 factors seemed good (revisit later):</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>places<span class="fl">.3</span> <span class="ot">&lt;-</span> <span class="fu">factanal</span>(places_numeric, <span class="dv">3</span>, <span class="at">scores =</span> <span class="st">"r"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>There are different ways to get factor scores. These called “regression” scores.</li>
</ul>
</section>
<section id="a-bad-biplot" class="level2">
<h2 class="anchored" data-anchor-id="a-bad-biplot">A bad biplot</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">biplot</span>(places<span class="fl">.3</span><span class="sc">$</span>scores, places<span class="fl">.3</span><span class="sc">$</span>loadings,</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="at">xlabs =</span> places<span class="sc">$</span>id)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="factor_files/figure-html/bFactor-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="comments-3" class="level2">
<h2 class="anchored" data-anchor-id="comments-3">Comments</h2>
<ul>
<li>I have to find a way to make a better biplot!</li>
<li>Some of the variables now point straight up and some straight across (if you look carefully for the red arrows among the black points).</li>
<li>This should make the factors more interpretable than the components were.</li>
</ul>
</section>
<section id="factor-loadings" class="level2">
<h2 class="anchored" data-anchor-id="factor-loadings">Factor loadings</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>places<span class="fl">.3</span><span class="sc">$</span>loadings</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Loadings:
         Factor1 Factor2 Factor3
climate                   0.994 
housing   0.360   0.482   0.229 
health    0.884   0.164         
crime     0.115   0.400   0.205 
trans     0.414   0.460         
educate   0.511                 
arts      0.655   0.552   0.102 
recreate  0.148   0.714         
econ              0.318  -0.114 

               Factor1 Factor2 Factor3
SS loadings      1.814   1.551   1.120
Proportion Var   0.202   0.172   0.124
Cumulative Var   0.202   0.374   0.498</code></pre>
</div>
</div>
</section>
<section id="comments-on-loadings" class="level2">
<h2 class="anchored" data-anchor-id="comments-on-loadings">Comments on loadings</h2>
<ul>
<li>These are at least somewhat clearer than for the principal components:</li>
<li>Factor 1: health, education, arts: “well-being”</li>
<li>Factor 2: housing, transportation, arts (again), recreation: “places to be”</li>
<li>Factor 3: climate (only): “climate”</li>
<li>In this analysis, economic factors don’t seem to be important.</li>
</ul>
</section>
<section id="factor-scores" class="level2">
<h2 class="anchored" data-anchor-id="factor-scores">Factor scores</h2>
<ul>
<li>Make a dataframe with the city IDs and factor scores:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(<span class="at">id =</span> places<span class="sc">$</span>id, places<span class="fl">.3</span><span class="sc">$</span>scores) <span class="sc">%&gt;%</span> </span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">as_tibble</span>() <span class="ot">-&gt;</span> places_scores</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>Make percentile ranks again (for checking):</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>places <span class="sc">%&gt;%</span> </span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mutate</span>(<span class="fu">across</span>(<span class="sc">-</span>id, \(x) <span class="fu">percent_rank</span>(x))) <span class="ot">-&gt;</span> places_pr</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="highest-scores-on-factor-1-well-being" class="level2">
<h2 class="anchored" data-anchor-id="highest-scores-on-factor-1-well-being">Highest scores on factor 1, “well-being”:</h2>
<ul>
<li>for the top 4 places:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>places_scores <span class="sc">%&gt;%</span> </span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">slice_max</span>(Factor1, <span class="at">n =</span> <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
     id Factor1 Factor2 Factor3
  &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
1   213    2.47   1.78    0.506
2    65    2.39   0.925  -0.287
3   234    2.32   0.122   0.524
4   314    2.22   0.671   0.521</code></pre>
</div>
</div>
</section>
<section id="check-percentile-ranks-for-factor-1" class="level2">
<h2 class="anchored" data-anchor-id="check-percentile-ranks-for-factor-1">Check percentile ranks for factor 1</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>places_pr <span class="sc">%&gt;%</span> </span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(id, health, educate, arts) <span class="sc">%&gt;%</span> </span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(id <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">213</span>, <span class="dv">65</span>, <span class="dv">234</span>, <span class="dv">314</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
     id health educate  arts
  &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
1    65  0.997   0.963 0.997
2   213  1       0.723 1    
3   234  0.991   1     0.985
4   314  0.985   0.994 0.991</code></pre>
</div>
</div>
<ul>
<li>These are definitely high on the well-being variables.</li>
<li>City #213 is not so high on education, but is highest of all on the others.</li>
</ul>
</section>
<section id="highest-scores-on-factor-2-places-to-be" class="level2">
<h2 class="anchored" data-anchor-id="highest-scores-on-factor-2-places-to-be">Highest scores on factor 2, “places to be”:</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>places_scores <span class="sc">%&gt;%</span> </span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">slice_max</span>(Factor2, <span class="at">n =</span> <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
     id Factor1 Factor2 Factor3
  &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
1   318  -1.01     2.05 -0.0957
2    12  -0.540    2.02 -3.80  
3   168  -1.35     1.94  0.273 
4    44  -0.149    1.92 -0.556 </code></pre>
</div>
</div>
</section>
<section id="check-percentile-ranks-for-factor-2" class="level2">
<h2 class="anchored" data-anchor-id="check-percentile-ranks-for-factor-2">Check percentile ranks for factor 2</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>places_pr <span class="sc">%&gt;%</span> </span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(id, housing, trans, arts, recreate) <span class="sc">%&gt;%</span> </span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(id <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">318</span>, <span class="dv">12</span>, <span class="dv">168</span>, <span class="dv">44</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
     id housing trans  arts recreate
  &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;
1    12   0.933 0.729 0.604    0.896
2    44   0.927 0.963 0.735    0.988
3   168   0.832 0.872 0.442    0.979
4   318   0.881 0.744 0.668    0.963</code></pre>
</div>
</div>
<ul>
<li>These are definitely high on housing and recreation.</li>
<li>Some are (very) high on transportation, but not so much on arts.</li>
<li>Could look at more cities to see if #168 being low on arts is a fluke.</li>
</ul>
</section>
<section id="highest-scores-on-factor-3-climate" class="level2">
<h2 class="anchored" data-anchor-id="highest-scores-on-factor-3-climate">Highest scores on factor 3, “climate”:</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>places_scores <span class="sc">%&gt;%</span> </span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">slice_max</span>(Factor3, <span class="at">n =</span> <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
     id Factor1 Factor2 Factor3
  &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
1   227  -0.184   0.385    2.04
2   218   0.881   0.897    2.02
3   269   0.932   1.19     1.98
4   270   1.50    1.84     1.94</code></pre>
</div>
</div>
</section>
<section id="check-percentile-ranks-for-factor-3" class="level2">
<h2 class="anchored" data-anchor-id="check-percentile-ranks-for-factor-3">Check percentile ranks for factor 3</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>places_pr <span class="sc">%&gt;%</span> </span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(id, climate) <span class="sc">%&gt;%</span> </span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(id <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">227</span>, <span class="dv">218</span>, <span class="dv">269</span>, <span class="dv">270</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
     id climate
  &lt;dbl&gt;   &lt;dbl&gt;
1   218   0.997
2   227   0.991
3   269   0.994
4   270   0.997</code></pre>
</div>
</div>
<p>This is very clear.</p>
</section>
<section id="uniquenesses-1" class="level2">
<h2 class="anchored" data-anchor-id="uniquenesses-1">Uniquenesses</h2>
<ul>
<li>We said earlier that the economy was not part of any of our factors:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>places<span class="fl">.3</span><span class="sc">$</span>uniquenesses</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  climate   housing    health     crime     trans   educate      arts  recreate 
0.0050000 0.5859175 0.1854084 0.7842407 0.6165449 0.7351921 0.2554663 0.4618143 
     econ 
0.8856382 </code></pre>
</div>
</div>
<ul>
<li>The higher the uniqueness, the less the variable concerned is part of any of our factors (and that maybe another factor is needed to accommodate it).</li>
<li>This includes economy and maybe crime.</li>
</ul>
</section>
<section id="test-of-significance" class="level2">
<h2 class="anchored" data-anchor-id="test-of-significance">Test of significance</h2>
<p>We can test whether the three factors that we have is enough, or whether we need more to describe our data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>places<span class="fl">.3</span><span class="sc">$</span>PVAL</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   objective 
1.453217e-14 </code></pre>
</div>
</div>
<ul>
<li>3 factors are not enough.</li>
<li>What would 5 factors look like?</li>
</ul>
</section>
<section id="five-factors" class="level2">
<h2 class="anchored" data-anchor-id="five-factors">Five factors</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>places<span class="fl">.5</span> <span class="ot">&lt;-</span> <span class="fu">factanal</span>(places_numeric, <span class="dv">5</span>, <span class="at">scores =</span> <span class="st">"r"</span>)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>places<span class="fl">.5</span><span class="sc">$</span>loadings</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Loadings:
         Factor1 Factor2 Factor3 Factor4 Factor5
climate                           0.131   0.559 
housing   0.286   0.505   0.289  -0.113   0.475 
health    0.847   0.214                   0.187 
crime             0.196   0.143   0.948   0.181 
trans     0.389   0.515           0.175         
educate   0.534                                 
arts      0.611   0.564           0.172   0.145 
recreate          0.705           0.115   0.136 
econ                      0.978   0.135         

               Factor1 Factor2 Factor3 Factor4 Factor5
SS loadings      1.628   1.436   1.087   1.023   0.658
Proportion Var   0.181   0.160   0.121   0.114   0.073
Cumulative Var   0.181   0.340   0.461   0.575   0.648</code></pre>
</div>
</div>
</section>
<section id="comments-12" class="level2">
<h2 class="anchored" data-anchor-id="comments-12">Comments 1/2</h2>
<ul>
<li>On (new) 5 factors:</li>
<li>Factor 1 is health, education, arts: same as factor 1 before.</li>
<li>Factor 2 is housing, transportation, arts, recreation: as factor 2 before.</li>
<li>Factor 3 is economy.</li>
<li>Factor 4 is crime.</li>
<li>Factor 5 is climate and housing: like factor 3 before.</li>
</ul>
</section>
<section id="comments-22" class="level2">
<h2 class="anchored" data-anchor-id="comments-22">Comments 2/2</h2>
<ul>
<li>The two added factors include the two “missing” variables.</li>
<li>Is this now enough?</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>places<span class="fl">.5</span><span class="sc">$</span>PVAL</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   objective 
0.0009741394 </code></pre>
</div>
</div>
<ul>
<li>No.&nbsp;My guess is that the authors of Places Rated chose their 9 criteria to capture different aspects of what makes a city good or bad to live in, and so it was too much to hope that a small number of factors would come out of these.</li>
</ul>
</section>
<section id="a-bigger-example-bem-sex-role-inventory" class="level2">
<h2 class="anchored" data-anchor-id="a-bigger-example-bem-sex-role-inventory">A bigger example: BEM sex role inventory</h2>
<ul>
<li><p>369 women asked to rate themselves on 60 traits, like “self-reliant” or “shy”.</p></li>
<li><p>Rating 1 “never or almost never true of me” to 7 ``always or almost always true of me’’.</p></li>
<li><p>60 personality traits is a lot. Can we find a smaller number of factors that capture aspects of personality?</p></li>
<li><p>The whole BEM sex role inventory on next page.</p></li>
</ul>
</section>
<section id="the-whole-inventory" class="level2">
<h2 class="anchored" data-anchor-id="the-whole-inventory">The whole inventory</h2>
<p><img src="bem.png" class="img-fluid" width="450"></p>
</section>
<section id="some-of-the-data" class="level2">
<h2 class="anchored" data-anchor-id="some-of-the-data">Some of the data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>my_url <span class="ot">&lt;-</span> <span class="st">"http://ritsokiguess.site/datafiles/factor.txt"</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>bem <span class="ot">&lt;-</span> <span class="fu">read_tsv</span>(my_url)</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>bem</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 369 × 45
   subno helpful reliant defbel yielding cheerful indpt athlet   shy assert
   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
 1     1       7       7      5        5        7     7      7     1      7
 2     2       5       6      6        6        2     3      3     3      4
 3     3       7       6      4        4        5     5      2     3      4
 4     4       6       6      7        4        6     6      3     4      4
 5     5       6       6      7        4        7     7      7     2      7
 6     7       5       6      7        4        6     6      2     4      4
 7     8       6       4      6        6        6     3      1     3      3
 8     9       7       6      7        5        6     7      5     2      5
 9    10       7       6      6        4        4     5      2     2      5
10    11       7       4      7        4        7     5      2     1      5
# ℹ 359 more rows
# ℹ 35 more variables: strpers &lt;dbl&gt;, forceful &lt;dbl&gt;, affect &lt;dbl&gt;,
#   flatter &lt;dbl&gt;, loyal &lt;dbl&gt;, analyt &lt;dbl&gt;, feminine &lt;dbl&gt;, sympathy &lt;dbl&gt;,
#   moody &lt;dbl&gt;, sensitiv &lt;dbl&gt;, undstand &lt;dbl&gt;, compass &lt;dbl&gt;, leaderab &lt;dbl&gt;,
#   soothe &lt;dbl&gt;, risk &lt;dbl&gt;, decide &lt;dbl&gt;, selfsuff &lt;dbl&gt;, conscien &lt;dbl&gt;,
#   dominant &lt;dbl&gt;, masculin &lt;dbl&gt;, stand &lt;dbl&gt;, happy &lt;dbl&gt;, softspok &lt;dbl&gt;,
#   warm &lt;dbl&gt;, truthful &lt;dbl&gt;, tender &lt;dbl&gt;, gullible &lt;dbl&gt;, leadact &lt;dbl&gt;, …</code></pre>
</div>
</div>
</section>
<section id="principal-components-first" class="level2">
<h2 class="anchored" data-anchor-id="principal-components-first">Principal components first</h2>
<p>to decide on number of factors:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>bem.pc <span class="ot">&lt;-</span> bem <span class="sc">%&gt;%</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(<span class="sc">-</span>subno) <span class="sc">%&gt;%</span></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a><span class="fu">princomp</span>(<span class="at">cor =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="the-scree-plot" class="level2">
<h2 class="anchored" data-anchor-id="the-scree-plot">The scree plot</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>(g <span class="ot">&lt;-</span> <span class="fu">ggscreeplot</span>(bem.pc))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="factor_files/figure-html/genoa-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li>No obvious elbow.</li>
</ul>
</section>
<section id="zoom-in-to-search-for-elbow" class="level2">
<h2 class="anchored" data-anchor-id="zoom-in-to-search-for-elbow">Zoom in to search for elbow</h2>
<p>Possible elbows at 3 (2 factors) and 6 (5):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>g <span class="sc">+</span> <span class="fu">scale_x_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">8</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="factor_files/figure-html/bem-scree-two-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="but-is-2-really-good" class="level2">
<h2 class="anchored" data-anchor-id="but-is-2-really-good">but is 2 really good?</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(bem.pc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Importance of components:
                          Comp.1    Comp.2     Comp.3     Comp.4     Comp.5
Standard deviation     2.7444993 2.2405789 1.55049106 1.43886350 1.30318840
Proportion of Variance 0.1711881 0.1140953 0.05463688 0.04705291 0.03859773
Cumulative Proportion  0.1711881 0.2852834 0.33992029 0.38697320 0.42557093
                           Comp.6     Comp.7     Comp.8     Comp.9    Comp.10
Standard deviation     1.18837867 1.15919129 1.07838912 1.07120568 1.04901318
Proportion of Variance 0.03209645 0.03053919 0.02643007 0.02607913 0.02500974
Cumulative Proportion  0.45766738 0.48820657 0.51463664 0.54071577 0.56572551
                          Comp.11    Comp.12    Comp.13    Comp.14   Comp.15
Standard deviation     1.03848656 1.00152287 0.97753974 0.95697572 0.9287543
Proportion of Variance 0.02451033 0.02279655 0.02171782 0.02081369 0.0196042
Cumulative Proportion  0.59023584 0.61303238 0.63475020 0.65556390 0.6751681
                          Comp.16    Comp.17   Comp.18    Comp.19    Comp.20
Standard deviation     0.92262649 0.90585705 0.8788668 0.86757525 0.84269120
Proportion of Variance 0.01934636 0.01864948 0.0175547 0.01710652 0.01613928
Cumulative Proportion  0.69451445 0.71316392 0.7307186 0.74782514 0.76396443
                          Comp.21    Comp.22    Comp.23    Comp.24    Comp.25
Standard deviation     0.83124925 0.80564654 0.78975423 0.78100835 0.77852606
Proportion of Variance 0.01570398 0.01475151 0.01417527 0.01386305 0.01377506
Cumulative Proportion  0.77966841 0.79441992 0.80859519 0.82245823 0.83623330
                          Comp.26    Comp.27    Comp.28    Comp.29    Comp.30
Standard deviation     0.74969868 0.74137885 0.72343693 0.71457305 0.70358645
Proportion of Variance 0.01277382 0.01249188 0.01189457 0.01160488 0.01125077
Cumulative Proportion  0.84900712 0.86149899 0.87339356 0.88499844 0.89624921
                          Comp.31     Comp.32     Comp.33    Comp.34
Standard deviation     0.69022738 0.654861232 0.640339974 0.63179848
Proportion of Variance 0.01082759 0.009746437 0.009318984 0.00907203
Cumulative Proportion  0.90707680 0.916823235 0.926142219 0.93521425
                           Comp.35     Comp.36     Comp.37     Comp.38
Standard deviation     0.616621295 0.602404917 0.570025368 0.560881809
Proportion of Variance 0.008641405 0.008247538 0.007384748 0.007149736
Cumulative Proportion  0.943855654 0.952103192 0.959487940 0.966637677
                           Comp.39     Comp.40     Comp.41     Comp.42
Standard deviation     0.538149460 0.530277613 0.512370708 0.505662309
Proportion of Variance 0.006581928 0.006390781 0.005966449 0.005811236
Cumulative Proportion  0.973219605 0.979610386 0.985576834 0.991388070
                           Comp.43     Comp.44
Standard deviation     0.480413465 0.384873772
Proportion of Variance 0.005245389 0.003366541
Cumulative Proportion  0.996633459 1.000000000</code></pre>
</div>
</div>
</section>
<section id="comments-4" class="level2">
<h2 class="anchored" data-anchor-id="comments-4">Comments</h2>
<ul>
<li><p>Want overall fraction of variance explained (``cumulative proportion’’) to be reasonably high.</p></li>
<li><p>2 factors, 28.5%. Terrible!</p></li>
<li><p>Even 56% (10 factors) not that good!</p></li>
<li><p>Have to live with that.</p></li>
</ul>
</section>
<section id="biplot" class="level2">
<h2 class="anchored" data-anchor-id="biplot">Biplot</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggbiplot</span>(bem.pc, <span class="at">alpha =</span> <span class="fl">0.3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="factor_files/figure-html/bem-biplot-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="comments-5" class="level2">
<h2 class="anchored" data-anchor-id="comments-5">Comments</h2>
<ul>
<li><p>Ignore individuals for now.</p></li>
<li><p>Most variables point to 1 o’clock or 4 o’clock.</p></li>
<li><p>Suggests factor analysis with rotation will get interpretable factors (rotate to 12 o’clock and 3 o’clock, for example).</p></li>
<li><p>Try for 2-factor solution (rough interpretation, will be bad):</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>bem <span class="sc">%&gt;%</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(<span class="sc">-</span>subno) <span class="sc">%&gt;%</span></span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a><span class="fu">factanal</span>(<span class="at">factors =</span> <span class="dv">2</span>) <span class="ot">-&gt;</span> bem<span class="fl">.2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>Show output in pieces (just print <code>bem.2</code> to see all of it).</li>
</ul>
</section>
<section id="uniquenesses-sorted" class="level2">
<h2 class="anchored" data-anchor-id="uniquenesses-sorted">Uniquenesses, sorted</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(bem<span class="fl">.2</span><span class="sc">$</span>uniquenesses)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> leaderab   leadact      warm    tender  dominant    gentle 
0.4091894 0.4166153 0.4764762 0.4928919 0.4942909 0.5064551 
 forceful   strpers   compass     stand  undstand    assert 
0.5631857 0.5679398 0.5937073 0.6024001 0.6194392 0.6329347 
   soothe    affect    decide  selfsuff  sympathy     indpt 
0.6596103 0.6616625 0.6938578 0.7210246 0.7231450 0.7282742 
  helpful    defbel      risk   reliant   individ   compete 
0.7598223 0.7748448 0.7789761 0.7808058 0.7941998 0.7942910 
 conscien     happy  sensitiv     loyal  ambitiou       shy 
0.7974820 0.8008966 0.8018851 0.8035264 0.8101599 0.8239496 
 softspok  cheerful  masculin  yielding  feminine  truthful 
0.8339058 0.8394916 0.8453368 0.8688473 0.8829927 0.8889983 
  lovchil    analyt    athlet   flatter  gullible     moody 
0.8924392 0.8968744 0.9229702 0.9409500 0.9583435 0.9730607 
 childlik  foullang 
0.9800360 0.9821662 </code></pre>
</div>
</div>
</section>
<section id="comments-6" class="level2">
<h2 class="anchored" data-anchor-id="comments-6">Comments</h2>
<ul>
<li><p>Mostly high or very high (bad).</p></li>
<li><p>Some smaller, eg.: Leadership ability (0.409), Acts like leader (0.417), Warm (0.476), Tender (0.493).</p></li>
<li><p>Smaller uniquenesses captured by one of our two factors.</p></li>
<li><p>Larger uniquenesses are not: need more factors to capture them.</p></li>
</ul>
</section>
<section id="factor-loadings-some" class="level2">
<h2 class="anchored" data-anchor-id="factor-loadings-some">Factor loadings, some</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>bem<span class="fl">.2</span><span class="sc">$</span>loadings</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Loadings:
         Factor1 Factor2
helpful   0.314   0.376 
reliant   0.453   0.117 
defbel    0.434   0.193 
yielding -0.131   0.338 
cheerful  0.152   0.371 
indpt     0.521         
athlet    0.267         
shy      -0.414         
assert    0.605         
strpers   0.657         
forceful  0.649  -0.126 
affect    0.178   0.554 
flatter           0.223 
loyal     0.151   0.417 
analyt    0.295   0.127 
feminine  0.113   0.323 
sympathy          0.526 
moody            -0.162 
sensitiv  0.135   0.424 
undstand          0.610 
compass   0.114   0.627 
leaderab  0.765         
soothe            0.580 
risk      0.442   0.161 
decide    0.542   0.113 
selfsuff  0.511   0.134 
conscien  0.328   0.308 
dominant  0.668  -0.245 
masculin  0.276  -0.280 
stand     0.607   0.172 
happy     0.119   0.430 
softspok -0.230   0.336 
warm              0.719 
truthful  0.109   0.315 
tender            0.710 
gullible -0.153   0.135 
leadact   0.763         
childlik -0.101         
individ   0.445         
foullang          0.133 
lovchil           0.327 
compete   0.450         
ambitiou  0.414   0.137 
gentle            0.702 

               Factor1 Factor2
SS loadings      6.083   5.127
Proportion Var   0.138   0.117
Cumulative Var   0.138   0.255</code></pre>
</div>
</div>
</section>
<section id="making-a-data-frame" class="level2">
<h2 class="anchored" data-anchor-id="making-a-data-frame">Making a data frame</h2>
<p>There are too many to read easily, so make a data frame. A bit tricky:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>bem<span class="fl">.2</span><span class="sc">$</span>loadings <span class="sc">%&gt;%</span> </span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a><span class="fu">unclass</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a><span class="fu">as_tibble</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a><span class="fu">mutate</span>(<span class="at">trait =</span> <span class="fu">rownames</span>(bem<span class="fl">.2</span><span class="sc">$</span>loadings)) <span class="ot">-&gt;</span> loadings</span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a>loadings <span class="sc">%&gt;%</span> <span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 3
  Factor1  Factor2 trait   
    &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;   
1   0.314  0.376   helpful 
2   0.453  0.117   reliant 
3   0.434  0.193   defbel  
4  -0.131  0.338   yielding
5   0.152  0.371   cheerful
6   0.521  0.00587 indpt   
7   0.267  0.0755  athlet  
8  -0.414 -0.0654  shy     </code></pre>
</div>
</div>
</section>
<section id="pick-out-the-big-ones-on-factor-1" class="level2">
<h2 class="anchored" data-anchor-id="pick-out-the-big-ones-on-factor-1">Pick out the big ones on factor 1</h2>
<p>Arbitrarily defining <span class="math inline">\(&gt;0.4\)</span> or <span class="math inline">\(&lt;-0.4\)</span> as “big”:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>loadings <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">abs</span>(Factor1) <span class="sc">&gt;</span> <span class="fl">0.4</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 17 × 3
   Factor1  Factor2 trait   
     &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;   
 1   0.453  0.117   reliant 
 2   0.434  0.193   defbel  
 3   0.521  0.00587 indpt   
 4  -0.414 -0.0654  shy     
 5   0.605  0.0330  assert  
 6   0.657  0.0208  strpers 
 7   0.649 -0.126   forceful
 8   0.765  0.0695  leaderab
 9   0.442  0.161   risk    
10   0.542  0.113   decide  
11   0.511  0.134   selfsuff
12   0.668 -0.245   dominant
13   0.607  0.172   stand   
14   0.763 -0.0407  leadact 
15   0.445  0.0891  individ 
16   0.450  0.0532  compete 
17   0.414  0.137   ambitiou</code></pre>
</div>
</div>
</section>
<section id="factor-2-the-big-ones" class="level2">
<h2 class="anchored" data-anchor-id="factor-2-the-big-ones">Factor 2, the big ones</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>loadings <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">abs</span>(Factor2) <span class="sc">&gt;</span> <span class="fl">0.4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 11 × 3
   Factor1 Factor2 trait   
     &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;   
 1  0.178    0.554 affect  
 2  0.151    0.417 loyal   
 3  0.0230   0.526 sympathy
 4  0.135    0.424 sensitiv
 5  0.0911   0.610 undstand
 6  0.114    0.627 compass 
 7  0.0606   0.580 soothe  
 8  0.119    0.430 happy   
 9  0.0796   0.719 warm    
10  0.0511   0.710 tender  
11 -0.0187   0.702 gentle  </code></pre>
</div>
</div>
</section>
<section id="plotting-the-two-factors" class="level2">
<h2 class="anchored" data-anchor-id="plotting-the-two-factors">Plotting the two factors</h2>
<ul>
<li><p>A bi-plot, this time with the variables reduced in size. Looking for unusual individuals.</p></li>
<li><p>Have to run <code>factanal</code> again to get factor scores for plotting.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>bem <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>subno) <span class="sc">%&gt;%</span> </span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a><span class="fu">factanal</span>(<span class="at">factors =</span> <span class="dv">2</span>, <span class="at">scores =</span> <span class="st">"r"</span>) <span class="ot">-&gt;</span> bem<span class="fl">.2</span>a</span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a><span class="fu">biplot</span>(bem<span class="fl">.2</span>a<span class="sc">$</span>scores, bem<span class="fl">.2</span>a<span class="sc">$</span>loadings, <span class="at">cex =</span> <span class="fu">c</span>(<span class="fl">0.5</span>, <span class="fl">0.5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>Numbers on plot are row numbers of <code>bem</code> data frame.</li>
</ul>
</section>
<section id="the-awful-biplot" class="level2">
<h2 class="anchored" data-anchor-id="the-awful-biplot">The (awful) biplot</h2>
<div class="cell">
<div class="cell-output-display">
<p><img src="factor_files/figure-html/biplot-two-ag-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="comments-7" class="level2">
<h2 class="anchored" data-anchor-id="comments-7">Comments</h2>
<ul>
<li><p>Variables mostly up (“feminine”) and right (“masculine”), accomplished by rotation.</p></li>
<li><p>Some unusual individuals: 311, 214 (low on factor 2), 366 (high on factor 2), 359, 258 (low on factor 1), 230 (high on factor 1).</p></li>
</ul>
</section>
<section id="individual-366" class="level2">
<h2 class="anchored" data-anchor-id="individual-366">Individual 366</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>bem <span class="sc">%&gt;%</span> <span class="fu">slice</span>(<span class="dv">366</span>) <span class="sc">%&gt;%</span> <span class="fu">glimpse</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 1
Columns: 45
$ subno    &lt;dbl&gt; 755
$ helpful  &lt;dbl&gt; 7
$ reliant  &lt;dbl&gt; 7
$ defbel   &lt;dbl&gt; 5
$ yielding &lt;dbl&gt; 7
$ cheerful &lt;dbl&gt; 7
$ indpt    &lt;dbl&gt; 7
$ athlet   &lt;dbl&gt; 7
$ shy      &lt;dbl&gt; 2
$ assert   &lt;dbl&gt; 1
$ strpers  &lt;dbl&gt; 3
$ forceful &lt;dbl&gt; 1
$ affect   &lt;dbl&gt; 7
$ flatter  &lt;dbl&gt; 9
$ loyal    &lt;dbl&gt; 7
$ analyt   &lt;dbl&gt; 7
$ feminine &lt;dbl&gt; 7
$ sympathy &lt;dbl&gt; 7
$ moody    &lt;dbl&gt; 1
$ sensitiv &lt;dbl&gt; 7
$ undstand &lt;dbl&gt; 7
$ compass  &lt;dbl&gt; 6
$ leaderab &lt;dbl&gt; 3
$ soothe   &lt;dbl&gt; 7
$ risk     &lt;dbl&gt; 7
$ decide   &lt;dbl&gt; 7
$ selfsuff &lt;dbl&gt; 7
$ conscien &lt;dbl&gt; 7
$ dominant &lt;dbl&gt; 1
$ masculin &lt;dbl&gt; 1
$ stand    &lt;dbl&gt; 7
$ happy    &lt;dbl&gt; 7
$ softspok &lt;dbl&gt; 7
$ warm     &lt;dbl&gt; 7
$ truthful &lt;dbl&gt; 7
$ tender   &lt;dbl&gt; 7
$ gullible &lt;dbl&gt; 1
$ leadact  &lt;dbl&gt; 2
$ childlik &lt;dbl&gt; 1
$ individ  &lt;dbl&gt; 5
$ foullang &lt;dbl&gt; 7
$ lovchil  &lt;dbl&gt; 7
$ compete  &lt;dbl&gt; 7
$ ambitiou &lt;dbl&gt; 7
$ gentle   &lt;dbl&gt; 7</code></pre>
</div>
</div>
</section>
<section id="comments-8" class="level2">
<h2 class="anchored" data-anchor-id="comments-8">Comments</h2>
<ul>
<li><p>Individual 366 high on factor 2, but hard to see which traits should have high scores (unless we remember).</p></li>
<li><p>Idea 1: use percentile ranks as before.</p></li>
<li><p>Idea 2: Rating scale is easy to interpret. So <em>tidy</em> original data frame to make easier to look things up.</p></li>
</ul>
</section>
<section id="tidying-original-data" class="level2">
<h2 class="anchored" data-anchor-id="tidying-original-data">Tidying original data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>bem <span class="sc">%&gt;%</span></span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ungroup</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a><span class="fu">mutate</span>(<span class="at">row =</span> <span class="fu">row_number</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a><span class="fu">pivot_longer</span>(<span class="fu">c</span>(<span class="sc">-</span>subno, <span class="sc">-</span>row), <span class="at">names_to=</span><span class="st">"trait"</span>, </span>
<span id="cb81-5"><a href="#cb81-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">values_to=</span><span class="st">"score"</span>) <span class="ot">-&gt;</span> bem_tidy</span>
<span id="cb81-6"><a href="#cb81-6" aria-hidden="true" tabindex="-1"></a>bem_tidy</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 16,236 × 4
   subno   row trait    score
   &lt;dbl&gt; &lt;int&gt; &lt;chr&gt;    &lt;dbl&gt;
 1     1     1 helpful      7
 2     1     1 reliant      7
 3     1     1 defbel       5
 4     1     1 yielding     5
 5     1     1 cheerful     7
 6     1     1 indpt        7
 7     1     1 athlet       7
 8     1     1 shy          1
 9     1     1 assert       7
10     1     1 strpers      7
# ℹ 16,226 more rows</code></pre>
</div>
</div>
</section>
<section id="recall-data-frame-of-loadings" class="level2">
<h2 class="anchored" data-anchor-id="recall-data-frame-of-loadings">Recall data frame of loadings</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>loadings <span class="sc">%&gt;%</span> <span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 3
   Factor1  Factor2 trait   
     &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;   
 1   0.314  0.376   helpful 
 2   0.453  0.117   reliant 
 3   0.434  0.193   defbel  
 4  -0.131  0.338   yielding
 5   0.152  0.371   cheerful
 6   0.521  0.00587 indpt   
 7   0.267  0.0755  athlet  
 8  -0.414 -0.0654  shy     
 9   0.605  0.0330  assert  
10   0.657  0.0208  strpers </code></pre>
</div>
</div>
<p>Want to add the factor scores for each trait to our tidy data frame <code>bem_tidy</code>. This is a left-join (over), matching on the column <code>trait</code> that is in both data frames (thus, the default):</p>
</section>
<section id="looking-up-loadings" class="level2">
<h2 class="anchored" data-anchor-id="looking-up-loadings">Looking up loadings</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>bem_tidy <span class="sc">%&gt;%</span> <span class="fu">left_join</span>(loadings) <span class="ot">-&gt;</span> bem_tidy</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Joining with `by = join_by(trait)`</code></pre>
</div>
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>bem_tidy <span class="sc">%&gt;%</span> <span class="fu">sample_n</span>(<span class="dv">12</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 6
   subno   row trait    score  Factor1 Factor2
   &lt;dbl&gt; &lt;int&gt; &lt;chr&gt;    &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;
 1    32    22 forceful     4  0.649   -0.126 
 2    28    18 conscien     7  0.328    0.308 
 3    85    51 masculin     1  0.276   -0.280 
 4    99    61 flatter      4  0.0964   0.223 
 5   403   229 individ      6  0.445    0.0891
 6   448   252 gentle       6 -0.0187   0.702 
 7   183   110 foullang     1 -0.00493  0.133 
 8   122    77 tender       6  0.0511   0.710 
 9   302   176 softspok     5 -0.230    0.336 
10   588   344 risk         1  0.442    0.161 
11   514   297 loyal        7  0.151    0.417 
12    98    60 individ      5  0.445    0.0891</code></pre>
</div>
</div>
</section>
<section id="individual-366-high-on-factor-2" class="level2">
<h2 class="anchored" data-anchor-id="individual-366-high-on-factor-2">Individual 366, high on Factor 2</h2>
<p>So now pick out the rows of the tidy data frame that belong to individual 366 (<code>row=366</code>) and for which the <code>Factor2</code> score exceeds 0.4 in absolute value (our “big” from before):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>bem_tidy <span class="sc">%&gt;%</span> <span class="fu">filter</span>(row <span class="sc">==</span> <span class="dv">366</span>, <span class="fu">abs</span>(Factor2) <span class="sc">&gt;</span> <span class="fl">0.4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 11 × 6
   subno   row trait    score Factor1 Factor2
   &lt;dbl&gt; &lt;int&gt; &lt;chr&gt;    &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
 1   755   366 affect       7  0.178    0.554
 2   755   366 loyal        7  0.151    0.417
 3   755   366 sympathy     7  0.0230   0.526
 4   755   366 sensitiv     7  0.135    0.424
 5   755   366 undstand     7  0.0911   0.610
 6   755   366 compass      6  0.114    0.627
 7   755   366 soothe       7  0.0606   0.580
 8   755   366 happy        7  0.119    0.430
 9   755   366 warm         7  0.0796   0.719
10   755   366 tender       7  0.0511   0.710
11   755   366 gentle       7 -0.0187   0.702</code></pre>
</div>
</div>
<p>As expected, high scorer on these.</p>
</section>
<section id="several-individuals" class="level2">
<h2 class="anchored" data-anchor-id="several-individuals">Several individuals</h2>
<p>Rows 311 and 214 were <em>low</em> on Factor 2, so their scores should be low. Can we do them all at once?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a>bem_tidy <span class="sc">%&gt;%</span> <span class="fu">filter</span>(</span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a>row <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">366</span>, <span class="dv">311</span>, <span class="dv">214</span>),</span>
<span id="cb91-3"><a href="#cb91-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abs</span>(Factor2) <span class="sc">&gt;</span> <span class="fl">0.4</span></span>
<span id="cb91-4"><a href="#cb91-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 33 × 6
   subno   row trait    score Factor1 Factor2
   &lt;dbl&gt; &lt;int&gt; &lt;chr&gt;    &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
 1   369   214 affect       1  0.178    0.554
 2   369   214 loyal        7  0.151    0.417
 3   369   214 sympathy     4  0.0230   0.526
 4   369   214 sensitiv     7  0.135    0.424
 5   369   214 undstand     5  0.0911   0.610
 6   369   214 compass      5  0.114    0.627
 7   369   214 soothe       3  0.0606   0.580
 8   369   214 happy        4  0.119    0.430
 9   369   214 warm         1  0.0796   0.719
10   369   214 tender       3  0.0511   0.710
# ℹ 23 more rows</code></pre>
</div>
</div>
<p>Can we display each individual in own column?</p>
</section>
<section id="individual-by-column" class="level2">
<h2 class="anchored" data-anchor-id="individual-by-column">Individual by column</h2>
<p>Un-<code>tidy</code>, that is, <code>pivot_wider</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a>bem_tidy <span class="sc">%&gt;%</span></span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(</span>
<span id="cb93-3"><a href="#cb93-3" aria-hidden="true" tabindex="-1"></a>  row <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">366</span>, <span class="dv">311</span>, <span class="dv">214</span>),</span>
<span id="cb93-4"><a href="#cb93-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">abs</span>(Factor2) <span class="sc">&gt;</span> <span class="fl">0.4</span></span>
<span id="cb93-5"><a href="#cb93-5" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb93-6"><a href="#cb93-6" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(<span class="sc">-</span>subno, <span class="sc">-</span>Factor1, <span class="sc">-</span>Factor2) <span class="sc">%&gt;%</span></span>
<span id="cb93-7"><a href="#cb93-7" aria-hidden="true" tabindex="-1"></a><span class="fu">pivot_wider</span>(<span class="at">names_from=</span>row, <span class="at">values_from=</span>score)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 11 × 4
   trait    `214` `311` `366`
   &lt;chr&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
 1 affect       1     5     7
 2 loyal        7     4     7
 3 sympathy     4     4     7
 4 sensitiv     7     4     7
 5 undstand     5     3     7
 6 compass      5     4     6
 7 soothe       3     4     7
 8 happy        4     3     7
 9 warm         1     3     7
10 tender       3     4     7
11 gentle       2     3     7</code></pre>
</div>
</div>
<p>366 high, 311 middling, 214 (sometimes) low.</p>
</section>
<section id="individuals-230-258-359" class="level2">
<h2 class="anchored" data-anchor-id="individuals-230-258-359">Individuals 230, 258, 359</h2>
<p>These were high, low, low on factor 1. Adapt code:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a>bem_tidy <span class="sc">%&gt;%</span></span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(row <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">359</span>, <span class="dv">258</span>, <span class="dv">230</span>), <span class="fu">abs</span>(Factor1) <span class="sc">&gt;</span> <span class="fl">0.4</span>) <span class="sc">%&gt;%</span></span>
<span id="cb95-3"><a href="#cb95-3" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(<span class="sc">-</span>subno, <span class="sc">-</span>Factor1, <span class="sc">-</span>Factor2) <span class="sc">%&gt;%</span></span>
<span id="cb95-4"><a href="#cb95-4" aria-hidden="true" tabindex="-1"></a><span class="fu">pivot_wider</span>(<span class="at">names_from=</span>row, <span class="at">values_from=</span>score)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 17 × 4
   trait    `230` `258` `359`
   &lt;chr&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
 1 reliant      7     4     1
 2 defbel       7     1     1
 3 indpt        7     7     1
 4 shy          2     7     5
 5 assert       7     3     1
 6 strpers      7     1     3
 7 forceful     7     1     1
 8 leaderab     7     1     1
 9 risk         7     5     7
10 decide       7     1     2
11 selfsuff     7     4     1
12 dominant     7     1     1
13 stand        7     1     6
14 leadact      7     1     1
15 individ      7     3     3
16 compete      6     2     1
17 ambitiou     7     2     4</code></pre>
</div>
</div>
</section>
<section id="is-2-factors-enough" class="level2">
<h2 class="anchored" data-anchor-id="is-2-factors-enough">Is 2 factors enough?</h2>
<p>Suspect not:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a>bem<span class="fl">.2</span><span class="sc">$</span>PVAL</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    objective 
1.458183e-150 </code></pre>
</div>
</div>
<p>2 factors resoundingly rejected. Need more. Have to go all the way to 15 factors to not reject:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a>bem <span class="sc">%&gt;%</span></span>
<span id="cb99-2"><a href="#cb99-2" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(<span class="sc">-</span>subno) <span class="sc">%&gt;%</span></span>
<span id="cb99-3"><a href="#cb99-3" aria-hidden="true" tabindex="-1"></a><span class="fu">factanal</span>(<span class="at">factors =</span> <span class="dv">15</span>) <span class="ot">-&gt;</span> bem<span class="fl">.15</span></span>
<span id="cb99-4"><a href="#cb99-4" aria-hidden="true" tabindex="-1"></a>bem<span class="fl">.15</span><span class="sc">$</span>PVAL</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>objective 
 0.132617 </code></pre>
</div>
</div>
<p>Even then, only just over 50% of variability explained.</p>
</section>
<section id="whats-important-in-15-factors" class="level2">
<h2 class="anchored" data-anchor-id="whats-important-in-15-factors">What’s important in 15 factors?</h2>
<ul>
<li><p>Let’s take a look at the important things in those 15 factors.</p></li>
<li><p>Get 15-factor loadings into a data frame, as before:</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a>bem<span class="fl">.15</span><span class="sc">$</span>loadings <span class="sc">%&gt;%</span> </span>
<span id="cb101-2"><a href="#cb101-2" aria-hidden="true" tabindex="-1"></a><span class="fu">unclass</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb101-3"><a href="#cb101-3" aria-hidden="true" tabindex="-1"></a><span class="fu">as_tibble</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb101-4"><a href="#cb101-4" aria-hidden="true" tabindex="-1"></a><span class="fu">mutate</span>(<span class="at">trait =</span> <span class="fu">rownames</span>(bem<span class="fl">.15</span><span class="sc">$</span>loadings)) <span class="ot">-&gt;</span> loadings</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>then show the highest few loadings on each factor.</li>
</ul>
</section>
<section id="factor-1-of-15" class="level2">
<h2 class="anchored" data-anchor-id="factor-1-of-15">Factor 1 (of 15)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a>loadings <span class="sc">%&gt;%</span></span>
<span id="cb102-2"><a href="#cb102-2" aria-hidden="true" tabindex="-1"></a><span class="fu">arrange</span>(<span class="fu">desc</span>(<span class="fu">abs</span>(Factor1))) <span class="sc">%&gt;%</span></span>
<span id="cb102-3"><a href="#cb102-3" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(Factor1, trait) <span class="sc">%&gt;%</span></span>
<span id="cb102-4"><a href="#cb102-4" aria-hidden="true" tabindex="-1"></a><span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 2
   Factor1 trait   
     &lt;dbl&gt; &lt;chr&gt;   
 1   0.813 compass 
 2   0.676 undstand
 3   0.661 sympathy
 4   0.641 sensitiv
 5   0.597 soothe  
 6   0.348 warm    
 7   0.280 gentle  
 8   0.279 tender  
 9   0.250 helpful 
10   0.234 conscien</code></pre>
</div>
</div>
<p>Compassionate, understanding, sympathetic, soothing: thoughtful of others.</p>
</section>
<section id="factor-2" class="level2">
<h2 class="anchored" data-anchor-id="factor-2">Factor 2</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a>loadings <span class="sc">%&gt;%</span></span>
<span id="cb104-2"><a href="#cb104-2" aria-hidden="true" tabindex="-1"></a><span class="fu">arrange</span>(<span class="fu">desc</span>(<span class="fu">abs</span>(Factor2))) <span class="sc">%&gt;%</span></span>
<span id="cb104-3"><a href="#cb104-3" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(Factor2, trait) <span class="sc">%&gt;%</span></span>
<span id="cb104-4"><a href="#cb104-4" aria-hidden="true" tabindex="-1"></a><span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 2
   Factor2 trait   
     &lt;dbl&gt; &lt;chr&gt;   
 1   0.762 strpers 
 2   0.716 forceful
 3   0.698 assert  
 4   0.504 dominant
 5   0.393 leaderab
 6   0.367 stand   
 7   0.351 leadact 
 8  -0.313 softspok
 9  -0.287 shy     
10   0.260 analyt  </code></pre>
</div>
</div>
<p>Strong personality, forceful, assertive, dominant: getting ahead.</p>
</section>
<section id="factor-3" class="level2">
<h2 class="anchored" data-anchor-id="factor-3">Factor 3</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a>loadings <span class="sc">%&gt;%</span></span>
<span id="cb106-2"><a href="#cb106-2" aria-hidden="true" tabindex="-1"></a><span class="fu">arrange</span>(<span class="fu">desc</span>(<span class="fu">abs</span>(Factor3))) <span class="sc">%&gt;%</span></span>
<span id="cb106-3"><a href="#cb106-3" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(Factor3, trait) <span class="sc">%&gt;%</span></span>
<span id="cb106-4"><a href="#cb106-4" aria-hidden="true" tabindex="-1"></a><span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 2
   Factor3 trait   
     &lt;dbl&gt; &lt;chr&gt;   
 1   0.670 reliant 
 2   0.648 selfsuff
 3   0.620 indpt   
 4   0.390 helpful 
 5  -0.339 gullible
 6   0.333 individ 
 7   0.332 decide  
 8   0.329 conscien
 9   0.288 leaderab
10   0.280 defbel  </code></pre>
</div>
</div>
<p>Self-reliant, self-sufficient, independent: going it alone.</p>
</section>
<section id="factor-4" class="level2">
<h2 class="anchored" data-anchor-id="factor-4">Factor 4</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a>loadings <span class="sc">%&gt;%</span></span>
<span id="cb108-2"><a href="#cb108-2" aria-hidden="true" tabindex="-1"></a><span class="fu">arrange</span>(<span class="fu">desc</span>(<span class="fu">abs</span>(Factor4))) <span class="sc">%&gt;%</span></span>
<span id="cb108-3"><a href="#cb108-3" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(Factor4, trait) <span class="sc">%&gt;%</span></span>
<span id="cb108-4"><a href="#cb108-4" aria-hidden="true" tabindex="-1"></a><span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 2
   Factor4 trait   
     &lt;dbl&gt; &lt;chr&gt;   
 1   0.696 gentle  
 2   0.692 tender  
 3   0.599 warm    
 4   0.447 affect  
 5   0.394 softspok
 6   0.278 lovchil 
 7   0.244 undstand
 8   0.244 happy   
 9   0.213 loyal   
10   0.202 soothe  </code></pre>
</div>
</div>
<p>Gentle, tender, warm (affectionate): caring for others.</p>
</section>
<section id="factor-5" class="level2">
<h2 class="anchored" data-anchor-id="factor-5">Factor 5</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a>loadings <span class="sc">%&gt;%</span></span>
<span id="cb110-2"><a href="#cb110-2" aria-hidden="true" tabindex="-1"></a><span class="fu">arrange</span>(<span class="fu">desc</span>(<span class="fu">abs</span>(Factor5))) <span class="sc">%&gt;%</span></span>
<span id="cb110-3"><a href="#cb110-3" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(Factor5, trait) <span class="sc">%&gt;%</span></span>
<span id="cb110-4"><a href="#cb110-4" aria-hidden="true" tabindex="-1"></a><span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 2
   Factor5 trait   
     &lt;dbl&gt; &lt;chr&gt;   
 1   0.696 compete 
 2   0.674 ambitiou
 3   0.345 risk    
 4   0.342 individ 
 5   0.281 athlet  
 6   0.270 leaderab
 7   0.245 decide  
 8   0.206 dominant
 9   0.193 leadact 
10   0.185 strpers </code></pre>
</div>
</div>
<p>Ambitious, competitive (with a bit of risk-taking and individualism): Being the best.</p>
</section>
<section id="factor-6" class="level2">
<h2 class="anchored" data-anchor-id="factor-6">Factor 6</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb112"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a>loadings <span class="sc">%&gt;%</span></span>
<span id="cb112-2"><a href="#cb112-2" aria-hidden="true" tabindex="-1"></a><span class="fu">arrange</span>(<span class="fu">desc</span>(<span class="fu">abs</span>(Factor6))) <span class="sc">%&gt;%</span></span>
<span id="cb112-3"><a href="#cb112-3" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(Factor6, trait) <span class="sc">%&gt;%</span></span>
<span id="cb112-4"><a href="#cb112-4" aria-hidden="true" tabindex="-1"></a><span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 2
   Factor6 trait   
     &lt;dbl&gt; &lt;chr&gt;   
 1   0.868 leadact 
 2   0.608 leaderab
 3   0.338 dominant
 4   0.201 forceful
 5  -0.192 shy     
 6   0.179 risk    
 7   0.170 masculin
 8   0.164 decide  
 9   0.159 compete 
10   0.147 athlet  </code></pre>
</div>
</div>
<p>Acts like a leader, leadership ability (with a bit of Dominant): Taking charge.</p>
</section>
<section id="factor-7" class="level2">
<h2 class="anchored" data-anchor-id="factor-7">Factor 7</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a>loadings <span class="sc">%&gt;%</span></span>
<span id="cb114-2"><a href="#cb114-2" aria-hidden="true" tabindex="-1"></a><span class="fu">arrange</span>(<span class="fu">desc</span>(<span class="fu">abs</span>(Factor7))) <span class="sc">%&gt;%</span></span>
<span id="cb114-3"><a href="#cb114-3" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(Factor7, trait) <span class="sc">%&gt;%</span></span>
<span id="cb114-4"><a href="#cb114-4" aria-hidden="true" tabindex="-1"></a><span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 2
   Factor7 trait   
     &lt;dbl&gt; &lt;chr&gt;   
 1   0.670 happy   
 2   0.667 cheerful
 3  -0.522 moody   
 4   0.219 athlet  
 5   0.213 warm    
 6   0.172 gentle  
 7  -0.164 masculin
 8   0.160 reliant 
 9   0.147 yielding
10   0.141 lovchil </code></pre>
</div>
</div>
<p>Happy and cheerful.</p>
</section>
<section id="factor-8" class="level2">
<h2 class="anchored" data-anchor-id="factor-8">Factor 8</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb116"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a>loadings <span class="sc">%&gt;%</span></span>
<span id="cb116-2"><a href="#cb116-2" aria-hidden="true" tabindex="-1"></a><span class="fu">arrange</span>(<span class="fu">desc</span>(<span class="fu">abs</span>(Factor8))) <span class="sc">%&gt;%</span></span>
<span id="cb116-3"><a href="#cb116-3" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(Factor8, trait) <span class="sc">%&gt;%</span></span>
<span id="cb116-4"><a href="#cb116-4" aria-hidden="true" tabindex="-1"></a><span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 2
   Factor8 trait   
     &lt;dbl&gt; &lt;chr&gt;   
 1   0.630 affect  
 2   0.516 flatter 
 3  -0.251 softspok
 4   0.221 warm    
 5   0.188 tender  
 6   0.185 strpers 
 7  -0.180 shy     
 8   0.180 compete 
 9   0.166 loyal   
10   0.155 helpful </code></pre>
</div>
</div>
<p>Affectionate, flattering: Making others feel good.</p>
</section>
<section id="factor-9" class="level2">
<h2 class="anchored" data-anchor-id="factor-9">Factor 9</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb118"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb118-1"><a href="#cb118-1" aria-hidden="true" tabindex="-1"></a>loadings <span class="sc">%&gt;%</span></span>
<span id="cb118-2"><a href="#cb118-2" aria-hidden="true" tabindex="-1"></a><span class="fu">arrange</span>(<span class="fu">desc</span>(<span class="fu">abs</span>(Factor9))) <span class="sc">%&gt;%</span></span>
<span id="cb118-3"><a href="#cb118-3" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(Factor9, trait) <span class="sc">%&gt;%</span></span>
<span id="cb118-4"><a href="#cb118-4" aria-hidden="true" tabindex="-1"></a><span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 2
   Factor9 trait   
     &lt;dbl&gt; &lt;chr&gt;   
 1   0.863 stand   
 2   0.340 defbel  
 3   0.245 individ 
 4   0.194 risk    
 5  -0.172 shy     
 6   0.171 decide  
 7   0.120 assert  
 8   0.116 conscien
 9   0.112 analyt  
10  -0.112 gullible</code></pre>
</div>
</div>
<p>Taking a stand.</p>
</section>
<section id="factor-10" class="level2">
<h2 class="anchored" data-anchor-id="factor-10">Factor 10</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb120"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb120-1"><a href="#cb120-1" aria-hidden="true" tabindex="-1"></a>loadings <span class="sc">%&gt;%</span></span>
<span id="cb120-2"><a href="#cb120-2" aria-hidden="true" tabindex="-1"></a><span class="fu">arrange</span>(<span class="fu">desc</span>(<span class="fu">abs</span>(Factor10))) <span class="sc">%&gt;%</span></span>
<span id="cb120-3"><a href="#cb120-3" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(Factor10, trait) <span class="sc">%&gt;%</span></span>
<span id="cb120-4"><a href="#cb120-4" aria-hidden="true" tabindex="-1"></a><span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 2
   Factor10 trait   
      &lt;dbl&gt; &lt;chr&gt;   
 1   0.808  feminine
 2  -0.264  masculin
 3   0.245  softspok
 4   0.232  conscien
 5   0.202  selfsuff
 6   0.176  yielding
 7   0.141  gentle  
 8   0.113  flatter 
 9   0.109  decide  
10  -0.0941 lovchil </code></pre>
</div>
</div>
<p>Feminine. (A little bit of not-masculine!)</p>
</section>
<section id="factor-11" class="level2">
<h2 class="anchored" data-anchor-id="factor-11">Factor 11</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb122"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb122-1"><a href="#cb122-1" aria-hidden="true" tabindex="-1"></a>loadings <span class="sc">%&gt;%</span></span>
<span id="cb122-2"><a href="#cb122-2" aria-hidden="true" tabindex="-1"></a><span class="fu">arrange</span>(<span class="fu">desc</span>(<span class="fu">abs</span>(Factor11))) <span class="sc">%&gt;%</span></span>
<span id="cb122-3"><a href="#cb122-3" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(Factor11, trait) <span class="sc">%&gt;%</span></span>
<span id="cb122-4"><a href="#cb122-4" aria-hidden="true" tabindex="-1"></a><span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 2
   Factor11 trait   
      &lt;dbl&gt; &lt;chr&gt;   
 1   0.916  loyal   
 2   0.189  affect  
 3   0.159  truthful
 4   0.125  helpful 
 5   0.104  analyt  
 6   0.101  tender  
 7   0.0972 lovchil 
 8   0.0964 gullible
 9   0.0935 cheerful
10   0.0821 conscien</code></pre>
</div>
</div>
<p>Loyal.</p>
</section>
<section id="factor-12" class="level2">
<h2 class="anchored" data-anchor-id="factor-12">Factor 12</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb124"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb124-1"><a href="#cb124-1" aria-hidden="true" tabindex="-1"></a>loadings <span class="sc">%&gt;%</span></span>
<span id="cb124-2"><a href="#cb124-2" aria-hidden="true" tabindex="-1"></a><span class="fu">arrange</span>(<span class="fu">desc</span>(<span class="fu">abs</span>(Factor12))) <span class="sc">%&gt;%</span></span>
<span id="cb124-3"><a href="#cb124-3" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(Factor12, trait) <span class="sc">%&gt;%</span></span>
<span id="cb124-4"><a href="#cb124-4" aria-hidden="true" tabindex="-1"></a><span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 2
   Factor12 trait   
      &lt;dbl&gt; &lt;chr&gt;   
 1    0.611 childlik
 2   -0.285 selfsuff
 3   -0.279 conscien
 4    0.259 moody   
 5    0.201 shy     
 6   -0.167 decide  
 7    0.154 masculin
 8    0.146 dominant
 9    0.138 compass 
10   -0.130 leaderab</code></pre>
</div>
</div>
<p>Childlike. (With a bit of moody, shy, not-self-sufficient, not-conscientious.)</p>
</section>
<section id="factor-13" class="level2">
<h2 class="anchored" data-anchor-id="factor-13">Factor 13</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb126"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb126-1"><a href="#cb126-1" aria-hidden="true" tabindex="-1"></a>loadings <span class="sc">%&gt;%</span></span>
<span id="cb126-2"><a href="#cb126-2" aria-hidden="true" tabindex="-1"></a><span class="fu">arrange</span>(<span class="fu">desc</span>(<span class="fu">abs</span>(Factor13))) <span class="sc">%&gt;%</span></span>
<span id="cb126-3"><a href="#cb126-3" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(Factor13, trait) <span class="sc">%&gt;%</span></span>
<span id="cb126-4"><a href="#cb126-4" aria-hidden="true" tabindex="-1"></a><span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 2
   Factor13 trait   
      &lt;dbl&gt; &lt;chr&gt;   
 1    0.573 truthful
 2   -0.278 gullible
 3    0.263 happy   
 4    0.189 warm    
 5   -0.167 shy     
 6    0.165 loyal   
 7   -0.144 yielding
 8   -0.130 assert  
 9    0.114 defbel  
10   -0.111 lovchil </code></pre>
</div>
</div>
<p>Truthful. (With a bit of happy and not-gullible.)</p>
</section>
<section id="factor-14" class="level2">
<h2 class="anchored" data-anchor-id="factor-14">Factor 14</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb128"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb128-1"><a href="#cb128-1" aria-hidden="true" tabindex="-1"></a>loadings <span class="sc">%&gt;%</span></span>
<span id="cb128-2"><a href="#cb128-2" aria-hidden="true" tabindex="-1"></a><span class="fu">arrange</span>(<span class="fu">desc</span>(<span class="fu">abs</span>(Factor14))) <span class="sc">%&gt;%</span></span>
<span id="cb128-3"><a href="#cb128-3" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(Factor14, trait) <span class="sc">%&gt;%</span></span>
<span id="cb128-4"><a href="#cb128-4" aria-hidden="true" tabindex="-1"></a><span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 2
   Factor14 trait   
      &lt;dbl&gt; &lt;chr&gt;   
 1    0.443 decide  
 2    0.237 selfsuff
 3    0.195 forceful
 4   -0.186 softspok
 5    0.160 risk    
 6   -0.148 strpers 
 7    0.146 dominant
 8    0.128 happy   
 9    0.115 compass 
10    0.105 masculin</code></pre>
</div>
</div>
<p>Decisive. (With a bit of self-sufficient and not-soft-spoken.)</p>
</section>
<section id="factor-15" class="level2">
<h2 class="anchored" data-anchor-id="factor-15">Factor 15</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb130"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb130-1"><a href="#cb130-1" aria-hidden="true" tabindex="-1"></a>loadings <span class="sc">%&gt;%</span></span>
<span id="cb130-2"><a href="#cb130-2" aria-hidden="true" tabindex="-1"></a><span class="fu">arrange</span>(<span class="fu">desc</span>(<span class="fu">abs</span>(Factor15))) <span class="sc">%&gt;%</span></span>
<span id="cb130-3"><a href="#cb130-3" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(Factor15, trait) <span class="sc">%&gt;%</span></span>
<span id="cb130-4"><a href="#cb130-4" aria-hidden="true" tabindex="-1"></a><span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 2
   Factor15 trait   
      &lt;dbl&gt; &lt;chr&gt;   
 1   -0.324 compass 
 2    0.247 athlet  
 3    0.229 sensitiv
 4    0.199 risk    
 5   -0.164 affect  
 6    0.163 moody   
 7   -0.112 individ 
 8    0.110 warm    
 9    0.105 cheerful
10    0.101 reliant </code></pre>
</div>
</div>
<p>Not-compassionate, athletic, sensitive: A mixed bag. (“Cares about self”?)</p>
</section>
<section id="anything-left-out-uniquenesses" class="level2">
<h2 class="anchored" data-anchor-id="anything-left-out-uniquenesses">Anything left out? Uniquenesses</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb132"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb132-1"><a href="#cb132-1" aria-hidden="true" tabindex="-1"></a><span class="fu">enframe</span>(bem<span class="fl">.15</span><span class="sc">$</span>uniquenesses, <span class="at">name=</span><span class="st">"quality"</span>, <span class="at">value=</span><span class="st">"uniq"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb132-2"><a href="#cb132-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_max</span>(uniq, <span class="at">n =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 2
   quality   uniq
   &lt;chr&gt;    &lt;dbl&gt;
 1 foullang 0.914
 2 lovchil  0.824
 3 analyt   0.812
 4 yielding 0.791
 5 masculin 0.723
 6 athlet   0.722
 7 shy      0.703
 8 gullible 0.700
 9 flatter  0.663
10 helpful  0.652</code></pre>
</div>
</div>
<p>Uses foul language especially, also loves children and analytical. So could use even more factors.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>