---
title: "Lecture notes"
format: html
---

Here are my lecture notes, all of them, in course order, with the slideshows, PDF versions of those (for printing) and the Quarto documents with the code that made the slides:

| Section | Slides | PDF | Code |
|:--------|:--------|:--------------|:----------|
|STAC32 course outline | [Slides](http://ritsokiguess.site/lecture-notes/outline_c32.html) | [PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/outline_c32.pdf) | [Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/outline_c32.qmd) |
|Running R | [Slides](http://ritsokiguess.site/lecture-notes/running.html) | [PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/running.pdf) | [Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/running.qmd) |
|Reading data files | [Slides](http://ritsokiguess.site/lecture-notes/readfile.html) | [PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/readfile.pdf) | [Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/readfile.qmd) |
|Drawing graphs (C32 version) | [Slides](http://ritsokiguess.site/lecture-notes/graphs_c32.html) | [PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/graphs_c32.pdf) | [Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/graphs_c32.qmd) |
|Drawing graphs (C33 version) | [Slides](http://ritsokiguess.site/lecture-notes/graphs_c33.html) | [PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/graphs_c33.pdf) | [Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/graphs_c33.qmd) |
|Numerical summaries | [Slides](http://ritsokiguess.site/lecture-notes/numsum.html) | [PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/numsum.pdf) | [Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/numsum.qmd) |
|Choosing things from dataframes| [Slides](http://ritsokiguess.site/lecture-notes/choosing.html) | [PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/choosing.pdf) | [Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/choosing.qmd) |
|Inference: one and two-sample t | [Slides](http://ritsokiguess.site/lecture-notes/inference_1.html) | [PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/inference_1.pdf) | [Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/inference_1.qmd) | 
|Bootstrap for sample mean | [Slides](http://ritsokiguess.site/lecture-notes/bootstrap_R.html) | [PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/bootstrap_R.pdf) | [Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/bootstrap_R.qmd) |
|Inference for means (C33) | [Slides](http://ritsokiguess.site/lecture-notes/inference_c33.html) | [PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/inference_c33.pdf) | [Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/inference_c33.qmd) |
|Assumptions for inference (C33)| [Slides](http://ritsokiguess.site/lecture-notes/assumptions_c33.html) | [PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/assumptions_c33.pdf) | [Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/assumptions_c33.qmd) |
|Inference: power | [Slides](http://ritsokiguess.site/lecture-notes/inference_2.html) | [PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/inference_2.pdf) | [Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/inference_2.qmd) |
|Inference: sign test | [Slides](http://ritsokiguess.site/lecture-notes/inference_3.html) | [PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/inference_3.pdf) | [Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/inference_3.qmd) |
|Inference: matched pairs | [Slides](http://ritsokiguess.site/lecture-notes/inference_4b.html) | [PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/inference_4b.pdf) | [Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/inference_4b.qmd) |
|Inference: Mood's median test | [Slides](http://ritsokiguess.site/lecture-notes/inference_5a.html) | [PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/inference_5a.pdf) | [Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/inference_5a.qmd) |
|Alternative tests (C33) | [Slides](http://ritsokiguess.site/lecture-notes/alternative_c33.html) | [PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/alternative_c33.pdf) | [Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/alternative_c33.qmd) |
|Inference: analysis of variance | [Slides](http://ritsokiguess.site/lecture-notes/inference_5b.html) | [PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/inference_5b.pdf) | [Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/inference_5b.qmd) |
|Writing reports | [Slides](http://ritsokiguess.site/lecture-notes/reports.html) |[PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/reports.pdf) |[Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/reports.qmd) |
|Tidying data | [Slides](http://ritsokiguess.site/lecture-notes/tidying.html) | [PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/tidying.pdf) | [Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/tidying.qmd) |
|Tidying data: extras | [Slides](http://ritsokiguess.site/lecture-notes/tidy_extra.html) | [PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/tidy_extra.pdf) | [Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/tidy_extra.qmd) |
|When `pivot_wider` goes wrong | [Slides](http://ritsokiguess.site/lecture-notes/wider_wrong.html) | [PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/wider_wrong.pdf) | [Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/wider_wrong.qmd) |
|Case study: windmill | [Slides](http://ritsokiguess.site/lecture-notes/windmill.html) | [PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/windmill.pdf) | [Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/windmill.qmd) |
|Case study: asphalt | [Slides](http://ritsokiguess.site/lecture-notes/asphalt.html) | [PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/asphalt.pdf) | [Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/asphalt.qmd) |
|Regression with categorical variables | [Slides](http://ritsokiguess.site/lecture-notes/with_categ.html) | [PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/with_categ.pdf) | [Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/with_categ.qmd) |
|Functions | [Slides](http://ritsokiguess.site/lecture-notes/functions.html) | [PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/functions.pdf) | [Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/functions.qmd) |
|Dates and Times | [Slides](http://ritsokiguess.site/lecture-notes/dates_and_times.html) | [PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/dates_and_times.pdf) | [Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/dates_and_times.qmd) |
|Durations, intervals and periods | [Slides](http://ritsokiguess.site/lecture-notes/dip.html) | [PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/dip.pdf) | [Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/dip.qmd) |
|STAC33 course outline | [Slides](http://ritsokiguess.site/lecture-notes/outline_c33.html) | [PDF](http://ritsokiguess.site/lecture-notes/outline_c33.pdf) | [Code](http://ritsokiguess.site/lecture-notes/outline_c33.qmd) |
|Running R | [Slides](http://ritsokiguess.site/lecture-notes/running.html) | [PDF](http://ritsokiguess.site/lecture-notes/running.pdf) | [Code](http://ritsokiguess.site/lecture-notes/running.qmd) |
|Reading data files | [Slides](http://ritsokiguess.site/lecture-notes/readfile.html) | [PDF](http://ritsokiguess.site/lecture-notes/readfile.pdf) | [Code](http://ritsokiguess.site/lecture-notes/readfile.qmd) |
|Drawing graphs | [Slides](http://ritsokiguess.site/lecture-notes/graphs_c33.html) | [PDF](http://ritsokiguess.site/lecture-notes/graphs_c33.pdf) | [Code](http://ritsokiguess.site/lecture-notes/graphs_c33.qmd) |
|Numerical summaries | [Slides](http://ritsokiguess.site/lecture-notes/numsum.html) | [PDF](http://ritsokiguess.site/lecture-notes/numsum.pdf) | [Code](http://ritsokiguess.site/lecture-notes/numsum.qmd) |
|Choosing things from dataframes| [Slides](http://ritsokiguess.site/lecture-notes/choosing.html) | [PDF](http://ritsokiguess.site/lecture-notes/choosing.pdf) | [Code](http://ritsokiguess.site/lecture-notes/choosing.qmd) |
|Inference for means | [Slides](http://ritsokiguess.site/lecture-notes/inference_c33.html) | [PDF](http://ritsokiguess.site/lecture-notes/inference_c33.pdf) | [Code](http://ritsokiguess.site/lecture-notes/inference_c33.qmd) | 
|Assumptions for inference | [Slides](http://ritsokiguess.site/lecture-notes/assumptions_c33.html) | [PDF](http://ritsokiguess.site/lecture-notes/assumptions_c33.pdf) | [Code](http://ritsokiguess.site/lecture-notes/assumptions_c33.qmd) |
|Bootstrap | [Slides](http://ritsokiguess.site/lecture-notes/bootstrap_c33.html) | [PDF](http://ritsokiguess.site/lecture-notes/bootstrap_c33.pdf) | [Code](http://ritsokiguess.site/lecture-notes/bootstrap_c33.qmd) |
|Power | [Slides](http://ritsokiguess.site/lecture-notes/power_c33.html) | [PDF](http://ritsokiguess.site/lecture-notes/power_c33.pdf) | [Code](http://ritsokiguess.site/lecture-notes/power_c33.qmd) |
|Alternative tests | [Slides](http://ritsokiguess.site/lecture-notes/alternative_c33.html) | [PDF](http://ritsokiguess.site/lecture-notes/alternative_c33.pdf) | [Code](http://ritsokiguess.site/lecture-notes/alternative_c33.qmd) |
|Analysis of variance | [Slides](http://ritsokiguess.site/lecture-notes/inference_5b.html) | [PDF](http://ritsokiguess.site/lecture-notes/inference_5b.pdf) | [Code](http://ritsokiguess.site/lecture-notes/inference_5b.qmd) |
|Writing reports | [Slides](http://ritsokiguess.site/lecture-notes/reports.html) |[PDF](http://ritsokiguess.site/lecture-notes/reports.pdf) |[Code](http://ritsokiguess.site/lecture-notes/reports.qmd) |
|Tidying data | [Slides](http://ritsokiguess.site/lecture-notes/tidying.html) | [PDF](http://ritsokiguess.site/lecture-notes/tidying.pdf) | [Code](http://ritsokiguess.site/lecture-notes/tidying.qmd) |
|Tidying data: extras | [Slides](http://ritsokiguess.site/lecture-notes/tidy_extra.html) | [PDF](http://ritsokiguess.site/lecture-notes/tidy_extra.pdf) | [Code](http://ritsokiguess.site/lecture-notes/tidy_extra.qmd) |
|When `pivot_wider` goes wrong | [Slides](http://ritsokiguess.site/lecture-notes/wider_wrong.html) | [PDF](http://ritsokiguess.site/lecture-notes/wider_wrong.pdf) | [Code](http://ritsokiguess.site/lecture-notes/wider_wrong.qmd) |
|Case study: windmill | [Slides](http://ritsokiguess.site/lecture-notes/windmill.html) | [PDF](http://ritsokiguess.site/lecture-notes/windmill.pdf) | [Code](http://ritsokiguess.site/lecture-notes/windmill.qmd) |
|Case study: asphalt | [Slides](http://ritsokiguess.site/lecture-notes/asphalt.html) | [PDF](http://ritsokiguess.site/lecture-notes/asphalt.pdf) | [Code](http://ritsokiguess.site/lecture-notes/asphalt.qmd) |
|Regression with categorical variables | [Slides](http://ritsokiguess.site/lecture-notes/with_categ.html) | [PDF](http://ritsokiguess.site/lecture-notes/with_categ.pdf) | [Code](http://ritsokiguess.site/lecture-notes/with_categ.qmd) |
|Functions | [Slides](http://ritsokiguess.site/lecture-notes/functions.html) | [PDF](http://ritsokiguess.site/lecture-notes/functions.pdf) | [Code](http://ritsokiguess.site/lecture-notes/functions.qmd) |
|Vector and matrix algebra | [Slides](http://ritsokiguess.site/lecture-notes/vector_matrix.html) | [PDF](http://ritsokiguess.site/lecture-notes/vector_matrix.pdf) |  [Code](http://ritsokiguess.site/lecture-notes/vector_matrix.qmd) |
|Bayesian statistics with Stan | [Slides](http://ritsokiguess.site/lecture-notes/rstan.html) | [PDF](http://ritsokiguess.site/lecture-notes/rstan.pdf) | [Code](http://ritsokiguess.site/lecture-notes/rstan.qmd) |
|STAD29 course outline | [Slides](http://ritsokiguess.site/lecture-notes/outline_d29.html) | [PDF](http://ritsokiguess.site/lecture-notes/outline_d29.pdf) | [Code](http://ritsokiguess.site/lecture-notes/outline_d29.qmd) |
|Regression revisited | [Slides](http://ritsokiguess.site/lecture-notes/regression.html) | [PDF](http://ritsokiguess.site/lecture-notes/regression.pdf) | [Code](http://ritsokiguess.site/lecture-notes/regression.qmd) |
|Logistic regression | [Slides](http://ritsokiguess.site/lecture-notes/logistic.html) | [PDF](http://ritsokiguess.site/lecture-notes/logistic.pdf) | [Code](http://ritsokiguess.site/lecture-notes/logistic.qmd) |
|Dates and Times | [Slides](http://ritsokiguess.site/lecture-notes/dates_and_times.html) | [PDF](http://ritsokiguess.site/lecture-notes/dates_and_times.pdf) | [Code](http://ritsokiguess.site/lecture-notes/dates_and_times.qmd) |
|Durations, intervals and periods | [Slides](http://ritsokiguess.site/lecture-notes/dip.html) | [PDF](http://ritsokiguess.site/lecture-notes/dip.pdf) | [Code](http://ritsokiguess.site/lecture-notes/dip.qmd) |
|Survival analysis| [Slides](http://ritsokiguess.site/lecture-notes/survival.html) |[PDF](http://ritsokiguess.site/lecture-notes/survival.pdf) | [Code](http://ritsokiguess.site/lecture-notes/survival.qmd) |
|ANOVA revisited | [Slides](http://ritsokiguess.site/lecture-notes/anova.html) | [PDF](http://ritsokiguess.site/lecture-notes/anova.pdf) | [Code](http://ritsokiguess.site/lecture-notes/anova.qmd) |
|Analysis of Covariance | [Slides](http://ritsokiguess.site/lecture-notes/ancova.html) | [PDF](http://ritsokiguess.site/lecture-notes/ancova.pdf) | [Code](http://ritsokiguess.site/lecture-notes/ancova.qmd) |
|Multivariate ANOVA | [Slides](http://ritsokiguess.site/lecture-notes/manova.html) | [PDF](http://ritsokiguess.site/lecture-notes/manova.pdf) | [Code](http://ritsokiguess.site/lecture-notes/manova.qmd) |
|Repeated measures | [Slides](http://ritsokiguess.site/lecture-notes/profile.html) | [PDF](http://ritsokiguess.site/lecture-notes/profile.pdf) | [Code](http://ritsokiguess.site/lecture-notes/profile.qmd) |
|Discriminant analysis | [Slides](http://ritsokiguess.site/lecture-notes/discrim.html) | [PDF](http://ritsokiguess.site/lecture-notes/discrim.pdf) | [Code](http://ritsokiguess.site/lecture-notes/discrim.qmd) |
|Cluster analysis | [Slides](http://ritsokiguess.site/lecture-notes/cluster.html) | [PDF](http://ritsokiguess.site/lecture-notes/cluster.pdf) | [Code](http://ritsokiguess.site/lecture-notes/cluster.qmd) |
|Drawing maps | [Slides](http://ritsokiguess.site/lecture-notes/mapping.html) | [PDF](http://ritsokiguess.site/lecture-notes/mapping.pdf) | [Code](http://ritsokiguess.site/lecture-notes/_mapping.qmd) |
|Principal components | [Slides](http://ritsokiguess.site/lecture-notes/princomp.html) | [PDF](http://ritsokiguess.site/lecture-notes/princomp.pdf) | [Code](http://ritsokiguess.site/lecture-notes/princomp.qmd) |
|Factor analysis| [Slides](http://ritsokiguess.site/lecture-notes/factor.html) | [PDF](http://ritsokiguess.site/lecture-notes/factor.pdf) | [Code](http://ritsokiguess.site/lecture-notes/factor.qmd) |
|Multiway frequency tables| [Slides](http://ritsokiguess.site/lecture-notes/multiway.html) | [PDF](http://ritsokiguess.site/lecture-notes/multiway.pdf) | [Code](http://ritsokiguess.site/lecture-notes/multiway.qmd) |












