---
title: "STAC32 Course Outline"
---

## This course

-   STAC32, Applications of Statistical Methods (Fall 2025)

-   Classes:

    -   2 hours of lectures / week, in person.
    -   1 hour of tutorial / week, in person **starting in week 2**. In tutorial, you work through a worksheet, with a TA available to help if you get stuck.
    -   "office hours" in person only. For 1 hour after each LEC01 lecture in IA 4028, or catch me after class, specifically Tu 14:00-15:00 and Th 13:00-14:00.

-   Instructor:

    -   Ken Butler, `ken.butler@utoronto.ca`, office IA 4028

## Programs and Prerequisites 1/2

-   This course *only* offers credit for the Statistics Applied Minor program. If you are in the Statistics Major, Minor or Specialist programs, or the Math Specialist (Statistics), you should instead take STAC33, offered in Winter.

-   To take this course, you need one of these courses as preparation:

    -   STAB27 / STA221
    -   PSYC08 / PSY202
    -   MGEB12

## Programs and Prerequisites 2/2

-   STAB57 is *not* suitable preparation for this course. If you have that, you should take STAC33.

-   Note that you may not combine the Applied Minor Program in Statistics with any other Statistics, Mathematics or Computer Science program, with the exception of the Computer Science Minor.

-   I check prerequisites.

## Getting help

-   Option 1: Quercus discussion boards:

    -   Look at the Quercus discussion board. Your question might have an answer there.
    -   If you don't see an answer to your question, post your question (start a new thread, "+Discussion" top right).
    -   If you see a question there that you can answer, go ahead and answer it.
    -   For an issue that is more personal, email me (below).

-   Option 2: come to tutorial and ask the TA.

-   Option 3: office hours. 

## E-mail

-   If you have a question about the Applied Minor program, look at [FAQ](http://ritsokiguess.site/home/faq.html) first
-   Personal issues, or non-FAQ questions about the Applied Minor *program*, only. (Questions about the STAC32 course material go on the discussion board.)
-   Use a U of T email (so that I know who you are)
-   Use a suitable subject, eg "Applied Minor Program"
-   Begin with "Dear Dr Butler"
-   State *clearly* how I can help you. 
-   Include your name (as U of T knows it) *and* student number
-   I aim to reply within two working days.

## Course objectives

-   This course will help you develop the skills to use software to analyze data, and to communicate the results.
    -   Effective communication of results is key, since in applied work you are always trying to convince someone of what you found
-   I want you to demonstrate your understanding and insight about the data you're working with
-   This will be assessed through assignments (approximately weekly).

    -   Expect to be asked for software output, explanation, or both.
    -   The grading will reward evidence of clear understanding and insight.

-   Along the way you will learn how to use Quarto documents and how to turn these into reports.

## Course materials

The blue things are all links:

-   [Quercus](https://q.utoronto.ca/): hand in assignments, receive grades, ancient lecture videos

-   [Course website](http://ritsokiguess.site/STAC32/): course news, reminders, lecture notes and code, assignment solutions, other stuff I want to share with you

-   [PASIAS](http://ritsokiguess.site/pasias2/) practice problems for you to work through, with my solutions.

-   [Reference: R for Data Science, 2nd ed](https://r4ds.hadley.nz/intro)

## Assessment

-   Assignments: 8 total, due after weeks 3 through 11. Best 6 count, total 25% (about 4% each).
    - expect that each assignment will cover up to the Tuesday lecture before it is due
    - will become available after the Wednesday tutorial, and will be due Monday at 11:59pm
    - you will need to hand in your rendered Quarto document showing your code, output, answers and explanations (in the first tutorial you will learn how to do this)
-   Midterm (30%), final (45%) exams  (in person). You *must get at least 40%* on the final exam to pass the course.

## Grading

-   Graders will give feedback on how you can improve for the next assignment.

-   Grades are the grader's best assessment of the quality of the work, and are unlikely to change on appeal.

-   My (detailed) solutions will be available after each assignment is handed in.

## Policies 1/2

-   There is a penalty for late work (1% per *hour*), and no work is accepted more than two days late. I will want to post my solutions for everyone to learn from. 
-   You have two "free" assignments (since the worst two scores are dropped); you may miss these without explanation. If you have to miss more assignments than this, consider whether you will be able to catch up the missed work in time to write good exams.
-   There are no make-up assessments. If you miss the midterm exam, the weight automatically goes onto the final exam.

## Policies 2/2

-   Accommodations (through Accessability only) consist of a maximum extension of two days, that you must request individually before the due date. With weekly assignments, longer extensions do you no favours because you are taking away time to prepare for the next one.
-   Things may change during the semester. I reserve the right to make changes to this course outline as we proceed, including taking class votes if needed.
- [Detailed course policies](https://ritsokiguess.site/STAC32/policies.pdf) (link).

## Course material 1/2

-   R installation / connection
-   Reading data files (of different sorts)
-   Making graphs
-   Numerical summaries
-   Statistical inference
-   Reports

## Course material 2/2

-   Tidying and organizing data
-   Case studies:
  - simple regression
  - multiple regression
-   Functions
-   Miscellaneous tasks (as time permits)


## Accessibility statement

Students with diverse learning styles and needs are welcome in this course. In particular, if you have a disability/health consideration that may require accommodations, please feel free to approach me and/or the AccessAbility Services Office as soon as possible. I will work with you and AccessAbility Services to ensure you can achieve your learning goals in this course. Enquiries are confidential. The UTSC AccessAbility Services staff are available by appointment to assess specific needs, provide referrals and arrange appropriate accommodations: (416) 287-7560 or by e-mail at `ability.utsc@utsc.utoronto.ca`.

## Expectations 1/5

-   I expect that you will do your own work in this course, and not seek help from outside this course. 
-   All the ideas you need to succeed in this course are contained in the lecture notes, with a few exceptions that I will tell you about. Seeking help from outside the course may confuse you more than it helps.

## Expectations 2/5

- In particular, using chatgpt or the like *will not help you* in this course.
- Your aim in this course should be to *learn how to use R yourself*, and to interpret the results yourself.  If you cannot do this, you will not succeed on the exams, *and* you will not be able to use either R or AI tools  effectively in the future because you will not have the skills required to critically assess their output.

## Expectations 3/5

- Large language models are literally *bullshit generators*: they have *no interest* in whether what they return is true or false, relevant or irrelevant. Thus, you should never use the output from them without reading it through carefully to assess it for correctness and relevance, and in order to do that, you need to have the relevant knowledge *in your brain*.
- The questions you will be answering in this course will be specific to particular datasets and analyses, and your answers will need to be equally specific and relevant. Answers speaking  in generalities will receive little or no credit.

## Expectations 4/5 {.smaller}

-   You may freely use anything that you learn from the lecture notes, PASIAS, solutions to previous assignments, or from conversation with the TAs or me. Everything in the course, unless otherwise stated, can be completed using this material.
-   Anything else, for example material you find on the Internet, **must be cited**. You can do this by giving the URL that it came from, for example "according to `https://r4ds.had.co.nz/data-import.html`", and then say whatever it is you learned from there.
-   If you want credit for *any* ideas that come from outside the course materials, you must say where they came from.
-   Citation is a way of making sure that people get credit for ideas that are theirs; not citing when you should is a way of erasing someone's point of view, and claiming that an idea from outside the course is yours when it is not is *plagiarism*.

## Expectations 5/5

-   I expect you to learn how to do things *as they are done in this course*. You will also make STAD29 much easier if you do that.
-   Detailed [course policies](https://ritsokiguess.site/STAC32/policies.pdf). If you have a question about administrative policies in the course, look here first.
-   [This (video)](https://twitter.com/i/status/1293543531496308736).
-   I am doing my best to give you an opportunity to learn something that will help you in your future. I would like you to take that opportunity.

