<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.340">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Regression revisited</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="regression_files/libs/clipboard/clipboard.min.js"></script>
<script src="regression_files/libs/quarto-html/quarto.js"></script>
<script src="regression_files/libs/quarto-html/popper.min.js"></script>
<script src="regression_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="regression_files/libs/quarto-html/anchor.min.js"></script>
<link href="regression_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="regression_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="regression_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="regression_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="regression_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="regression.html"><i class="bi bi-file-slides"></i>RevealJS</a></li><li><a href="regression.pdf"><i class="bi bi-file-pdf"></i>Beamer</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Regression revisited</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="regression" class="level2">
<h2 class="anchored" data-anchor-id="regression">Regression</h2>
<ul>
<li><p>Use regression when one variable is an outcome (<em>response</em>, <span class="math inline">\(y\)</span>).</p></li>
<li><p>See if/how response depends on other variable(s), <em>explanatory</em>, <span class="math inline">\(x_1, x_2,\ldots\)</span>.</p></li>
<li><p>Can have <em>one</em> or <em>more than one</em> explanatory variable, but always one response.</p></li>
<li><p>Assumes a <em>straight-line</em> relationship between response and explanatory.</p></li>
<li><p>Ask:</p>
<ul>
<li><em>is there</em> a relationship between <span class="math inline">\(y\)</span> and <span class="math inline">\(x\)</span>’s, and if so, which ones?</li>
<li>what does the relationship look like?</li>
</ul></li>
</ul>
</section>
<section id="packages" class="level2">
<h2 class="anchored" data-anchor-id="packages">Packages</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS) <span class="co"># for Box-Cox, later</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.2     ✔ readr     2.1.4
✔ forcats   0.5.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.2     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
✔ purrr     1.0.1     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
✖ dplyr::select() masks MASS::select()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(marginaleffects)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(conflicted)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">conflict_prefer</span>(<span class="st">"select"</span>, <span class="st">"dplyr"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>[conflicted] Will prefer dplyr::select over any other package.</code></pre>
</div>
</div>
</section>
<section id="a-regression-with-one-x" class="level2">
<h2 class="anchored" data-anchor-id="a-regression-with-one-x">A regression with one <span class="math inline">\(x\)</span></h2>
<p>13 children, measure average total sleep time (ATST, mins) and age (years) for each. See if ATST depends on age. Data in <code>sleep.txt</code>, ATST then age. Read in data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>my_url <span class="ot">&lt;-</span> <span class="st">"http://ritsokiguess.site/datafiles/sleep.txt"</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>sleep <span class="ot">&lt;-</span> <span class="fu">read_delim</span>(my_url, <span class="st">" "</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 13 Columns: 2
── Column specification ────────────────────────────────────────────────────────
Delimiter: " "
dbl (2): atst, age

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
</section>
<section id="check-data" class="level2">
<h2 class="anchored" data-anchor-id="check-data">Check data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sleep)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      atst            age        
 Min.   :461.8   Min.   : 4.400  
 1st Qu.:491.1   1st Qu.: 7.200  
 Median :528.3   Median : 8.900  
 Mean   :519.3   Mean   : 9.058  
 3rd Qu.:532.5   3rd Qu.:11.100  
 Max.   :586.0   Max.   :14.000  </code></pre>
</div>
</div>
<p>Make scatter plot of ATST (response) vs.&nbsp;age (explanatory) using code overleaf:</p>
</section>
<section id="the-scatterplot" class="level2">
<h2 class="anchored" data-anchor-id="the-scatterplot">The scatterplot</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sleep, <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> atst)) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="regression_files/figure-html/suggo-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="correlation" class="level2">
<h2 class="anchored" data-anchor-id="correlation">Correlation</h2>
<ul>
<li>Measures how well a straight line fits the data:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(sleep, <span class="fu">cor</span>(atst, age))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.9515469</code></pre>
</div>
</div>
<ul>
<li><p><span class="math inline">\(1\)</span> is perfect upward trend, <span class="math inline">\(-1\)</span> is perfect downward trend, 0 is no trend.</p></li>
<li><p>This one close to perfect downward trend.</p></li>
<li><p>Can do correlations of all pairs of variables:</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(sleep)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           atst        age
atst  1.0000000 -0.9515469
age  -0.9515469  1.0000000</code></pre>
</div>
</div>
</section>
<section id="lowess-curve" class="level2">
<h2 class="anchored" data-anchor-id="lowess-curve">Lowess curve</h2>
<ul>
<li><p>Sometimes nice to guide the eye: is the trend straight, or not?</p></li>
<li><p>Idea: <em>lowess curve</em>. “Locally weighted least squares”, not affected by outliers, not constrained to be linear.</p></li>
<li><p>Lowess is a <em>guide</em>: even if straight line appropriate, may wiggle/bend a little. Looking for <em>serious</em> problems with linearity.</p></li>
<li><p>Add lowess curve to plot using <code>geom_smooth</code>:</p></li>
</ul>
</section>
<section id="plot-with-lowess-curve" class="level2">
<h2 class="anchored" data-anchor-id="plot-with-lowess-curve">Plot with lowess curve</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sleep, <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> atst)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using method = 'loess' and formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="regression_files/figure-html/icko-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="the-regression" class="level2">
<h2 class="anchored" data-anchor-id="the-regression">The regression</h2>
<p>Scatterplot shows no obvious curve, and a pretty clear downward trend. So we can run the regression:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>sleep<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">lm</span>(atst <span class="sc">~</span> age, <span class="at">data =</span> sleep)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="the-output" class="level2">
<h2 class="anchored" data-anchor-id="the-output">The output</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sleep<span class="fl">.1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = atst ~ age, data = sleep)

Residuals:
    Min      1Q  Median      3Q     Max 
-23.011  -9.365   2.372   6.770  20.411 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  646.483     12.918   50.05 2.49e-14 ***
age          -14.041      1.368  -10.26 5.70e-07 ***
---
Signif. codes:  
0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 13.15 on 11 degrees of freedom
Multiple R-squared:  0.9054,    Adjusted R-squared:  0.8968 
F-statistic: 105.3 on 1 and 11 DF,  p-value: 5.7e-07</code></pre>
</div>
</div>
</section>
<section id="conclusions" class="level2">
<h2 class="anchored" data-anchor-id="conclusions">Conclusions</h2>
<ul>
<li><p>The relationship appears to be a straight line, with a downward trend.</p></li>
<li><p><span class="math inline">\(F\)</span>-tests for model as a whole and <span class="math inline">\(t\)</span>-test for slope (same) both confirm this (P-value <span class="math inline">\(5.7\times 10^{-7}=0.00000057\)</span>).</p></li>
<li><p>Slope is <span class="math inline">\(-14\)</span>, so a 1-year increase in age goes with a 14-minute decrease in ATST on average.</p></li>
<li><p>R-squared is correlation squared (when one <span class="math inline">\(x\)</span> anyway), between 0 and 1 (1 good, 0 bad).</p></li>
<li><p>Here R-squared is 0.9054, pleasantly high.</p></li>
</ul>
</section>
<section id="doing-things-with-the-regression-output" class="level2">
<h2 class="anchored" data-anchor-id="doing-things-with-the-regression-output">Doing things with the regression output</h2>
<ul>
<li><p>Output from regression (and eg. <span class="math inline">\(t\)</span>-test) is all right to look at, but hard to extract and re-use information from.</p></li>
<li><p>Package <code>broom</code> extracts info from model output in way that can be used in pipe (later):</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(sleep<span class="fl">.1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term        estimate std.error statistic  p.value
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)    646.      12.9       50.0 2.49e-14
2 age            -14.0      1.37     -10.3 5.70e- 7</code></pre>
</div>
</div>
</section>
<section id="also-one-line-summary-of-model" class="level2">
<h2 class="anchored" data-anchor-id="also-one-line-summary-of-model">also one-line summary of model:</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(sleep<span class="fl">.1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squared sigma statistic     p.value    df
      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt; &lt;dbl&gt;
1     0.905         0.897  13.2      105. 0.000000570     1
# ℹ 6 more variables: logLik &lt;dbl&gt;, AIC &lt;dbl&gt;, BIC &lt;dbl&gt;,
#   deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
</div>
</div>
</section>
<section id="broom-part-2" class="level2">
<h2 class="anchored" data-anchor-id="broom-part-2">Broom part 2</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>sleep<span class="fl">.1</span> <span class="sc">%&gt;%</span> <span class="fu">augment</span>(sleep)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 13 × 8
    atst   age .fitted .resid   .hat .sigma .cooksd
   &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
 1  586   4.4     585.   1.30 0.312    13.8 0.00320
 2  462. 14       450.  11.8  0.341    13.0 0.319  
 3  491. 10.1     505. -13.6  0.0887   13.0 0.0568 
 4  565   6.7     552.  12.6  0.137    13.1 0.0844 
 5  462  11.5     485. -23.0  0.141    11.3 0.294  
 6  532.  9.6     512.  20.4  0.0801   12.0 0.114  
 7  478. 12.4     472.   5.23 0.198    13.7 0.0243 
 8  515.  8.9     522.  -6.32 0.0772   13.6 0.0105 
 9  493  11.1     491.   2.37 0.122    13.8 0.00258
10  528.  7.75    538.  -9.37 0.0954   13.4 0.0296 
11  576.  5.5     569.   6.64 0.214    13.6 0.0441 
12  532.  8.6     526.   6.77 0.0792   13.6 0.0124 
13  530.  7.2     545. -14.9  0.114    12.9 0.0933 
# ℹ 1 more variable: .std.resid &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Useful for plotting residuals against an <span class="math inline">\(x\)</span>-variable.</p>
</section>
<section id="ci-for-mean-response-and-prediction-intervals" class="level2">
<h2 class="anchored" data-anchor-id="ci-for-mean-response-and-prediction-intervals">CI for mean response and prediction intervals</h2>
<p>Once useful regression exists, use it for prediction:</p>
<ul>
<li><p>To get a single number for prediction at a given <span class="math inline">\(x\)</span>, substitute into regression equation, eg. age 10: predicted ATST is <span class="math inline">\(646.48-14.04(10)=506\)</span> minutes.</p></li>
<li><p>To express uncertainty of this prediction:</p></li>
<li><p><em>CI for mean response</em> expresses uncertainty about mean ATST for all children aged 10, based on data.</p></li>
<li><p><em>Prediction interval</em> expresses uncertainty about predicted ATST for a new child aged 10 whose ATST not known. More uncertain.</p></li>
<li><p>Also do above for a child aged 5.</p></li>
</ul>
</section>
<section id="the-marginaleffects-package-12" class="level2">
<h2 class="anchored" data-anchor-id="the-marginaleffects-package-12">The <code>marginaleffects</code> package 1/2</h2>
<p>To get predictions for specific values, set up a dataframe with those values first:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>new <span class="ot">&lt;-</span> <span class="fu">datagrid</span>(<span class="at">model =</span> sleep<span class="fl">.1</span>, <span class="at">age =</span> <span class="fu">c</span>(<span class="dv">10</span>, <span class="dv">5</span>))</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>new</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      atst age
1 519.3038  10
2 519.3038   5</code></pre>
</div>
</div>
<p>Any variables in the dataframe that you don’t specify are set to their mean values (quantitative) or most common category (categorical).</p>
</section>
<section id="the-marginaleffects-package-22" class="level2">
<h2 class="anchored" data-anchor-id="the-marginaleffects-package-22">The <code>marginaleffects</code> package 2/2</h2>
<p>Then feed into <code>newdata</code> in <code>predictions</code>. This contains a lot of columns, so you probably want only to display the ones you care about:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(<span class="fu">predictions</span>(sleep<span class="fl">.1</span>, <span class="at">newdata =</span> new)) <span class="sc">%&gt;%</span> </span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(estimate, conf.low, conf.high, age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  estimate conf.low conf.high age
1 506.0729 498.4899  513.6558  10
2 576.2781 563.2588  589.2974   5</code></pre>
</div>
</div>
<p>The confidence limits are a 95% confidence interval for the mean response at that <code>age</code>.</p>
</section>
<section id="prediction-intervals" class="level2">
<h2 class="anchored" data-anchor-id="prediction-intervals">Prediction intervals</h2>
<p>These are obtained (instead) with <code>predict</code> as below. Use the same dataframe <code>new</code> as before:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>pp <span class="ot">&lt;-</span> <span class="fu">predict</span>(sleep<span class="fl">.1</span>, new, <span class="at">interval =</span> <span class="st">"p"</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(new, pp) <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>atst)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  age      fit      lwr      upr
1  10 506.0729 475.8982 536.2475
2   5 576.2781 543.8474 608.7088</code></pre>
</div>
</div>
</section>
<section id="comments" class="level2">
<h2 class="anchored" data-anchor-id="comments">Comments</h2>
<ul>
<li><p>Age 10 closer to centre of data, so intervals are both narrower than those for age 5.</p></li>
<li><p>Prediction intervals bigger than CI for mean (additional uncertainty).</p></li>
<li><p>Technical note: output from <code>predict</code> is R <code>matrix</code>, not data frame, so Tidyverse <code>bind_cols</code> does not work. Use base R <code>cbind</code>.</p></li>
</ul>
</section>
<section id="that-grey-envelope" class="level2">
<h2 class="anchored" data-anchor-id="that-grey-envelope">That grey envelope</h2>
<p>Marks confidence interval for mean for all <span class="math inline">\(x\)</span>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sleep, <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> atst)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>) <span class="sc">+</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">420</span>, <span class="dv">600</span>, <span class="dv">20</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="regression_files/figure-html/bRegression-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="diagnostics" class="level2">
<h2 class="anchored" data-anchor-id="diagnostics">Diagnostics</h2>
<p>How to tell whether a straight-line regression is appropriate?</p>
<ul>
<li><p>Before: check scatterplot for straight trend.</p></li>
<li><p>After: plot <em>residuals</em> (observed minus predicted response) against predicted values. Aim: a plot with no pattern.</p></li>
</ul>
</section>
<section id="residual-plot" class="level2">
<h2 class="anchored" data-anchor-id="residual-plot">Residual plot</h2>
<p>Not much pattern here — regression appropriate.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sleep<span class="fl">.1</span>, <span class="fu">aes</span>(<span class="at">x =</span> .fitted, <span class="at">y =</span> .resid)) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="regression_files/figure-html/akjhkadjfhjahnkkk-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="an-inappropriate-regression" class="level2">
<h2 class="anchored" data-anchor-id="an-inappropriate-regression">An inappropriate regression</h2>
<p>Different data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>my_url <span class="ot">&lt;-</span> <span class="st">"http://ritsokiguess.site/datafiles/curvy.txt"</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>curvy <span class="ot">&lt;-</span> <span class="fu">read_delim</span>(my_url, <span class="st">" "</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 10 Columns: 2
── Column specification ────────────────────────────────────
Delimiter: " "
dbl (2): xx, yy

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
</section>
<section id="scatterplot" class="level2">
<h2 class="anchored" data-anchor-id="scatterplot">Scatterplot</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(curvy, <span class="fu">aes</span>(<span class="at">x =</span> xx, <span class="at">y =</span> yy)) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="regression_files/figure-html/bRegression-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="regression-line-anyway" class="level2">
<h2 class="anchored" data-anchor-id="regression-line-anyway">Regression line, anyway</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>curvy<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">lm</span>(yy <span class="sc">~</span> xx, <span class="at">data =</span> curvy)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(curvy<span class="fl">.1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = yy ~ xx, data = curvy)

Residuals:
   Min     1Q Median     3Q    Max 
-3.582 -2.204  0.000  1.514  3.509 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)   7.5818     1.5616   4.855  0.00126 **
xx            0.9818     0.2925   3.356  0.00998 **
---
Signif. codes:  
0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.657 on 8 degrees of freedom
Multiple R-squared:  0.5848,    Adjusted R-squared:  0.5329 
F-statistic: 11.27 on 1 and 8 DF,  p-value: 0.009984</code></pre>
</div>
</div>
</section>
<section id="residual-plot-1" class="level2">
<h2 class="anchored" data-anchor-id="residual-plot-1">Residual plot</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(curvy<span class="fl">.1</span>, <span class="fu">aes</span>(<span class="at">x =</span> .fitted, <span class="at">y =</span> .resid)) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="regression_files/figure-html/altoadige-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="no-good-fixing-it-up" class="level2">
<h2 class="anchored" data-anchor-id="no-good-fixing-it-up">No good: fixing it up</h2>
<ul>
<li><p>Residual plot has <em>curve</em>: middle residuals positive, high and low ones negative. Bad.</p></li>
<li><p>Fitting a curve would be better. Try this:</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>curvy<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">lm</span>(yy <span class="sc">~</span> xx <span class="sc">+</span> <span class="fu">I</span>(xx<span class="sc">^</span><span class="dv">2</span>), <span class="at">data =</span> curvy)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><p>Adding <code>xx</code>-squared term, to allow for curve.</p></li>
<li><p>Another way to do same thing: specify how model <em>changes</em>:</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>curvy<span class="fl">.2</span>a <span class="ot">&lt;-</span> <span class="fu">update</span>(curvy<span class="fl">.1</span>, . <span class="sc">~</span> . <span class="sc">+</span> <span class="fu">I</span>(xx<span class="sc">^</span><span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="regression-2" class="level2">
<h2 class="anchored" data-anchor-id="regression-2">Regression 2</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(curvy<span class="fl">.2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
  term        estimate std.error statistic   p.value
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)    3.9      0.773       5.04 0.00149  
2 xx             3.74     0.400       9.36 0.0000331
3 I(xx^2)       -0.307    0.0428     -7.17 0.000182 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(curvy<span class="fl">.2</span>) <span class="co">#</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squared sigma statistic   p.value    df
      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt;
1     0.950         0.936 0.983      66.8 0.0000275     2
# ℹ 6 more variables: logLik &lt;dbl&gt;, AIC &lt;dbl&gt;, BIC &lt;dbl&gt;,
#   deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
</div>
</div>
</section>
<section id="comments-1" class="level2">
<h2 class="anchored" data-anchor-id="comments-1">Comments</h2>
<ul>
<li><p><code>xx</code>-squared term definitely significant (P-value 0.000182), so need this curve to describe relationship.</p></li>
<li><p>Adding squared term has made R-squared go up from 0.5848 to 0.9502: great improvement.</p></li>
<li><p>This is a definite curve!</p></li>
</ul>
</section>
<section id="the-residual-plot-now" class="level2">
<h2 class="anchored" data-anchor-id="the-residual-plot-now">The residual plot now</h2>
<p>No problems any more:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(curvy<span class="fl">.2</span>, <span class="fu">aes</span>(<span class="at">x =</span> .fitted, <span class="at">y =</span> .resid)) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="regression_files/figure-html/bRegression-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="another-way-to-handle-curves" class="level2">
<h2 class="anchored" data-anchor-id="another-way-to-handle-curves">Another way to handle curves</h2>
<ul>
<li><p>Above, saw that changing <span class="math inline">\(x\)</span> (adding <span class="math inline">\(x^2\)</span>) was a way of handling curved relationships.</p></li>
<li><p>Another way: change <span class="math inline">\(y\)</span> (transformation).</p></li>
<li><p>Can guess how to change <span class="math inline">\(y\)</span>, or might be theory:</p></li>
<li><p>example: relationship <span class="math inline">\(y=ae^{bx}\)</span> (exponential growth):</p></li>
<li><p>take logs to get <span class="math inline">\(\ln y=\ln a + bx\)</span>.</p></li>
<li><p>Taking logs has made relationship linear (<span class="math inline">\(\ln y\)</span> as response).</p></li>
<li><p>Or, <em>estimate</em> transformation, using Box-Cox method.</p></li>
</ul>
</section>
<section id="box-cox" class="level2">
<h2 class="anchored" data-anchor-id="box-cox">Box-Cox</h2>
<ul>
<li><p>Install package <code>MASS</code> via <code>install.packages("MASS")</code> (only need to do <em>once</em>)</p></li>
<li><p>Every R session you want to use something in <code>MASS</code>, type <code>library(MASS)</code></p></li>
</ul>
</section>
<section id="some-made-up-data" class="level2">
<h2 class="anchored" data-anchor-id="some-made-up-data">Some made-up data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>my_url <span class="ot">&lt;-</span> <span class="st">"http://ritsokiguess.site/datafiles/madeup2.csv"</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>madeup <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(my_url)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>madeup</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 3
   ...1     x     y
  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     1     0  17.9
2     2     1  33.6
3     3     2  82.7
4     4     3  31.2
5     5     4 177. 
6     6     5 359. 
7     7     6 469. 
8     8     7 283. </code></pre>
</div>
</div>
<p>Seems to be faster-than-linear growth, maybe exponential growth.</p>
</section>
<section id="scatterplot-faster-than-linear-growth" class="level2">
<h2 class="anchored" data-anchor-id="scatterplot-faster-than-linear-growth">Scatterplot: faster than linear growth</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(madeup, <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using method = 'loess' and formula = 'y ~
x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="regression_files/figure-html/dsljhsdjlhf-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="running-box-cox" class="level2">
<h2 class="anchored" data-anchor-id="running-box-cox">Running Box-Cox</h2>
<ul>
<li><p><code>library(MASS)</code> first.</p></li>
<li><p>Feed <code>boxcox</code> a model formula with a squiggle in it, such as you would use for <code>lm</code>.</p></li>
<li><p>Output: a graph (next page):</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxcox</span>(y <span class="sc">~</span> x, <span class="at">data =</span> madeup)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="the-box-cox-output" class="level2">
<h2 class="anchored" data-anchor-id="the-box-cox-output">The Box-Cox output</h2>
<div class="cell">
<div class="cell-output-display">
<p><img src="regression_files/figure-html/trento-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="comments-2" class="level2">
<h2 class="anchored" data-anchor-id="comments-2">Comments</h2>
<ul>
<li><p><span class="math inline">\(\lambda\)</span> (lambda) is the power by which you should transform <span class="math inline">\(y\)</span> to get the relationship straight (straighter). Power 0 is “take logs”</p></li>
<li><p>Middle dotted line marks best single value of <span class="math inline">\(\lambda\)</span> (here about 0.1).</p></li>
<li><p>Outer dotted lines mark 95% CI for <span class="math inline">\(\lambda\)</span>, here <span class="math inline">\(-0.3\)</span> to 0.7, approx. (Rather uncertain about best transformation.)</p></li>
<li><p>Any power transformation within the CI supported by data. In this case, log (<span class="math inline">\(\lambda=0\)</span>) and square root (<span class="math inline">\(\lambda=0.5\)</span>) good, but no transformation (<span class="math inline">\(\lambda=1\)</span>) not.</p></li>
<li><p>Pick a “round-number” value of <span class="math inline">\(\lambda\)</span> like <span class="math inline">\(2,1,0.5,0,-0.5,-1\)</span>. Here 0 and 0.5 good values to pick.</p></li>
</ul>
</section>
<section id="did-transformation-straighten-things" class="level2">
<h2 class="anchored" data-anchor-id="did-transformation-straighten-things">Did transformation straighten things?</h2>
<ul>
<li>Plot transformed <span class="math inline">\(y\)</span> against <span class="math inline">\(x\)</span>. Here, log:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(madeup, <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> <span class="fu">log</span>(y))) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="regression_files/figure-html/bRegression-24-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Looks much straighter.</p>
</section>
<section id="regression-with-transformed-y" class="level2">
<h2 class="anchored" data-anchor-id="regression-with-transformed-y">Regression with transformed <span class="math inline">\(y\)</span></h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>madeup<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(y) <span class="sc">~</span> x, <span class="at">data =</span> madeup)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(madeup<span class="fl">.1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squared sigma statistic p.value    df
      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
1     0.811         0.779 0.588      25.7 0.00228     1
# ℹ 6 more variables: logLik &lt;dbl&gt;, AIC &lt;dbl&gt;, BIC &lt;dbl&gt;,
#   deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(madeup<span class="fl">.1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term        estimate std.error statistic  p.value
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)    3.03     0.379       7.98 0.000206
2 x              0.460    0.0907      5.07 0.00228 </code></pre>
</div>
</div>
<p>R-squared now decently high.</p>
</section>
<section id="multiple-regression" class="level2">
<h2 class="anchored" data-anchor-id="multiple-regression">Multiple regression</h2>
<ul>
<li><p>What if more than one <span class="math inline">\(x\)</span>? Extra issues:</p>
<ul>
<li><p>Now one intercept and a slope for each <span class="math inline">\(x\)</span>: how to interpret?</p></li>
<li><p>Which <span class="math inline">\(x\)</span>-variables actually help to predict <span class="math inline">\(y\)</span>?</p></li>
<li><p>Different interpretations of “global” <span class="math inline">\(F\)</span>-test and individual <span class="math inline">\(t\)</span>-tests.</p></li>
<li><p>R-squared no longer correlation squared, but still interpreted as “higher better”.</p></li>
<li><p>In <code>lm</code> line, add extra <span class="math inline">\(x\)</span>s after <code>~</code>.</p></li>
<li><p>Interpretation not so easy (and other problems that can occur).</p></li>
</ul></li>
</ul>
</section>
<section id="multiple-regression-example" class="level2">
<h2 class="anchored" data-anchor-id="multiple-regression-example">Multiple regression example</h2>
<p>Study of women and visits to health professionals, and how the number of visits might be related to other variables:</p>
<p><code>timedrs</code> response, others explanatory.</p>
</section>
<section id="the-data" class="level2">
<h2 class="anchored" data-anchor-id="the-data">The data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>my_url <span class="ot">&lt;-</span> </span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"http://ritsokiguess.site/datafiles/regressx.txt"</span></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>visits <span class="ot">&lt;-</span> <span class="fu">read_delim</span>(my_url, <span class="st">" "</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 465 Columns: 5
── Column specification ────────────────────────────────────
Delimiter: " "
dbl (5): subjno, timedrs, phyheal, menheal, stress

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
</section>
<section id="check-data-1" class="level2">
<h2 class="anchored" data-anchor-id="check-data-1">Check data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>visits</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 465 × 5
   subjno timedrs phyheal menheal stress
    &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;
 1      1       1       5       8    265
 2      2       3       4       6    415
 3      3       0       3       4     92
 4      4      13       2       2    241
 5      5      15       3       6     86
 6      6       3       5       5    247
 7      7       2       5       6     13
 8      8       0       4       5     12
 9      9       7       5       4    269
10     10       4       3       9    391
# ℹ 455 more rows</code></pre>
</div>
</div>
</section>
<section id="fit-multiple-regression" class="level2">
<h2 class="anchored" data-anchor-id="fit-multiple-regression">Fit multiple regression</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>visits<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">lm</span>(timedrs <span class="sc">~</span> phyheal <span class="sc">+</span> menheal <span class="sc">+</span> stress,</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> visits)</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(visits<span class="fl">.1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = timedrs ~ phyheal + menheal + stress, data = visits)

Residuals:
    Min      1Q  Median      3Q     Max 
-14.792  -4.353  -1.815   0.902  65.886 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -3.704848   1.124195  -3.296 0.001058 ** 
phyheal      1.786948   0.221074   8.083  5.6e-15 ***
menheal     -0.009666   0.129029  -0.075 0.940318    
stress       0.013615   0.003612   3.769 0.000185 ***
---
Signif. codes:  
0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 9.708 on 461 degrees of freedom
Multiple R-squared:  0.2188,    Adjusted R-squared:  0.2137 
F-statistic: 43.03 on 3 and 461 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="the-slopes" class="level2">
<h2 class="anchored" data-anchor-id="the-slopes">The slopes</h2>
<ul>
<li><p>Model as a whole strongly significant even though R-sq not very big (lots of data). At least one of the <span class="math inline">\(x\)</span>’s predicts <code>timedrs</code>.</p></li>
<li><p>The physical health and stress variables definitely help to predict the number of visits, but <em>with those in the model</em> we don’t need <code>menheal</code>. However, look at prediction of <code>timedrs</code> from <code>menheal</code> by itself:</p></li>
</ul>
</section>
<section id="just-menheal" class="level2">
<h2 class="anchored" data-anchor-id="just-menheal">Just <code>menheal</code></h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>visits<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">lm</span>(timedrs <span class="sc">~</span> menheal, <span class="at">data =</span> visits)</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(visits<span class="fl">.2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = timedrs ~ menheal, data = visits)

Residuals:
    Min      1Q  Median      3Q     Max 
-13.826  -5.150  -2.818   1.177  72.513 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   3.8159     0.8702   4.385 1.44e-05 ***
menheal       0.6672     0.1173   5.688 2.28e-08 ***
---
Signif. codes:  
0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 10.6 on 463 degrees of freedom
Multiple R-squared:  0.06532,   Adjusted R-squared:  0.0633 
F-statistic: 32.35 on 1 and 463 DF,  p-value: 2.279e-08</code></pre>
</div>
</div>
</section>
<section id="menheal-by-itself" class="level2">
<h2 class="anchored" data-anchor-id="menheal-by-itself"><code>menheal</code> by itself</h2>
<ul>
<li><p><code>menheal</code> by itself <em>does</em> significantly help to predict <code>timedrs</code>.</p></li>
<li><p>But the R-sq is much less (6.5% vs.&nbsp;22%).</p></li>
<li><p>So other two variables do a better job of prediction.</p></li>
<li><p>With those variables in the regression (<code>phyheal</code> and <code>stress</code>), don’t need <code>menheal</code> <em>as well</em>.</p></li>
</ul>
</section>
<section id="investigating-via-correlation" class="level2">
<h2 class="anchored" data-anchor-id="investigating-via-correlation">Investigating via correlation</h2>
<p>Leave out first column (<code>subjno</code>):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>visits <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>subjno) <span class="sc">%&gt;%</span> <span class="fu">cor</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          timedrs   phyheal   menheal    stress
timedrs 1.0000000 0.4395293 0.2555703 0.2865951
phyheal 0.4395293 1.0000000 0.5049464 0.3055517
menheal 0.2555703 0.5049464 1.0000000 0.3697911
stress  0.2865951 0.3055517 0.3697911 1.0000000</code></pre>
</div>
</div>
<ul>
<li><p><code>phyheal</code> most strongly correlated with <code>timedrs</code>.</p></li>
<li><p>Not much to choose between other two.</p></li>
<li><p>But <code>menheal</code> has higher correlation with <code>phyheal</code>, so not as much to <em>add</em> to prediction as <code>stress</code>.</p></li>
<li><p>Goes to show things more complicated in multiple regression.</p></li>
</ul>
</section>
<section id="residual-plot-from-timedrs-on-all" class="level2">
<h2 class="anchored" data-anchor-id="residual-plot-from-timedrs-on-all">Residual plot (from <code>timedrs</code> on all)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(visits<span class="fl">.1</span>, <span class="fu">aes</span>(<span class="at">x =</span> .fitted, <span class="at">y =</span> .resid)) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="regression_files/figure-html/iffy8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Apparently random. But…</p>
</section>
<section id="normal-quantile-plot-of-residuals" class="level2">
<h2 class="anchored" data-anchor-id="normal-quantile-plot-of-residuals">Normal quantile plot of residuals</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(visits<span class="fl">.1</span>, <span class="fu">aes</span>(<span class="at">sample =</span> .resid)) <span class="sc">+</span> <span class="fu">stat_qq</span>() <span class="sc">+</span> <span class="fu">stat_qq_line</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="regression_files/figure-html/bRegression-32-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Not normal at all; upper tail is way too long.</p>
</section>
<section id="absolute-residuals" class="level2">
<h2 class="anchored" data-anchor-id="absolute-residuals">Absolute residuals</h2>
<p>Is there trend in <em>size</em> of residuals (fan-out)? Plot <em>absolute value</em> of residual against fitted value:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(visits<span class="fl">.1</span>, <span class="fu">aes</span>(<span class="at">x =</span> .fitted, <span class="at">y =</span> <span class="fu">abs</span>(.resid))) <span class="sc">+</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_smooth</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="regression_files/figure-html/bRegression-33-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="comments-3" class="level2">
<h2 class="anchored" data-anchor-id="comments-3">Comments</h2>
<ul>
<li><p>On the normal quantile plot:</p>
<ul>
<li><p>highest (most positive) residuals are <em>way</em> too high</p></li>
<li><p>distribution of residuals skewed to right (not normal at all)</p></li>
</ul></li>
<li><p>On plot of absolute residuals:</p>
<ul>
<li><p>size of residuals getting bigger as fitted values increase</p></li>
<li><p>predictions getting more variable as fitted values increase</p></li>
<li><p>that is, predictions getting <em>less accurate</em> as fitted values increase, but predictions should be equally accurate all way along.</p></li>
</ul></li>
<li><p>Both indicate problems with regression, of kind that transformation of response often fixes: that is, predict <em>function</em> of response <code>timedrs</code> instead of <code>timedrs</code> itself.</p></li>
</ul>
</section>
<section id="box-cox-transformations" class="level2">
<h2 class="anchored" data-anchor-id="box-cox-transformations">Box-Cox transformations</h2>
<ul>
<li><p>Taking log of <code>timedrs</code> and having it work: lucky guess. How to find good transformation?</p></li>
<li><p>Box-Cox again.</p></li>
<li><p>Extra problem: some of <code>timedrs</code> values are 0, but Box-Cox expects all +. Note response for <code>boxcox</code>:</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxcox</span>(timedrs <span class="sc">+</span> <span class="dv">1</span> <span class="sc">~</span> phyheal <span class="sc">+</span> menheal <span class="sc">+</span> stress, <span class="at">data =</span> visits)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="try-1" class="level2">
<h2 class="anchored" data-anchor-id="try-1">Try 1</h2>
<div class="cell">
<div class="cell-output-display">
<p><img src="regression_files/figure-html/bRegression-36-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="comments-on-try-1" class="level2">
<h2 class="anchored" data-anchor-id="comments-on-try-1">Comments on try 1</h2>
<ul>
<li><p>Best: <span class="math inline">\(\lambda\)</span> just less than zero.</p></li>
<li><p>Hard to see scale.</p></li>
<li><p>Focus on <span class="math inline">\(\lambda\)</span> in <span class="math inline">\((-0.3,0.1)\)</span>:</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>my.lambda <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="fl">0.3</span>, <span class="fl">0.1</span>, <span class="fl">0.01</span>)</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>my.lambda</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] -0.30 -0.29 -0.28 -0.27 -0.26 -0.25 -0.24 -0.23 -0.22
[10] -0.21 -0.20 -0.19 -0.18 -0.17 -0.16 -0.15 -0.14 -0.13
[19] -0.12 -0.11 -0.10 -0.09 -0.08 -0.07 -0.06 -0.05 -0.04
[28] -0.03 -0.02 -0.01  0.00  0.01  0.02  0.03  0.04  0.05
[37]  0.06  0.07  0.08  0.09  0.10</code></pre>
</div>
</div>
</section>
<section id="try-2" class="level2">
<h2 class="anchored" data-anchor-id="try-2">Try 2</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxcox</span>(timedrs <span class="sc">+</span> <span class="dv">1</span> <span class="sc">~</span> phyheal <span class="sc">+</span> menheal <span class="sc">+</span> stress,</span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">lambda =</span> my.lambda,</span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> visits</span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="regression_files/figure-html/bRegression-38-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="comments-4" class="level2">
<h2 class="anchored" data-anchor-id="comments-4">Comments</h2>
<ul>
<li><p>Best: <span class="math inline">\(\lambda\)</span> just about <span class="math inline">\(-0.07\)</span>.</p></li>
<li><p>CI for <span class="math inline">\(\lambda\)</span> about <span class="math inline">\((-0.14,0.01)\)</span>.</p></li>
<li><p>Only nearby round number: <span class="math inline">\(\lambda=0\)</span>, log transformation.</p></li>
</ul>
</section>
<section id="fixing-the-problems" class="level2">
<h2 class="anchored" data-anchor-id="fixing-the-problems">Fixing the problems</h2>
<ul>
<li><p>Try regression again, with transformed response instead of original one.</p></li>
<li><p>Then check residual plot to see that it is OK now.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>visits<span class="fl">.3</span> <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(timedrs <span class="sc">+</span> <span class="dv">1</span>) <span class="sc">~</span> phyheal <span class="sc">+</span> menheal <span class="sc">+</span> stress,</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> visits</span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><p><code>timedrs+1</code> because some <code>timedrs</code> values 0, can’t take log of 0.</p></li>
<li><p>Won’t usually need to worry about this, but when response could be zero/negative, fix that before transformation.</p></li>
</ul>
</section>
<section id="output" class="level2">
<h2 class="anchored" data-anchor-id="output">Output</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(visits<span class="fl">.3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(timedrs + 1) ~ phyheal + menheal + stress, data = visits)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.95865 -0.44076 -0.02331  0.42304  2.36797 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 0.3903862  0.0882908   4.422 1.22e-05 ***
phyheal     0.2019361  0.0173624  11.631  &lt; 2e-16 ***
menheal     0.0071442  0.0101335   0.705    0.481    
stress      0.0013158  0.0002837   4.638 4.58e-06 ***
---
Signif. codes:  
0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.7625 on 461 degrees of freedom
Multiple R-squared:  0.3682,    Adjusted R-squared:  0.3641 
F-statistic: 89.56 on 3 and 461 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="comments-5" class="level2">
<h2 class="anchored" data-anchor-id="comments-5">Comments</h2>
<ul>
<li><p>Model as a whole strongly significant again</p></li>
<li><p>R-sq higher than before (37% vs.&nbsp;22%) suggesting things more linear now</p></li>
<li><p>Same conclusion re <code>menheal</code>: can take out of regression.</p></li>
<li><p>Should look at residual plots (next pages). Have we fixed problems?</p></li>
</ul>
</section>
<section id="residuals-against-fitted-values" class="level2">
<h2 class="anchored" data-anchor-id="residuals-against-fitted-values">Residuals against fitted values</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(visits<span class="fl">.3</span>, <span class="fu">aes</span>(<span class="at">x =</span> .fitted, <span class="at">y =</span> .resid)) <span class="sc">+</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="regression_files/figure-html/bRegression-41-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="normal-quantile-plot-of-residuals-1" class="level2">
<h2 class="anchored" data-anchor-id="normal-quantile-plot-of-residuals-1">Normal quantile plot of residuals</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(visits<span class="fl">.3</span>, <span class="fu">aes</span>(<span class="at">sample =</span> .resid)) <span class="sc">+</span> <span class="fu">stat_qq</span>() <span class="sc">+</span> <span class="fu">stat_qq_line</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="regression_files/figure-html/bRegression-42-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="absolute-residuals-against-fitted" class="level2">
<h2 class="anchored" data-anchor-id="absolute-residuals-against-fitted">Absolute residuals against fitted</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(visits<span class="fl">.3</span>, <span class="fu">aes</span>(<span class="at">x =</span> .fitted, <span class="at">y =</span> <span class="fu">abs</span>(.resid))) <span class="sc">+</span></span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_smooth</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="regression_files/figure-html/bRegression-43-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="comments-6" class="level2">
<h2 class="anchored" data-anchor-id="comments-6">Comments</h2>
<ul>
<li><p>Residuals vs.&nbsp;fitted looks a lot more random.</p></li>
<li><p>Normal quantile plot looks a lot more normal (though still a little right-skewness)</p></li>
<li><p>Absolute residuals: not so much trend (though still some).</p></li>
<li><p>Not perfect, but much improved.</p></li>
</ul>
</section>
<section id="testing-more-than-one-x-at-once" class="level2">
<h2 class="anchored" data-anchor-id="testing-more-than-one-x-at-once">Testing more than one <span class="math inline">\(x\)</span> at once</h2>
<ul>
<li>The <span class="math inline">\(t\)</span>-tests test only whether one variable could be taken out of the regression you’re looking at.</li>
<li>To test significance of more than one variable at once, fit model with and without variables
<ul>
<li>then use <code>anova</code> to compare fit of models:</li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>visits<span class="fl">.5</span> <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(timedrs <span class="sc">+</span> <span class="dv">1</span>) <span class="sc">~</span> phyheal <span class="sc">+</span> menheal <span class="sc">+</span> stress, </span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> visits)</span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a>visits<span class="fl">.6</span> <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(timedrs <span class="sc">+</span> <span class="dv">1</span>) <span class="sc">~</span> stress, <span class="at">data =</span> visits)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="results-of-tests" class="level2">
<h2 class="anchored" data-anchor-id="results-of-tests">Results of tests</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(visits<span class="fl">.6</span>, visits<span class="fl">.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: log(timedrs + 1) ~ stress
Model 2: log(timedrs + 1) ~ phyheal + menheal + stress
  Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
1    463 371.47                                  
2    461 268.01  2    103.46 88.984 &lt; 2.2e-16 ***
---
Signif. codes:  
0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<ul>
<li><p>Models don’t fit equally well, so bigger one fits better.</p></li>
<li><p>Or “taking both variables out makes the fit worse, so don’t do it”.</p></li>
<li><p>Taking out those <span class="math inline">\(x\)</span>’s is a mistake. Or putting them in is a good idea.</p></li>
</ul>
</section>
<section id="the-punting-data" class="level2">
<h2 class="anchored" data-anchor-id="the-punting-data">The punting data</h2>
<p>Data set <code>punting.txt</code> contains 4 variables for 13 right-footed football kickers (punters): left leg and right leg strength (lbs), distance punted (ft), another variable called “fred”. Predict punting distance from other variables:</p>
<pre><code>left            right               punt         fred
170               170                162.50       171 
130               140                144.0        136   
170               180                174.50       174 
160               160                163.50       161 
150               170                192.0        159 
150               150                171.75       151 
180               170                162.0        174 
110               110                104.83       111 
110               120                105.67       114 
120               130                117.58       126 
140               120                140.25       129  
130               140                150.17       136 
150               160                165.17       154 
</code></pre>
</section>
<section id="reading-in" class="level2">
<h2 class="anchored" data-anchor-id="reading-in">Reading in</h2>
<ul>
<li>Separated by <em>multiple spaces</em> with <em>columns lined up</em>:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>my_url <span class="ot">&lt;-</span> <span class="st">"http://ritsokiguess.site/datafiles/punting.txt"</span></span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>punting <span class="ot">&lt;-</span> <span class="fu">read_table</span>(my_url)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
── Column specification ────────────────────────────────────
cols(
  left = col_double(),
  right = col_double(),
  punt = col_double(),
  fred = col_double()
)</code></pre>
</div>
</div>
</section>
<section id="the-data-1" class="level2">
<h2 class="anchored" data-anchor-id="the-data-1">The data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>punting</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 13 × 4
    left right  punt  fred
   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
 1   170   170  162.   171
 2   130   140  144    136
 3   170   180  174.   174
 4   160   160  164.   161
 5   150   170  192    159
 6   150   150  172.   151
 7   180   170  162    174
 8   110   110  105.   111
 9   110   120  106.   114
10   120   130  118.   126
11   140   120  140.   129
12   130   140  150.   136
13   150   160  165.   154</code></pre>
</div>
</div>
</section>
<section id="regression-and-output" class="level2">
<h2 class="anchored" data-anchor-id="regression-and-output">Regression and output</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>punting<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">lm</span>(punt <span class="sc">~</span> left <span class="sc">+</span> right <span class="sc">+</span> fred, <span class="at">data =</span> punting)</span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(punting<span class="fl">.1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squared sigma statistic p.value    df
      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
1     0.778         0.704  14.7      10.5 0.00267     3
# ℹ 6 more variables: logLik &lt;dbl&gt;, AIC &lt;dbl&gt;, BIC &lt;dbl&gt;,
#   deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(punting<span class="fl">.1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
  term        estimate std.error statistic p.value
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
1 (Intercept)   -4.69      29.1    -0.161    0.876
2 left           0.268      2.11    0.127    0.902
3 right          1.05       2.15    0.490    0.636
4 fred          -0.267      4.23   -0.0632   0.951</code></pre>
</div>
</div>
</section>
<section id="comments-7" class="level2">
<h2 class="anchored" data-anchor-id="comments-7">Comments</h2>
<ul>
<li><p>Overall regression strongly significant, R-sq high.</p></li>
<li><p>None of the <span class="math inline">\(x\)</span>’s significant! Why?</p></li>
<li><p><span class="math inline">\(t\)</span>-tests only say that you could take any one of the <span class="math inline">\(x\)</span>’s out without damaging the fit; doesn’t matter which one.</p></li>
<li><p>Explanation: look at <em>correlations</em>.</p></li>
</ul>
</section>
<section id="the-correlations" class="level2">
<h2 class="anchored" data-anchor-id="the-correlations">The correlations</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(punting)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           left     right      punt      fred
left  1.0000000 0.8957224 0.8117368 0.9722632
right 0.8957224 1.0000000 0.8805469 0.9728784
punt  0.8117368 0.8805469 1.0000000 0.8679507
fred  0.9722632 0.9728784 0.8679507 1.0000000</code></pre>
</div>
</div>
<ul>
<li><p><em>All</em> correlations are high: <span class="math inline">\(x\)</span>’s with <code>punt</code> (good) and with each other (bad, at least confusing).</p></li>
<li><p>What to do? Probably do just as well to pick one variable, say <code>right</code> since kickers are right-footed.</p></li>
</ul>
</section>
<section id="just-right" class="level2">
<h2 class="anchored" data-anchor-id="just-right">Just <code>right</code></h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a>punting<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">lm</span>(punt <span class="sc">~</span> right, <span class="at">data =</span> punting)</span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(punting<span class="fl">.2</span>, punting<span class="fl">.1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: punt ~ right
Model 2: punt ~ left + right + fred
  Res.Df    RSS Df Sum of Sq      F Pr(&gt;F)
1     11 1962.5                           
2      9 1938.2  2    24.263 0.0563 0.9456</code></pre>
</div>
</div>
<p>No significant loss by dropping other two variables.</p>
</section>
<section id="comparing-r-squareds" class="level2">
<h2 class="anchored" data-anchor-id="comparing-r-squareds">Comparing R-squareds</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(punting<span class="fl">.1</span>)<span class="sc">$</span>r.squared</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7781401</code></pre>
</div>
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(punting<span class="fl">.2</span>)<span class="sc">$</span>r.squared</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7753629</code></pre>
</div>
</div>
<p>Basically no difference. In regression (over), <code>right</code> significant:</p>
</section>
<section id="regression-results" class="level2">
<h2 class="anchored" data-anchor-id="regression-results">Regression results</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(punting<span class="fl">.2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term        estimate std.error statistic   p.value
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)    -3.69    25.3      -0.146 0.886    
2 right           1.04     0.169     6.16  0.0000709</code></pre>
</div>
</div>
</section>
<section id="but" class="level2">
<h2 class="anchored" data-anchor-id="but">But</h2>
<ul>
<li><p>Maybe we got the <em>form</em> of the relationship with <code>left</code> wrong.</p></li>
<li><p>Check: plot <em>residuals</em> from previous regression (without <code>left</code>) against <code>left</code>.</p></li>
<li><p>Residuals here are “punting distance adjusted for right leg strength”.</p></li>
<li><p>If there is some kind of relationship with <code>left</code>, we should include in model.</p></li>
<li><p>Plot of residuals against original variable: <code>augment</code> from <code>broom</code>.</p></li>
</ul>
</section>
<section id="augmenting-punting.2" class="level2">
<h2 class="anchored" data-anchor-id="augmenting-punting.2">Augmenting <code>punting.2</code></h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a>punting<span class="fl">.2</span> <span class="sc">%&gt;%</span> <span class="fu">augment</span>(punting) <span class="ot">-&gt;</span> punting.<span class="fl">2.</span>aug</span>
<span id="cb102-2"><a href="#cb102-2" aria-hidden="true" tabindex="-1"></a>punting.<span class="fl">2.</span>aug </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 13 × 10
    left right  punt  fred .fitted  .resid   .hat .sigma
   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
 1   170   170  162.   171    174. -11.1   0.157    13.5
 2   130   140  144    136    142.   1.72  0.0864   14.0
 3   170   180  174.   174    184.  -9.49  0.244    13.6
 4   160   160  164.   161    163.   0.366 0.101    14.0
 5   150   170  192    159    174.  18.4   0.157    12.5
 6   150   150  172.   151    153.  19.0   0.0778   12.5
 7   180   170  162    174    174. -11.6   0.157    13.4
 8   110   110  105.   111    111.  -6.17  0.305    13.8
 9   110   120  106.   114    121. -15.8   0.2      12.9
10   120   130  118.   126    132. -14.3   0.127    13.1
11   140   120  140.   129    121.  18.8   0.2      12.3
12   130   140  150.   136    142.   7.89  0.0864   13.8
13   150   160  165.   154    163.   2.04  0.101    14.0
# ℹ 2 more variables: .cooksd &lt;dbl&gt;, .std.resid &lt;dbl&gt;</code></pre>
</div>
</div>
</section>
<section id="residuals-against-left" class="level2">
<h2 class="anchored" data-anchor-id="residuals-against-left">Residuals against <code>left</code></h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(punting.<span class="fl">2.</span>aug, <span class="fu">aes</span>(<span class="at">x =</span> left, <span class="at">y =</span> .resid)) <span class="sc">+</span></span>
<span id="cb104-2"><a href="#cb104-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="regression_files/figure-html/basingstoke-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="comments-8" class="level2">
<h2 class="anchored" data-anchor-id="comments-8">Comments</h2>
<ul>
<li><p>There is a <em>curved</em> relationship with <code>left</code>.</p></li>
<li><p>We should add <code>left</code>-squared to the regression (and therefore put <code>left</code> back in when we do that):</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a>punting<span class="fl">.3</span> <span class="ot">&lt;-</span> <span class="fu">lm</span>(punt <span class="sc">~</span> left <span class="sc">+</span> <span class="fu">I</span>(left<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> right,</span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> punting</span>
<span id="cb105-3"><a href="#cb105-3" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="regression-with-left-squared" class="level2">
<h2 class="anchored" data-anchor-id="regression-with-left-squared">Regression with <code>left-squared</code></h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(punting<span class="fl">.3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = punt ~ left + I(left^2) + right, data = punting)

Residuals:
     Min       1Q   Median       3Q      Max 
-11.3777  -5.3599   0.0459   4.5088  13.2669 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept) -4.623e+02  9.902e+01  -4.669  0.00117 **
left         6.888e+00  1.462e+00   4.710  0.00110 **
I(left^2)   -2.302e-02  4.927e-03  -4.672  0.00117 **
right        7.396e-01  2.292e-01   3.227  0.01038 * 
---
Signif. codes:  
0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.931 on 9 degrees of freedom
Multiple R-squared:  0.9352,    Adjusted R-squared:  0.9136 
F-statistic:  43.3 on 3 and 9 DF,  p-value: 1.13e-05</code></pre>
</div>
</div>
</section>
<section id="comments-9" class="level2">
<h2 class="anchored" data-anchor-id="comments-9">Comments</h2>
<ul>
<li><p>This was definitely a good idea (R-squared has clearly increased).</p></li>
<li><p>We would never have seen it without plotting residuals from <code>punting.2</code> (without <code>left</code>) against <code>left</code>.</p></li>
<li><p>Negative slope for <code>leftsq</code> means that increased left-leg strength only increases punting distance up to a point: beyond that, it decreases again.</p></li>
</ul>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>