{
  "hash": "7796e10c84b03eb19ff8373ba754dc3d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Regression with categorical variables\"\neditor: \n  markdown: \n    wrap: 72\n---\n\n## Packages for this section\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(broom)\n```\n:::\n\n\n## The pigs revisited\n\n\n::: {.cell}\n\n:::\n\n\n-   Recall pig feed data, after we tidied it: \n\n\\small\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_url <- \"http://ritsokiguess.site/datafiles/pigs2.txt\"\npigs <- read_delim(my_url, \" \")\npigs \n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"pig\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"feed\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"weight\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"1\",\"2\":\"feed1\",\"3\":\"60.8\"},{\"1\":\"2\",\"2\":\"feed1\",\"3\":\"57.0\"},{\"1\":\"3\",\"2\":\"feed1\",\"3\":\"65.0\"},{\"1\":\"4\",\"2\":\"feed1\",\"3\":\"58.6\"},{\"1\":\"5\",\"2\":\"feed1\",\"3\":\"61.7\"},{\"1\":\"1\",\"2\":\"feed2\",\"3\":\"68.7\"},{\"1\":\"2\",\"2\":\"feed2\",\"3\":\"67.7\"},{\"1\":\"3\",\"2\":\"feed2\",\"3\":\"74.0\"},{\"1\":\"4\",\"2\":\"feed2\",\"3\":\"66.3\"},{\"1\":\"5\",\"2\":\"feed2\",\"3\":\"69.8\"},{\"1\":\"1\",\"2\":\"feed3\",\"3\":\"92.6\"},{\"1\":\"2\",\"2\":\"feed3\",\"3\":\"92.1\"},{\"1\":\"3\",\"2\":\"feed3\",\"3\":\"90.2\"},{\"1\":\"4\",\"2\":\"feed3\",\"3\":\"96.5\"},{\"1\":\"5\",\"2\":\"feed3\",\"3\":\"99.1\"},{\"1\":\"1\",\"2\":\"feed4\",\"3\":\"87.9\"},{\"1\":\"2\",\"2\":\"feed4\",\"3\":\"84.2\"},{\"1\":\"3\",\"2\":\"feed4\",\"3\":\"83.1\"},{\"1\":\"4\",\"2\":\"feed4\",\"3\":\"85.7\"},{\"1\":\"5\",\"2\":\"feed4\",\"3\":\"90.3\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\\normalsize\n\n## Summaries\n\n\n::: {.cell}\n\n```{.r .cell-code}\npigs %>%\n  group_by(feed) %>%\n  summarize(n = n(), mean_wt = mean(weight), \n            sd_wt = sd(weight))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"feed\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"n\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"mean_wt\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"sd_wt\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"feed1\",\"2\":\"5\",\"3\":\"60.62\",\"4\":\"3.064637\"},{\"1\":\"feed2\",\"2\":\"5\",\"3\":\"69.30\",\"4\":\"2.926602\"},{\"1\":\"feed3\",\"2\":\"5\",\"3\":\"94.10\",\"4\":\"3.613170\"},{\"1\":\"feed4\",\"2\":\"5\",\"3\":\"86.24\",\"4\":\"2.896204\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n## Running through `aov` and `lm`\n\n-   What happens if we run this through `lm` rather than `aov`?\n-   Recall `aov` first:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npigs.1 <- aov(weight ~ feed, data = pigs)\nsummary(pigs.1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value   Pr(>F)    \nfeed         3   3521  1173.5   119.1 3.72e-11 ***\nResiduals   16    158     9.9                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n## and now `lm`\n\n\\footnotesize\n\n\n::: {.cell}\n\n```{.r .cell-code}\npigs.2 <- lm(weight ~ feed, data = pigs)\nsummary(pigs.2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = weight ~ feed, data = pigs)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-3.900 -2.025 -0.570  1.845  5.000 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   60.620      1.404  43.190  < 2e-16 ***\nfeedfeed2      8.680      1.985   4.373 0.000473 ***\nfeedfeed3     33.480      1.985  16.867 1.30e-11 ***\nfeedfeed4     25.620      1.985  12.907 7.11e-10 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.138 on 16 degrees of freedom\nMultiple R-squared:  0.9572,\tAdjusted R-squared:  0.9491 \nF-statistic: 119.1 on 3 and 16 DF,  p-value: 3.72e-11\n```\n\n\n:::\n\n```{.r .cell-code}\ntidy(pigs.2)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"term\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"estimate\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"std.error\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"statistic\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"p.value\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"(Intercept)\",\"2\":\"60.62\",\"3\":\"1.403567\",\"4\":\"43.189962\",\"5\":\"5.393957e-18\"},{\"1\":\"feedfeed2\",\"2\":\"8.68\",\"3\":\"1.984943\",\"4\":\"4.372921\",\"5\":\"4.731212e-04\"},{\"1\":\"feedfeed3\",\"2\":\"33.48\",\"3\":\"1.984943\",\"4\":\"16.866980\",\"5\":\"1.299852e-11\"},{\"1\":\"feedfeed4\",\"2\":\"25.62\",\"3\":\"1.984943\",\"4\":\"12.907170\",\"5\":\"7.108367e-10\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nglance(pigs.2)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"r.squared\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"adj.r.squared\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"sigma\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"statistic\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"p.value\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"df\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"logLik\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"AIC\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"BIC\"],\"name\":[9],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"deviance\"],\"name\":[10],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"df.residual\"],\"name\":[11],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"nobs\"],\"name\":[12],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"0.9571521\",\"2\":\"0.9491181\",\"3\":\"3.138471\",\"4\":\"119.1379\",\"5\":\"3.720075e-11\",\"6\":\"3\",\"7\":\"-49.02205\",\"8\":\"108.0441\",\"9\":\"113.0228\",\"10\":\"157.6\",\"11\":\"16\",\"12\":\"20\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\\normalsize\n\n## Understanding those slopes {.scrollable}\n\n-   Get one slope for each category of categorical variable feed, except\n    for first.\n-   feed1 treated as \"baseline\", others measured relative to that.\n-   Thus prediction for feed 1 is intercept, 60.62 (mean weight for feed\n    1).\n-   Prediction for feed 2 is 60.62 + 8.68 = 69.30 (mean weight for feed\n    2).\n-   Or, mean weight for feed 2 is 8.68 bigger than for feed 1.\n-   Mean weight for feed 3 is 33.48 bigger than for feed 1.\n-   Slopes can be negative, if mean for a feed had been smaller than for\n    feed 1.\n\n## Reproducing the ANOVA\n\n-   Pass the fitted model object into `anova`:\n\n\\footnotesize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(pigs.2)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Df\"],\"name\":[1],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Sum Sq\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Mean Sq\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"F value\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>F)\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"3\",\"2\":\"3520.525\",\"3\":\"1173.508\",\"4\":\"119.1379\",\"5\":\"3.720075e-11\",\"_rn_\":\"feed\"},{\"1\":\"16\",\"2\":\"157.600\",\"3\":\"9.850\",\"4\":\"NA\",\"5\":\"NA\",\"_rn_\":\"Residuals\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\\normalsize\n\n-   Same as before.\n-   But no Tukey this way:\n\n\\scriptsize \n\n\n::: {.cell}\n\n```{.r .cell-code}\nTukeyHSD(pigs.2)\n```\n\n::: {.cell-output .cell-output-error}\n\n```\nError in UseMethod(\"TukeyHSD\"): no applicable method for 'TukeyHSD' applied to an object of class \"lm\"\n```\n\n\n:::\n:::\n\n\n\\normalsize\n\n## The crickets\n\n-   Male crickets rub their wings together to produce a chirping sound.\n-   Rate of chirping, called \"pulse rate\", depends on species and\n    possibly on temperature.\n-   Sample of crickets of two species' pulse rates measured; temperature\n    also recorded.\n-   Does pulse rate differ for species, especially when temperature\n    accounted for?\n\n## The crickets data\n\nRead the data:\n\n\\footnotesize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_url <- \"http://ritsokiguess.site/datafiles/crickets2.csv\"\ncrickets <- read_csv(my_url)\ncrickets %>% slice_sample(n = 10) # display sample of rows\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"species\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"temperature\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"pulse_rate\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"exclamationis\",\"2\":\"24.0\",\"3\":\"80.4\"},{\"1\":\"niveus\",\"2\":\"21.0\",\"3\":\"58.5\"},{\"1\":\"niveus\",\"2\":\"21.0\",\"3\":\"58.9\"},{\"1\":\"exclamationis\",\"2\":\"20.8\",\"3\":\"65.1\"},{\"1\":\"niveus\",\"2\":\"17.2\",\"3\":\"44.3\"},{\"1\":\"niveus\",\"2\":\"18.3\",\"3\":\"49.6\"},{\"1\":\"exclamationis\",\"2\":\"26.2\",\"3\":\"87.5\"},{\"1\":\"niveus\",\"2\":\"25.9\",\"3\":\"76.2\"},{\"1\":\"niveus\",\"2\":\"20.4\",\"3\":\"60.0\"},{\"1\":\"exclamationis\",\"2\":\"26.2\",\"3\":\"85.8\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\\normalsize\n\n## Fit model with `lm`\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrickets.1 <- lm(pulse_rate ~ temperature + species, \n                 data = crickets)\n```\n:::\n\n\n## Can I remove anything? No:\n\n\\small\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndrop1(crickets.1, test = \"F\") \n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Df\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Sum of Sq\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"RSS\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"AIC\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"F value\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>F)\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"NA\",\"2\":\"NA\",\"3\":\"89.34987\",\"4\":\"38.81575\",\"5\":\"NA\",\"6\":\"NA\",\"_rn_\":\"<none>\"},{\"1\":\"1\",\"2\":\"4376.083\",\"3\":\"4465.43244\",\"4\":\"158.07416\",\"5\":\"1371.3541\",\"6\":\"2.487732e-25\",\"_rn_\":\"temperature\"},{\"1\":\"1\",\"2\":\"598.004\",\"3\":\"687.35382\",\"4\":\"100.06472\",\"5\":\"187.3994\",\"6\":\"6.271533e-14\",\"_rn_\":\"species\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\\normalsize\n\n`drop1` is right thing to use in a regression with categorical\n(explanatory) variables in it: \"can I remove this categorical variable\n*as a whole*?\"\n\n## The summary\n\n\\footnotesize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(crickets.1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = pulse_rate ~ temperature + species, data = crickets)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.0128 -1.1296 -0.3912  0.9650  3.7800 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    -7.21091    2.55094  -2.827  0.00858 ** \ntemperature     3.60275    0.09729  37.032  < 2e-16 ***\nspeciesniveus -10.06529    0.73526 -13.689 6.27e-14 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.786 on 28 degrees of freedom\nMultiple R-squared:  0.9896,\tAdjusted R-squared:  0.9888 \nF-statistic:  1331 on 2 and 28 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\\normalsize\n\n## Conclusions\n\n-   Slope for temperature says that increasing temperature by 1 degree\n    increases pulse rate by 3.6 (same for both species)\n-   Slope for `speciesniveus` says that pulse rate for `niveus` about 10\n    lower than that for `exclamationis` at same temperature (latter\n    species is baseline).\n-   R-squared of almost 0.99 is very high, so that the prediction of\n    pulse rate from species and temperature is very good.\n\n## What this model is doing: a graph \n\n-   Two quantitative variables and one categorical: scatterplot with\n    categories distinguished by colour.\n-   This graph seems to need a title, which I define first.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt1 <- \"Pulse rate against temperature for two species of crickets\"\nt2 <- \"Temperature in degrees Celsius\"\nggplot(crickets, aes(x = temperature, y = pulse_rate,\n  colour = species)) +\n  geom_point() + geom_smooth(method = \"lm\", se = FALSE) +\n  ggtitle(t1, subtitle = t2) -> g\n```\n:::\n\n\n## The graph\n\n\n::: {.cell}\n\n```{.r .cell-code}\ng\n```\n\n::: {.cell-output-display}\n![](with_categ_files/figure-revealjs/unnamed-chunk-1-1.png){width=960}\n:::\n:::\n\n    \n## Residuals\n\n- We can also check residuals from this kind of model:\n\n\\small\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrickets.1a <- augment(crickets.1)\ncrickets.1a\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"pulse_rate\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"temperature\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"species\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\".fitted\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\".resid\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\".hat\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\".sigma\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\".cooksd\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\".std.resid\"],\"name\":[9],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"67.9\",\"2\":\"20.8\",\"3\":\"exclamationis\",\"4\":\"67.72635\",\"5\":\"0.1736464\",\"6\":\"0.14431494\",\"7\":\"1.818777\",\"8\":\"0.0006208087\",\"9\":\"0.10508503\"},{\"1\":\"65.1\",\"2\":\"20.8\",\"3\":\"exclamationis\",\"4\":\"67.72635\",\"5\":\"-2.6263536\",\"6\":\"0.14431494\",\"7\":\"1.735136\",\"8\":\"0.1420144860\",\"9\":\"-1.58938196\"},{\"1\":\"77.3\",\"2\":\"24.0\",\"3\":\"exclamationis\",\"4\":\"79.25516\",\"5\":\"-1.9551628\",\"6\":\"0.08058651\",\"7\":\"1.776307\",\"8\":\"0.0380670566\",\"9\":\"-1.14145698\"},{\"1\":\"78.7\",\"2\":\"24.0\",\"3\":\"exclamationis\",\"4\":\"79.25516\",\"5\":\"-0.5551628\",\"6\":\"0.08058651\",\"7\":\"1.815720\",\"8\":\"0.0030691928\",\"9\":\"-0.32411340\"},{\"1\":\"79.4\",\"2\":\"24.0\",\"3\":\"exclamationis\",\"4\":\"79.25516\",\"5\":\"0.1448372\",\"6\":\"0.08058651\",\"7\":\"1.818903\",\"8\":\"0.0002089025\",\"9\":\"0.08455839\"},{\"1\":\"80.4\",\"2\":\"24.0\",\"3\":\"exclamationis\",\"4\":\"79.25516\",\"5\":\"1.1448372\",\"6\":\"0.08058651\",\"7\":\"1.804566\",\"8\":\"0.0130518149\",\"9\":\"0.66837524\"},{\"1\":\"85.8\",\"2\":\"26.2\",\"3\":\"exclamationis\",\"4\":\"87.18122\",\"5\":\"-1.3812191\",\"6\":\"0.07201029\",\"7\":\"1.798086\",\"8\":\"0.0166638845\",\"9\":\"-0.80264418\"},{\"1\":\"86.6\",\"2\":\"26.2\",\"3\":\"exclamationis\",\"4\":\"87.18122\",\"5\":\"-0.5812191\",\"6\":\"0.07201029\",\"7\":\"1.815426\",\"8\":\"0.0029507395\",\"9\":\"-0.33775390\"},{\"1\":\"87.5\",\"2\":\"26.2\",\"3\":\"exclamationis\",\"4\":\"87.18122\",\"5\":\"0.3187809\",\"6\":\"0.07201029\",\"7\":\"1.818021\",\"8\":\"0.0008876374\",\"9\":\"0.18524766\"},{\"1\":\"89.1\",\"2\":\"26.2\",\"3\":\"exclamationis\",\"4\":\"87.18122\",\"5\":\"1.9187809\",\"6\":\"0.07201029\",\"7\":\"1.778289\",\"8\":\"0.0321589483\",\"9\":\"1.11502821\"},{\"1\":\"98.6\",\"2\":\"28.4\",\"3\":\"exclamationis\",\"4\":\"95.10728\",\"5\":\"3.4927245\",\"6\":\"0.09214576\",\"7\":\"1.676775\",\"8\":\"0.1424671164\",\"9\":\"2.05205185\"},{\"1\":\"100.8\",\"2\":\"29.0\",\"3\":\"exclamationis\",\"4\":\"97.26893\",\"5\":\"3.5310728\",\"6\":\"0.10262027\",\"7\":\"1.671721\",\"8\":\"0.1659727794\",\"9\":\"2.08665478\"},{\"1\":\"99.3\",\"2\":\"30.4\",\"3\":\"exclamationis\",\"4\":\"102.31278\",\"5\":\"-3.0127812\",\"6\":\"0.13536584\",\"7\":\"1.708930\",\"8\":\"0.1716810457\",\"9\":\"-1.81377518\"},{\"1\":\"101.7\",\"2\":\"30.4\",\"3\":\"exclamationis\",\"4\":\"102.31278\",\"5\":\"-0.6127812\",\"6\":\"0.13536584\",\"7\":\"1.814709\",\"8\":\"0.0071022840\",\"9\":\"-0.36891074\"},{\"1\":\"44.3\",\"2\":\"17.2\",\"3\":\"niveus\",\"4\":\"44.69115\",\"5\":\"-0.3911520\",\"6\":\"0.13072479\",\"7\":\"1.817343\",\"8\":\"0.0027648870\",\"9\":\"-0.23485456\"},{\"1\":\"47.2\",\"2\":\"18.3\",\"3\":\"niveus\",\"4\":\"48.65418\",\"5\":\"-1.4541802\",\"6\":\"0.10218583\",\"7\":\"1.794999\",\"8\":\"0.0280025168\",\"9\":\"-0.85912637\"},{\"1\":\"47.6\",\"2\":\"18.3\",\"3\":\"niveus\",\"4\":\"48.65418\",\"5\":\"-1.0541802\",\"6\":\"0.10218583\",\"7\":\"1.806491\",\"8\":\"0.0147160183\",\"9\":\"-0.62280728\"},{\"1\":\"49.6\",\"2\":\"18.3\",\"3\":\"niveus\",\"4\":\"48.65418\",\"5\":\"0.9458198\",\"6\":\"0.10218583\",\"7\":\"1.808964\",\"8\":\"0.0118461558\",\"9\":\"0.55878821\"},{\"1\":\"50.3\",\"2\":\"18.9\",\"3\":\"niveus\",\"4\":\"50.81583\",\"5\":\"-0.5158319\",\"6\":\"0.08964453\",\"7\":\"1.816158\",\"8\":\"0.0030064988\",\"9\":\"-0.30264587\"},{\"1\":\"51.8\",\"2\":\"18.9\",\"3\":\"niveus\",\"4\":\"50.81583\",\"5\":\"0.9841681\",\"6\":\"0.08964453\",\"7\":\"1.808272\",\"8\":\"0.0109441791\",\"9\":\"0.57742533\"},{\"1\":\"60.0\",\"2\":\"20.4\",\"3\":\"niveus\",\"4\":\"56.21996\",\"5\":\"3.7800388\",\"6\":\"0.06763444\",\"7\":\"1.655794\",\"8\":\"0.1161263639\",\"9\":\"2.19146834\"},{\"1\":\"58.5\",\"2\":\"21.0\",\"3\":\"niveus\",\"4\":\"58.38161\",\"5\":\"0.1183871\",\"6\":\"0.06256767\",\"7\":\"1.818983\",\"8\":\"0.0001042369\",\"9\":\"0.06844887\"},{\"1\":\"58.9\",\"2\":\"21.0\",\"3\":\"niveus\",\"4\":\"58.38161\",\"5\":\"0.5183871\",\"6\":\"0.06256767\",\"7\":\"1.816215\",\"8\":\"0.0019985789\",\"9\":\"0.29972036\"},{\"1\":\"60.7\",\"2\":\"22.1\",\"3\":\"niveus\",\"4\":\"62.34464\",\"5\":\"-1.6446411\",\"6\":\"0.05882517\",\"7\":\"1.789641\",\"8\":\"0.0187632358\",\"9\":\"-0.94900401\"},{\"1\":\"69.8\",\"2\":\"23.5\",\"3\":\"niveus\",\"4\":\"67.38850\",\"5\":\"2.4115049\",\"6\":\"0.06444328\",\"7\":\"1.754718\",\"8\":\"0.0447256399\",\"9\":\"1.39567770\"},{\"1\":\"70.9\",\"2\":\"24.2\",\"3\":\"niveus\",\"4\":\"69.91042\",\"5\":\"0.9895779\",\"6\":\"0.07161248\",\"7\":\"1.808366\",\"8\":\"0.0084991000\",\"9\":\"0.57493319\"},{\"1\":\"76.2\",\"2\":\"25.9\",\"3\":\"niveus\",\"4\":\"76.03510\",\"5\":\"0.1648980\",\"6\":\"0.10112502\",\"7\":\"1.818828\",\"8\":\"0.0003554950\",\"9\":\"0.09736384\"},{\"1\":\"76.1\",\"2\":\"26.5\",\"3\":\"niveus\",\"4\":\"78.19675\",\"5\":\"-2.0967538\",\"6\":\"0.11563440\",\"7\":\"1.767805\",\"8\":\"0.0678986442\",\"9\":\"-1.24814076\"},{\"1\":\"77.0\",\"2\":\"26.5\",\"3\":\"niveus\",\"4\":\"78.19675\",\"5\":\"-1.1967538\",\"6\":\"0.11563440\",\"7\":\"1.802574\",\"8\":\"0.0221195273\",\"9\":\"-0.71239512\"},{\"1\":\"77.7\",\"2\":\"26.5\",\"3\":\"niveus\",\"4\":\"78.19675\",\"5\":\"-0.4967538\",\"6\":\"0.11563440\",\"7\":\"1.816293\",\"8\":\"0.0038110844\",\"9\":\"-0.29570407\"},{\"1\":\"84.7\",\"2\":\"28.6\",\"3\":\"niveus\",\"4\":\"85.76253\",\"5\":\"-1.0625348\",\"6\":\"0.18323495\",\"7\":\"1.805010\",\"8\":\"0.0323924046\",\"9\":\"-0.65815266\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\\normalsize\n\nand then...\n\n## Residuals vs fitted\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(crickets.1a, aes(x = .fitted, y = .resid)) + \n  geom_point()\n```\n\n::: {.cell-output-display}\n![](with_categ_files/figure-revealjs/unnamed-chunk-3-1.png){width=960}\n:::\n:::\n\n\n## Normal quantile plot of residuals\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(crickets.1a, aes(sample = .resid)) + \n  stat_qq() + stat_qq_line()\n```\n\n::: {.cell-output-display}\n![](with_categ_files/figure-revealjs/unnamed-chunk-4-1.png){width=960}\n:::\n:::\n\n\n## Residuals vs. $x$'s\n\ndoesn't work as you expect:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrickets.1a %>% \n  pivot_longer(temperature:species, \n               names_to = \"xname\", values_to = \"xval\")\n```\n\n::: {.cell-output .cell-output-error}\n\n```\nError in `pivot_longer()`:\n! Can't combine `temperature` <double> and `species` <character>.\n```\n\n\n:::\n:::\n\n\n## so do them separately 1/3\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(crickets.1a, aes(x = temperature, y = .resid)) + \n  geom_point()\n```\n\n::: {.cell-output-display}\n![](with_categ_files/figure-revealjs/unnamed-chunk-6-1.png){width=960}\n:::\n:::\n\n\n## so do them separately 2/3\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(crickets.1a, aes(x = species, y = .resid)) + \n  geom_point()\n```\n\n::: {.cell-output-display}\n![](with_categ_files/figure-revealjs/unnamed-chunk-7-1.png){width=960}\n:::\n:::\n\n\n## so do them separately 3/3\n\nor perhaps better for categorical $x$'s\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(crickets.1a, aes(x = species, y = .resid)) + \n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](with_categ_files/figure-revealjs/unnamed-chunk-8-1.png){width=960}\n:::\n:::\n\n\n",
    "supporting": [
      "with_categ_files/figure-revealjs"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"with_categ_files/libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"with_categ_files/libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ],
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}