{
  "hash": "6d59330e1205cca45d7f8341b304ad82",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Regression with categorical variables\"\neditor: \n  markdown: \n    wrap: 72\n---\n\n\n\n\n## Packages for this section\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(broom)\n```\n:::\n\n\n\n\n## The pigs revisited\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n-   Recall pig feed data, after we tidied it:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_url <- \"http://ritsokiguess.site/datafiles/pigs2.txt\"\npigs <- read_delim(my_url, \" \")\npigs \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 20 x 3\n     pig feed  weight\n   <dbl> <chr>  <dbl>\n 1     1 feed1   60.8\n 2     2 feed1   57  \n 3     3 feed1   65  \n 4     4 feed1   58.6\n 5     5 feed1   61.7\n 6     1 feed2   68.7\n 7     2 feed2   67.7\n 8     3 feed2   74  \n 9     4 feed2   66.3\n10     5 feed2   69.8\n11     1 feed3   92.6\n12     2 feed3   92.1\n13     3 feed3   90.2\n14     4 feed3   96.5\n15     5 feed3   99.1\n16     1 feed4   87.9\n17     2 feed4   84.2\n18     3 feed4   83.1\n19     4 feed4   85.7\n20     5 feed4   90.3\n```\n\n\n:::\n:::\n\n\n\n\n## Summaries\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npigs %>%\n  group_by(feed) %>%\n  summarize(n = n(), mean_wt = mean(weight), \n            sd_wt = sd(weight))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 x 4\n  feed      n mean_wt sd_wt\n  <chr> <int>   <dbl> <dbl>\n1 feed1     5    60.6  3.06\n2 feed2     5    69.3  2.93\n3 feed3     5    94.1  3.61\n4 feed4     5    86.2  2.90\n```\n\n\n:::\n:::\n\n\n\n\n## Running through `aov` and `lm`\n\n-   What happens if we run this through `lm` rather than `aov`?\n-   Recall `aov` first:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npigs.1 <- aov(weight ~ feed, data = pigs)\nsummary(pigs.1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value   Pr(>F)    \nfeed         3   3521  1173.5   119.1 3.72e-11 ***\nResiduals   16    158     9.9                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\n## and now `lm`\n\n\\footnotesize\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npigs.2 <- lm(weight ~ feed, data = pigs)\nsummary(pigs.2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = weight ~ feed, data = pigs)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-3.900 -2.025 -0.570  1.845  5.000 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   60.620      1.404  43.190  < 2e-16 ***\nfeedfeed2      8.680      1.985   4.373 0.000473 ***\nfeedfeed3     33.480      1.985  16.867 1.30e-11 ***\nfeedfeed4     25.620      1.985  12.907 7.11e-10 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.138 on 16 degrees of freedom\nMultiple R-squared:  0.9572,\tAdjusted R-squared:  0.9491 \nF-statistic: 119.1 on 3 and 16 DF,  p-value: 3.72e-11\n```\n\n\n:::\n\n```{.r .cell-code}\ntidy(pigs.2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 x 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)    60.6       1.40     43.2  5.39e-18\n2 feedfeed2       8.68      1.98      4.37 4.73e- 4\n3 feedfeed3      33.5       1.98     16.9  1.30e-11\n4 feedfeed4      25.6       1.98     12.9  7.11e-10\n```\n\n\n:::\n\n```{.r .cell-code}\nglance(pigs.2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 x 12\n  r.squared adj.r.squared sigma statistic  p.value    df logLik   AIC   BIC\n      <dbl>         <dbl> <dbl>     <dbl>    <dbl> <dbl>  <dbl> <dbl> <dbl>\n1     0.957         0.949  3.14      119. 3.72e-11     3  -49.0  108.  113.\n# i 3 more variables: deviance <dbl>, df.residual <int>, nobs <int>\n```\n\n\n:::\n:::\n\n\n\n\n\\normalsize\n\n## Understanding those slopes {.scrollable}\n\n-   Get one slope for each category of categorical variable feed, except\n    for first.\n-   feed1 treated as \"baseline\", others measured relative to that.\n-   Thus prediction for feed 1 is intercept, 60.62 (mean weight for feed\n    1).\n-   Prediction for feed 2 is 60.62 + 8.68 = 69.30 (mean weight for feed\n    2).\n-   Or, mean weight for feed 2 is 8.68 bigger than for feed 1.\n-   Mean weight for feed 3 is 33.48 bigger than for feed 1.\n-   Slopes can be negative, if mean for a feed had been smaller than for\n    feed 1.\n\n## Reproducing the ANOVA\n\n-   Pass the fitted model object into `anova`:\n\n\\footnotesize\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(pigs.2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: weight\n          Df Sum Sq Mean Sq F value   Pr(>F)    \nfeed       3 3520.5 1173.51  119.14 3.72e-11 ***\nResiduals 16  157.6    9.85                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\n\\normalsize\n\n-   Same as before.\n-   But no Tukey this way:\n\n\\footnotesize\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTukeyHSD(pigs.2)\n```\n\n::: {.cell-output .cell-output-error}\n\n```\nError in UseMethod(\"TukeyHSD\"): no applicable method for 'TukeyHSD' applied to an object of class \"lm\"\n```\n\n\n:::\n:::\n\n\n\n\n\\normalsize\n\n## The crickets\n\n-   Male crickets rub their wings together to produce a chirping sound.\n-   Rate of chirping, called \"pulse rate\", depends on species and\n    possibly on temperature.\n-   Sample of crickets of two species' pulse rates measured; temperature\n    also recorded.\n-   Does pulse rate differ for species, especially when temperature\n    accounted for?\n\n## The crickets data\n\nRead the data:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_url <- \"http://ritsokiguess.site/datafiles/crickets2.csv\"\ncrickets <- read_csv(my_url)\ncrickets %>% slice_sample(n = 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 x 3\n   species       temperature pulse_rate\n   <chr>               <dbl>      <dbl>\n 1 niveus               18.3       49.6\n 2 exclamationis        26.2       89.1\n 3 niveus               18.9       50.3\n 4 niveus               23.5       69.8\n 5 niveus               18.3       47.2\n 6 niveus               26.5       77.7\n 7 exclamationis        26.2       87.5\n 8 niveus               21         58.9\n 9 exclamationis        30.4      102. \n10 exclamationis        24         77.3\n```\n\n\n:::\n:::\n\n\n\n\n## Fit model with `lm`\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrickets.1 <- lm(pulse_rate ~ temperature + species, \n                 data = crickets)\n```\n:::\n\n\n\n\nCan I remove anything? No:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndrop1(crickets.1, test = \"F\") \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSingle term deletions\n\nModel:\npulse_rate ~ temperature + species\n            Df Sum of Sq    RSS     AIC F value    Pr(>F)    \n<none>                     89.3  38.816                      \ntemperature  1    4376.1 4465.4 158.074  1371.4 < 2.2e-16 ***\nspecies      1     598.0  687.4 100.065   187.4 6.272e-14 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\n`drop1` is right thing to use in a regression with categorical\n(explanatory) variables in it: \"can I remove this categorical variable\n*as a whole*?\"\n\n## The summary\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(crickets.1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = pulse_rate ~ temperature + species, data = crickets)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.0128 -1.1296 -0.3912  0.9650  3.7800 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    -7.21091    2.55094  -2.827  0.00858 ** \ntemperature     3.60275    0.09729  37.032  < 2e-16 ***\nspeciesniveus -10.06529    0.73526 -13.689 6.27e-14 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.786 on 28 degrees of freedom\nMultiple R-squared:  0.9896,\tAdjusted R-squared:  0.9888 \nF-statistic:  1331 on 2 and 28 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\n## Conclusions\n\n-   Slope for temperature says that increasing temperature by 1 degree\n    increases pulse rate by 3.6 (same for both species)\n-   Slope for `speciesniveus` says that pulse rate for `niveus` about 10\n    lower than that for `exclamationis` at same temperature (latter\n    species is baseline).\n-   R-squared of almost 0.99 is very high, so that the prediction of\n    pulse rate from species and temperature is very good.\n\n## To end with a graph\n\n-   Two quantitative variables and one categorical: scatterplot with\n    categories distinguished by colour.\n-   This graph seems to need a title, which I define first.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt1 <- \"Pulse rate against temperature for two species of crickets\"\nt2 <- \"Temperature in degrees Celsius\"\nggplot(crickets, aes(x = temperature, y = pulse_rate,\n  colour = species)) +\n  geom_point() + geom_smooth(method = \"lm\", se = FALSE) +\n  ggtitle(t1, t2) -> g\n```\n:::\n\n\n\n\n## The graph\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ng\n```\n\n::: {.cell-output-display}\n![](with_categ_files/figure-beamer/unnamed-chunk-1-1.pdf){fig-pos='H'}\n:::\n:::\n",
    "supporting": [
      "with_categ_files/figure-beamer"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}