{
  "hash": "ddffe41007b9d7bdcd7477b79676b3f8",
  "result": {
    "markdown": "---\ntitle: \"Multiway Frequency Tables\"\n---\n\n\n## Packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse )\n```\n:::\n\n\n## Multi-way frequency analysis\n\n-   A study of gender and eyewear-wearing finds the following\n    frequencies:\n      \n```         \ngender contacts glasses none\nfemale 121      32      129\nmale   42       37      85\n```\n\n-   Is there association between eyewear and gender?\n\n-   Normally answer this with chisquare test (based on observed and\n    expected frequencies from null hypothesis of no association).\n\n-   Two categorical variables and a frequency.\n\n-   We assess in way that generalizes to more categorical variables.\n\n## The data file\n\n```         \ngender contacts glasses none\nfemale 121      32      129\nmale   42       37      85\n```\n\n-   This is *not tidy!*\n\n-   Two variables are gender and *eyewear*, and those numbers all\n    frequencies.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_url <- \"http://ritsokiguess.site/datafiles/eyewear.txt\"\n(eyewear <- read_delim(my_url, \" \"))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"gender\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"contacts\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"glasses\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"none\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"female\",\"2\":\"121\",\"3\":\"32\",\"4\":\"129\"},{\"1\":\"male\",\"2\":\"42\",\"3\":\"37\",\"4\":\"85\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n## Tidying the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\neyewear %>%\n  pivot_longer(contacts:none, names_to=\"eyewear\", \n               values_to=\"frequency\") -> eyes\neyes\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"gender\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"eyewear\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"frequency\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"female\",\"2\":\"contacts\",\"3\":\"121\"},{\"1\":\"female\",\"2\":\"glasses\",\"3\":\"32\"},{\"1\":\"female\",\"2\":\"none\",\"3\":\"129\"},{\"1\":\"male\",\"2\":\"contacts\",\"3\":\"42\"},{\"1\":\"male\",\"2\":\"glasses\",\"3\":\"37\"},{\"1\":\"male\",\"2\":\"none\",\"3\":\"85\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n## Making tidy data back into a table\n\n-   use `pivot_wider`\n-   or this (we use it again later):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxt <- xtabs(frequency ~ gender + eyewear, data = eyes)\nxt\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        eyewear\ngender   contacts glasses none\n  female      121      32  129\n  male         42      37   85\n```\n:::\n:::\n\n\n## Modelling\n\n-   Predict frequency from other factors and combos.\n-   `glm` with `poisson` family.\n\n\n::: {.cell}\n\n```{.r .cell-code}\neyes.1 <- glm(frequency ~ gender * eyewear,\n  data = eyes,\n  family = \"poisson\"\n)\n```\n:::\n\n\n-   Called **log-linear model**.\n\n## What can we get rid of?\n\n\\small\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndrop1(eyes.1, test = \"Chisq\")\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Df\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Deviance\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"AIC\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"LRT\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>Chi)\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"NA\",\"2\":\"7.549517e-15\",\"3\":\"47.95815\",\"4\":\"NA\",\"5\":\"NA\",\"_rn_\":\"<none>\"},{\"1\":\"2\",\"2\":\"1.782863e+01\",\"3\":\"61.78678\",\"4\":\"17.82863\",\"5\":\"0.0001344505\",\"_rn_\":\"gender:eyewear\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nnothing!\n\n## Conclusions\n\n-   `drop1` says what we can remove at this step. Significant = must\n    stay.\n\n-   Cannot remove anything.\n\n-   Frequency depends on `gender-wear` *combination*, cannot be\n    simplified further.\n\n-   Gender and eyewear are *associated*.\n\n-   Stop here.\n\n## `prop.table`\n\nOriginal table:\n\n\\footnotesize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxt\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        eyewear\ngender   contacts glasses none\n  female      121      32  129\n  male         42      37   85\n```\n:::\n:::\n\n\n\\normalsize\n\nCalculate eg. row proportions like this:\n\n\\small\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.table(xt, margin = 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        eyewear\ngender    contacts   glasses      none\n  female 0.4290780 0.1134752 0.4574468\n  male   0.2560976 0.2256098 0.5182927\n```\n:::\n:::\n\n\n\\normalsize\n\n## Comments\n\n-   `margin` says what to make add to 1.\n\n-   More females wear contacts and more males wear glasses.\n\n## No association\n\n-   Suppose table had been as shown below:\n\n\\scriptsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_url <- \"http://ritsokiguess.site/datafiles/eyewear2.txt\"\neyewear2 <- read_table(my_url)\neyewear2 %>% \n   pivot_longer(contacts:none, names_to = \"eyewear\", \n                values_to = \"frequency\") -> eyes2\nxt2 <- xtabs(frequency ~ gender + eyewear, data = eyes2)\nxt2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        eyewear\ngender   contacts glasses none\n  female      150      30  120\n  male         75      16   62\n```\n:::\n\n```{.r .cell-code}\nprop.table(xt2, margin = 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        eyewear\ngender    contacts   glasses      none\n  female 0.5000000 0.1000000 0.4000000\n  male   0.4901961 0.1045752 0.4052288\n```\n:::\n:::\n\n\n\\normalsize\n\n## Comments\n\n-   Females and males wear contacts and glasses *in same proportions*\n    -   though more females and more contact-wearers.\n-   No *association* between gender and eyewear.\n\n## Analysis for revised data\n\n\n::: {.cell}\n\n```{.r .cell-code}\neyes.2 <- glm(frequency ~ gender * eyewear,\n  data = eyes2,\n  family = \"poisson\"\n)\ndrop1(eyes.2, test = \"Chisq\")\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Df\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Deviance\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"AIC\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"LRT\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>Chi)\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"NA\",\"2\":\"2.176037e-14\",\"3\":\"47.46718\",\"4\":\"NA\",\"5\":\"NA\",\"_rn_\":\"<none>\"},{\"1\":\"2\",\"2\":\"4.732267e-02\",\"3\":\"43.51450\",\"4\":\"0.04732267\",\"5\":\"0.9766164\",\"_rn_\":\"gender:eyewear\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nNo longer any association. Take out interaction.\n\n## No interaction\n\n\\small\n\n\n::: {.cell}\n\n```{.r .cell-code}\neyes.3 <- update(eyes.2, . ~ . - gender:eyewear)\ndrop1(eyes.3, test = \"Chisq\")\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Df\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Deviance\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"AIC\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"LRT\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>Chi)\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"NA\",\"2\":\"0.04732267\",\"3\":\"43.51450\",\"4\":\"NA\",\"5\":\"NA\",\"_rn_\":\"<none>\"},{\"1\":\"1\",\"2\":\"48.62389131\",\"3\":\"90.09107\",\"4\":\"48.57657\",\"5\":\"3.176418e-12\",\"_rn_\":\"gender\"},{\"1\":\"2\",\"2\":\"138.13041408\",\"3\":\"177.59759\",\"4\":\"138.08309\",\"5\":\"1.036663e-30\",\"_rn_\":\"eyewear\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\\normalsize\n\n-   More females (gender effect)\n\n-   more contact-wearers (eyewear effect)\n\n-   no association (no interaction).\n\n## Chest pain, being overweight and being a smoker\n\n-   In a hospital emergency department, 176 subjects who attended for\n    acute chest pain took part in a study.\n\n-   Each subject had a normal or abnormal electrocardiogram reading\n    (ECG), were overweight (as judged by BMI) or not, and were a smoker\n    or not.\n\n-   How are these three variables related, or not?\n\n## The data\n\nIn modelling-friendly format:\n\n```         \n\necg bmi smoke count\nabnormal overweight yes 47\nabnormal overweight no 10\nabnormal normalweight yes 8 \nabnormal normalweight no 6\nnormal overweight yes 25 \nnormal overweight no 15 \nnormal normalweight yes 35\nnormal normalweight no 30\n```\n\n## First step\n\n\\small\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_url <- \"http://ritsokiguess.site/datafiles/ecg.txt\"\nchest <- read_delim(my_url, \" \")\nchest.1 <- glm(count ~ ecg * bmi * smoke,\n  data = chest,\n  family = \"poisson\"\n)\ndrop1(chest.1, test = \"Chisq\")\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Df\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Deviance\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"AIC\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"LRT\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>Chi)\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"NA\",\"2\":\"-1.475170e-28\",\"3\":\"53.70730\",\"4\":\"NA\",\"5\":\"NA\",\"_rn_\":\"<none>\"},{\"1\":\"1\",\"2\":\"1.388544e+00\",\"3\":\"53.09584\",\"4\":\"1.388544\",\"5\":\"0.2386511\",\"_rn_\":\"ecg:bmi:smoke\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\\normalsize\n\nThat 3-way interaction comes out.\n\n## Removing the 3-way interaction\n\n\\small\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchest.2 <- update(chest.1, . ~ . - ecg:bmi:smoke)\ndrop1(chest.2, test = \"Chisq\")\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Df\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Deviance\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"AIC\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"LRT\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>Chi)\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"NA\",\"2\":\"1.388544\",\"3\":\"53.09584\",\"4\":\"NA\",\"5\":\"NA\",\"_rn_\":\"<none>\"},{\"1\":\"1\",\"2\":\"29.019513\",\"3\":\"78.72681\",\"4\":\"27.630969\",\"5\":\"1.468094e-07\",\"_rn_\":\"ecg:bmi\"},{\"1\":\"1\",\"2\":\"4.893513\",\"3\":\"54.60081\",\"4\":\"3.504968\",\"5\":\"6.118501e-02\",\"_rn_\":\"ecg:smoke\"},{\"1\":\"1\",\"2\":\"4.468863\",\"3\":\"54.17616\",\"4\":\"3.080319\",\"5\":\"7.924499e-02\",\"_rn_\":\"bmi:smoke\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\\normalsize\n\nAt $\\alpha=0.05$, `bmi:smoke` comes out.\n\n## Removing `bmi:smoke`\n\n\\small\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchest.3 <- update(chest.2, . ~ . - bmi:smoke)\ndrop1(chest.3, test = \"Chisq\")\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Df\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Deviance\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"AIC\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"LRT\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>Chi)\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"NA\",\"2\":\"4.468863\",\"3\":\"54.17616\",\"4\":\"NA\",\"5\":\"NA\",\"_rn_\":\"<none>\"},{\"1\":\"1\",\"2\":\"36.562474\",\"3\":\"84.26977\",\"4\":\"32.09361\",\"5\":\"1.469197e-08\",\"_rn_\":\"ecg:bmi\"},{\"1\":\"1\",\"2\":\"12.436473\",\"3\":\"60.14377\",\"4\":\"7.96761\",\"5\":\"4.762177e-03\",\"_rn_\":\"ecg:smoke\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\\normalsize\n\n`ecg:smoke` has become significant. So we have to stop.\n\n## Understanding the final model\n\n-   Thinking of `ecg` as \"response\" that might depend on anything else.\n\n-   What is associated with `ecg`? Both `bmi` on its own and `smoke` on\n    its own, but *not* the combination of both.\n\n-   `ecg:bmi` table:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxtabs(count ~ ecg + bmi, data = chest)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          bmi\necg        normalweight overweight\n  abnormal           14         57\n  normal             65         40\n```\n:::\n:::\n\n\n-   Most normal weight people have a normal ECG, but a majority of\n    overweight people have an *abnormal* ECG. That is, knowing about BMI\n    says something about likely ECG.\n\n\n## `ecg:smoke`\n\n-   `ecg:smoke` table:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxtabs(count ~ ecg + smoke, data = chest)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          smoke\necg        no yes\n  abnormal 16  55\n  normal   45  60\n```\n:::\n:::\n\n\n-   Most nonsmokers have a normal ECG, but smokers are about 50--50\n    normal and abnormal ECG.\n\n-   Don't look at `smoke:bmi` table since not significant.\n\n## Simpson's paradox: the airlines example\n\n```         \n               Alaska Airlines       America West\nAirport       On time    Delayed   On time    Delayed\nLos Angeles      497        62        694       117\nPhoenix          221        12       4840       415\nSan Diego        212        20        383        65\nSan Francisco    503       102        320       129\nSeattle         1841       305        201        61\n\nTotal           3274       501       6438       787\n```\n\nUse `status` as variable name for \"on time/delayed\".\n\n-   Alaska: 13.3% flights delayed ($501/(3274+501)$).\n\n-   America West: 10.9% ($787/(6438+787)$).\n\n-   America West more punctual, right?\n\n## Arranging the data\n\n-   Can only have single thing in columns, so we have to construct\n    column names like this: \\small\n\n```         \n\nairport    aa_ontime aa_delayed aw_ontime aw_delayed\nLosAngeles   497          62       694        117\nPhoenix      221          12      4840        415\nSanDiego     212          20       383         65\nSanFrancisco 503         102       320        129\nSeattle     1841         305       201         61\n```\n\n\\normalsize\n\n-   Read in:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_url <- \"http://ritsokiguess.site/datafiles/airlines.txt\"\nairlines <- read_table(my_url)\n```\n:::\n\n\n## Tidying\n\n-   Some tidying gets us the right layout, with frequencies all in one\n    column and the airline and delayed/on time status separated out.\n    This uses one of the fancy versions of `pivot_longer`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nairlines %>%\n   pivot_longer(-airport, \n                names_to = c(\"airline\", \"status\"), \n                names_sep = \"_\", \n                values_to = \"freq\" ) -> punctual\n```\n:::\n\n\n## The data frame `punctual`\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"airport\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"airline\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"status\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"freq\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"LosAngeles\",\"2\":\"aa\",\"3\":\"ontime\",\"4\":\"497\"},{\"1\":\"LosAngeles\",\"2\":\"aa\",\"3\":\"delayed\",\"4\":\"62\"},{\"1\":\"LosAngeles\",\"2\":\"aw\",\"3\":\"ontime\",\"4\":\"694\"},{\"1\":\"LosAngeles\",\"2\":\"aw\",\"3\":\"delayed\",\"4\":\"117\"},{\"1\":\"Phoenix\",\"2\":\"aa\",\"3\":\"ontime\",\"4\":\"221\"},{\"1\":\"Phoenix\",\"2\":\"aa\",\"3\":\"delayed\",\"4\":\"12\"},{\"1\":\"Phoenix\",\"2\":\"aw\",\"3\":\"ontime\",\"4\":\"4840\"},{\"1\":\"Phoenix\",\"2\":\"aw\",\"3\":\"delayed\",\"4\":\"415\"},{\"1\":\"SanDiego\",\"2\":\"aa\",\"3\":\"ontime\",\"4\":\"212\"},{\"1\":\"SanDiego\",\"2\":\"aa\",\"3\":\"delayed\",\"4\":\"20\"},{\"1\":\"SanDiego\",\"2\":\"aw\",\"3\":\"ontime\",\"4\":\"383\"},{\"1\":\"SanDiego\",\"2\":\"aw\",\"3\":\"delayed\",\"4\":\"65\"},{\"1\":\"SanFrancisco\",\"2\":\"aa\",\"3\":\"ontime\",\"4\":\"503\"},{\"1\":\"SanFrancisco\",\"2\":\"aa\",\"3\":\"delayed\",\"4\":\"102\"},{\"1\":\"SanFrancisco\",\"2\":\"aw\",\"3\":\"ontime\",\"4\":\"320\"},{\"1\":\"SanFrancisco\",\"2\":\"aw\",\"3\":\"delayed\",\"4\":\"129\"},{\"1\":\"Seattle\",\"2\":\"aa\",\"3\":\"ontime\",\"4\":\"1841\"},{\"1\":\"Seattle\",\"2\":\"aa\",\"3\":\"delayed\",\"4\":\"305\"},{\"1\":\"Seattle\",\"2\":\"aw\",\"3\":\"ontime\",\"4\":\"201\"},{\"1\":\"Seattle\",\"2\":\"aw\",\"3\":\"delayed\",\"4\":\"61\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n## Proportions delayed by airline\n\n-   Two-step process: get appropriate subtable:\n\n\\small\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxt <- xtabs(freq ~ airline + status, data = punctual)\nxt\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       status\nairline delayed ontime\n     aa     501   3274\n     aw     787   6438\n```\n:::\n:::\n\n\n\\normalsize\n\n-   and then calculate appropriate proportions:\n\n\\small\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.table(xt, margin = 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       status\nairline   delayed    ontime\n     aa 0.1327152 0.8672848\n     aw 0.1089273 0.8910727\n```\n:::\n:::\n\n\n\\normalsize\n\n-   More of Alaska Airlines' flights delayed (13.3% vs. 10.9%).\n\n## Proportion delayed by airport, for each airline\n\n\\footnotesize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxt <- xtabs(freq ~ airline + status + airport, data = punctual)\nxp <- prop.table(xt, margin = c(1, 3))\nftable(xp,\n  row.vars = c(\"airport\", \"airline\"),\n  col.vars = \"status\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                     status    delayed     ontime\nairport      airline                             \nLosAngeles   aa             0.11091234 0.88908766\n             aw             0.14426634 0.85573366\nPhoenix      aa             0.05150215 0.94849785\n             aw             0.07897241 0.92102759\nSanDiego     aa             0.08620690 0.91379310\n             aw             0.14508929 0.85491071\nSanFrancisco aa             0.16859504 0.83140496\n             aw             0.28730512 0.71269488\nSeattle      aa             0.14212488 0.85787512\n             aw             0.23282443 0.76717557\n```\n:::\n:::\n\n\n\\normalsize\n\n## Simpson's Paradox\n\n\n```{=tex}\n\\begin{tabular}{|l|rr|}\n\\hline\nAirport & Alaska & America West\\\\\n\\hline\nLos Angeles & 11.4 & 14.4\\\\\nPhoenix & 5.2 & 7.9\\\\\nSan Diego & 8.6 & 14.5\\\\\nSan Francisco & 16.9 & 28.7\\\\\nSeattle & 14.2 & 23.2 \\\\\n\\hline\nTotal & 13.3 & 10.9 \\\\\n\\hline\n\\end{tabular}\n```\n\n-   America West more punctual overall,\n\n-   but worse at *every single* airport!\n\n-   How is that possible?\n\n-   Log-linear analysis sheds some light.\n\n## Model 1 and output\n\n\n::: {.cell}\n\n```{.r .cell-code}\npunctual.1 <- glm(freq ~ airport * airline * status,\n  data = punctual, family = \"poisson\"\n)\ndrop1(punctual.1, test = \"Chisq\")\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Df\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Deviance\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"AIC\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"LRT\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>Chi)\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"NA\",\"2\":\"4.662937e-13\",\"3\":\"183.4348\",\"4\":\"NA\",\"5\":\"NA\",\"_rn_\":\"<none>\"},{\"1\":\"4\",\"2\":\"3.216569e+00\",\"3\":\"178.6513\",\"4\":\"3.216569\",\"5\":\"0.5222589\",\"_rn_\":\"airport:airline:status\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n## Remove 3-way interaction\n\n\\footnotesize\n\n\n::: {.cell}\n\n```{.r .cell-code}\npunctual.2 <- update(punctual.1, ~ . - airport:airline:status)\ndrop1(punctual.2, test = \"Chisq\")\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Df\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Deviance\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"AIC\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"LRT\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>Chi)\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"NA\",\"2\":\"3.216569\",\"3\":\"178.6513\",\"4\":\"NA\",\"5\":\"NA\",\"_rn_\":\"<none>\"},{\"1\":\"4\",\"2\":\"6432.454138\",\"3\":\"6599.8889\",\"4\":\"6429.23757\",\"5\":\"0.000000e+00\",\"_rn_\":\"airport:airline\"},{\"1\":\"4\",\"2\":\"240.107798\",\"3\":\"407.5426\",\"4\":\"236.89123\",\"5\":\"4.334046e-50\",\"_rn_\":\"airport:status\"},{\"1\":\"1\",\"2\":\"45.465141\",\"3\":\"218.8999\",\"4\":\"42.24857\",\"5\":\"8.037869e-11\",\"_rn_\":\"airline:status\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\\normalsize\n\nStop here.\n\n## Understanding the significance\n\n-   `airline:status`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxt <- xtabs(freq ~ airline + status, data = punctual)\nprop.table(xt, margin = 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       status\nairline   delayed    ontime\n     aa 0.1327152 0.8672848\n     aw 0.1089273 0.8910727\n```\n:::\n:::\n\n\n-   More of Alaska Airlines' flights delayed overall.\n\n-   Saw this before.\n\n## Understanding the significance (2)\n\n-   `airport:status`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxt <- xtabs(freq ~ airport + status, data = punctual)\nprop.table(xt, margin = 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n              status\nairport           delayed     ontime\n  LosAngeles   0.13065693 0.86934307\n  Phoenix      0.07780612 0.92219388\n  SanDiego     0.12500000 0.87500000\n  SanFrancisco 0.21916509 0.78083491\n  Seattle      0.15199336 0.84800664\n```\n:::\n:::\n\n\n-   Flights into San Francisco (and maybe Seattle) are often late, and\n    flights into Phoenix are usually on time.\n\n-   Considerable variation among airports.\n\n## Understanding the significance (3)\n\n-   `airport:airline`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxt <- xtabs(freq ~ airport + airline, data = punctual)\nprop.table(xt, margin = 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n              airline\nairport                aa         aw\n  LosAngeles   0.14807947 0.11224913\n  Phoenix      0.06172185 0.72733564\n  SanDiego     0.06145695 0.06200692\n  SanFrancisco 0.16026490 0.06214533\n  Seattle      0.56847682 0.03626298\n```\n:::\n:::\n\n\n-   What fraction of each airline's flights are to each airport.\n\n-   Most of Alaska Airlines' flights to Seattle and San Francisco.\n\n-   Most of America West's flights to Phoenix.\n\n## The resolution\n\n-   Most of America West's flights to Phoenix, where it is easy to be on\n    time.\n\n-   Most of Alaska Airlines' flights to San Francisco and Seattle, where\n    it is difficult to be on time.\n\n-   Overall comparison looks bad for Alaska because of this.\n\n-   But, *comparing like with like*, if you compare each airline's\n    performance *to the same airport*, Alaska does better.\n\n-   Aggregating over the very different airports was a (big) mistake:\n    that was the cause of the Simpson's paradox.\n\n-   Alaska Airlines is *more* punctual when you do the proper\n    comparison.\n\n## Ovarian cancer: a four-way table\n\n-   Retrospective study of ovarian cancer done in 1973.\n\n-   Information about 299 women operated on for ovarian cancer 10 years\n    previously.\n\n-   Recorded:\n\n    -   stage of cancer (early or advanced)\n\n    -   type of operation (radical or limited)\n\n    -   X-ray treatment received (yes or no)\n\n    -   10-year survival (yes or no)\n\n-   Survival looks like response (suggests logistic regression).\n\n-   Log-linear model finds any associations at all.\n\n## The data\n\nafter tidying:\n\n\\scriptsize\n\n```         \n\nstage operation xray survival freq\nearly radical no no 10\nearly radical no yes 41\nearly radical yes no 17\nearly radical yes yes 64\nearly limited no no 1\nearly limited no yes 13\nearly limited yes no 3\nearly limited yes yes 9\nadvanced radical no no 38\nadvanced radical no yes 6\nadvanced radical yes no 64\nadvanced radical yes yes 11\nadvanced limited no no 3\nadvanced limited no yes 1\nadvanced limited yes no 13\nadvanced limited yes yes 5\n\n```\n\n\\normalsize\n\n## Reading in data\n\n\\small\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_url <- \"http://ritsokiguess.site/datafiles/cancer.txt\"\ncancer <- read_delim(my_url, \" \")\ncancer %>% slice(1:6)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"stage\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"operation\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"xray\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"survival\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"freq\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"early\",\"2\":\"radical\",\"3\":\"no\",\"4\":\"no\",\"5\":\"10\"},{\"1\":\"early\",\"2\":\"radical\",\"3\":\"no\",\"4\":\"yes\",\"5\":\"41\"},{\"1\":\"early\",\"2\":\"radical\",\"3\":\"yes\",\"4\":\"no\",\"5\":\"17\"},{\"1\":\"early\",\"2\":\"radical\",\"3\":\"yes\",\"4\":\"yes\",\"5\":\"64\"},{\"1\":\"early\",\"2\":\"limited\",\"3\":\"no\",\"4\":\"no\",\"5\":\"1\"},{\"1\":\"early\",\"2\":\"limited\",\"3\":\"no\",\"4\":\"yes\",\"5\":\"13\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\\normalsize\n\n## Model 1\n\nhopefully looking familiar by now:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncancer.1 <- glm(freq ~ stage * operation * xray * survival,\n  data = cancer, family = \"poisson\"\n)\n```\n:::\n\n\n## Output 1\n\nSee what we can remove:\n\n\\scriptsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndrop1(cancer.1, test = \"Chisq\")\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Df\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Deviance\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"AIC\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"LRT\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>Chi)\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"NA\",\"2\":\"-3.774763e-15\",\"3\":\"98.12961\",\"4\":\"NA\",\"5\":\"NA\",\"_rn_\":\"<none>\"},{\"1\":\"1\",\"2\":\"6.026558e-01\",\"3\":\"96.73227\",\"4\":\"0.6026558\",\"5\":\"0.4375665\",\"_rn_\":\"stage:operation:xray:survival\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\\normalsize\n\nNon-significant interaction can come out.\n\n## Model 2\n\n\\scriptsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncancer.2 <- update(cancer.1, . ~ . - stage:operation:xray:survival)\ndrop1(cancer.2, test = \"Chisq\")\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Df\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Deviance\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"AIC\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"LRT\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>Chi)\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"NA\",\"2\":\"0.6026558\",\"3\":\"96.73227\",\"4\":\"NA\",\"5\":\"NA\",\"_rn_\":\"<none>\"},{\"1\":\"1\",\"2\":\"2.3575888\",\"3\":\"96.48720\",\"4\":\"1.7549331\",\"5\":\"0.1852578\",\"_rn_\":\"stage:operation:xray\"},{\"1\":\"1\",\"2\":\"1.1773024\",\"3\":\"95.30692\",\"4\":\"0.5746466\",\"5\":\"0.4484184\",\"_rn_\":\"stage:operation:survival\"},{\"1\":\"1\",\"2\":\"0.9557671\",\"3\":\"95.08538\",\"4\":\"0.3531113\",\"5\":\"0.5523571\",\"_rn_\":\"stage:xray:survival\"},{\"1\":\"1\",\"2\":\"1.2337838\",\"3\":\"95.36340\",\"4\":\"0.6311281\",\"5\":\"0.4269418\",\"_rn_\":\"operation:xray:survival\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\\normalsize\n\nLeast significant term is `stage:xray:survival`: remove.\n\n## Take out `stage:xray:survival`\n\n\\scriptsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncancer.3 <- update(cancer.2, . ~ . - stage:xray:survival)\ndrop1(cancer.3, test = \"Chisq\")\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Df\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Deviance\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"AIC\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"LRT\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>Chi)\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"NA\",\"2\":\"0.9557671\",\"3\":\"95.08538\",\"4\":\"NA\",\"5\":\"NA\",\"_rn_\":\"<none>\"},{\"1\":\"1\",\"2\":\"3.0866591\",\"3\":\"95.21627\",\"4\":\"2.1308920\",\"5\":\"0.1443567\",\"_rn_\":\"stage:operation:xray\"},{\"1\":\"1\",\"2\":\"1.5660529\",\"3\":\"93.69567\",\"4\":\"0.6102858\",\"5\":\"0.4346802\",\"_rn_\":\"stage:operation:survival\"},{\"1\":\"1\",\"2\":\"1.5512410\",\"3\":\"93.68085\",\"4\":\"0.5954739\",\"5\":\"0.4403102\",\"_rn_\":\"operation:xray:survival\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\\normalsize\n\n`operation:xray:survival` comes out next.\n\n## Remove `operation:xray:survival`\n\n\\scriptsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncancer.4 <- update(cancer.3, . ~ . - operation:xray:survival)\ndrop1(cancer.4, test = \"Chisq\")\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Df\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Deviance\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"AIC\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"LRT\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>Chi)\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"NA\",\"2\":\"1.551241\",\"3\":\"93.68085\",\"4\":\"NA\",\"5\":\"NA\",\"_rn_\":\"<none>\"},{\"1\":\"1\",\"2\":\"1.697682\",\"3\":\"91.82729\",\"4\":\"0.1464406\",\"5\":\"0.70196030\",\"_rn_\":\"xray:survival\"},{\"1\":\"1\",\"2\":\"6.841961\",\"3\":\"96.97157\",\"4\":\"5.2907197\",\"5\":\"0.02143936\",\"_rn_\":\"stage:operation:xray\"},{\"1\":\"1\",\"2\":\"1.931103\",\"3\":\"92.06072\",\"4\":\"0.3798619\",\"5\":\"0.53767715\",\"_rn_\":\"stage:operation:survival\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\\normalsize\n\n## Comments\n\n-   `stage:operation:xray` has now become significant, so won't remove\n    that.\n\n-   Shows value of removing terms one at a time.\n\n-   There are no higher-order interactions containing both `xray` and\n    `survival`, so now we get to test (and remove) `xray:survival`.\n\n## Remove `xray:survival`\n\n\\scriptsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncancer.5 <- update(cancer.4, . ~ . - xray:survival)\ndrop1(cancer.5, test = \"Chisq\")\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Df\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Deviance\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"AIC\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"LRT\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>Chi)\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"NA\",\"2\":\"1.697682\",\"3\":\"91.82729\",\"4\":\"NA\",\"5\":\"NA\",\"_rn_\":\"<none>\"},{\"1\":\"1\",\"2\":\"6.927690\",\"3\":\"95.05730\",\"4\":\"5.2300086\",\"5\":\"0.02220042\",\"_rn_\":\"stage:operation:xray\"},{\"1\":\"1\",\"2\":\"2.024220\",\"3\":\"90.15383\",\"4\":\"0.3265384\",\"5\":\"0.56770454\",\"_rn_\":\"stage:operation:survival\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\\normalsize\n\n## Remove `stage:operation:survival`\n\n\\scriptsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncancer.6 <- update(cancer.5, . ~ . - stage:operation:survival)\ndrop1(cancer.6, test = \"Chisq\")\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Df\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Deviance\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"AIC\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"LRT\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>Chi)\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"NA\",\"2\":\"2.024220\",\"3\":\"90.15383\",\"4\":\"NA\",\"5\":\"NA\",\"_rn_\":\"<none>\"},{\"1\":\"1\",\"2\":\"135.197636\",\"3\":\"221.32725\",\"4\":\"133.173416\",\"5\":\"8.284940e-31\",\"_rn_\":\"stage:survival\"},{\"1\":\"1\",\"2\":\"4.115730\",\"3\":\"90.24534\",\"4\":\"2.091510\",\"5\":\"1.481196e-01\",\"_rn_\":\"operation:survival\"},{\"1\":\"1\",\"2\":\"7.254229\",\"3\":\"93.38384\",\"4\":\"5.230009\",\"5\":\"2.220042e-02\",\"_rn_\":\"stage:operation:xray\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\\normalsize\n\n## Last step?\n\nRemove `operation:survival`.\n\n\\footnotesize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncancer.7 <- update(cancer.6, . ~ . - operation:survival)\ndrop1(cancer.7, test = \"Chisq\")\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Df\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Deviance\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"AIC\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"LRT\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>Chi)\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"NA\",\"2\":\"4.115730\",\"3\":\"90.24534\",\"4\":\"NA\",\"5\":\"NA\",\"_rn_\":\"<none>\"},{\"1\":\"1\",\"2\":\"136.729112\",\"3\":\"220.85872\",\"4\":\"132.613382\",\"5\":\"1.098503e-30\",\"_rn_\":\"stage:survival\"},{\"1\":\"1\",\"2\":\"9.345738\",\"3\":\"93.47535\",\"4\":\"5.230009\",\"5\":\"2.220042e-02\",\"_rn_\":\"stage:operation:xray\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\\normalsize\n\nFinally done!\n\n## Conclusions\n\n-   What matters is things associated with `survival` (`survival` is\n    \"response\").\n\n-   Only significant such term is `stage:survival`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxt <- xtabs(freq ~ stage + survival, data = cancer)\nprop.table(xt, margin = 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          survival\nstage             no       yes\n  advanced 0.8368794 0.1631206\n  early    0.1962025 0.8037975\n```\n:::\n:::\n\n\n-   Most people in early stage of cancer survived, and most people in\n    advanced stage did not survive.\n\n-   This true *regardless* of type of operation or whether or not X-ray\n    treatment was received. These things have no impact on survival.\n\n## What about that other interaction?\n\n\\footnotesize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxt <- xtabs(freq ~ operation + xray + stage, data = cancer)\nftable(prop.table(xt, margin = 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n               stage   advanced      early\noperation xray                            \nlimited   no         0.02836879 0.08860759\n          yes        0.12765957 0.07594937\nradical   no         0.31205674 0.32278481\n          yes        0.53191489 0.51265823\n```\n:::\n:::\n\n\n\\normalsize\n\n-   Out of the people at each stage of cancer (since `margin=3` and\n    `stage` was listed 3rd).\n\n-   The association is between `stage` and `xray` *only for those who\n    had the limited operation*.\n\n-   For those who had the radical operation, there was no association\n    between `stage` and `xray`.\n\n-   This is of less interest than associations with `survival`.\n\n## General procedure\n\n-   Start with \"complete model\" including all possible interactions.\n\n-   `drop1` gives highest-order interaction(s) remaining, remove least\n    non-significant.\n\n-   Repeat as necessary until everything significant.\n\n-   Look at subtables of significant interactions.\n\n-   Main effects not usually very interesting.\n\n-   Interactions with \"response\" usually of most interest: show\n    association with response.\n",
    "supporting": [
      "multiway_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"multiway_files/libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"multiway_files/libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ],
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}